/*
 * Software Development Kit for Fisilink
 * @file: DestPost.c
 * @description: C language expression for DestPost module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/DestPostOpr.h>


int insertDestPostHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostCtlCommon");
    hdr->name          = "DestPostCtlCommon";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostCtlCommon;
    hdr->write         = writeDestPostCtlCommon;
    hdr->set           = setDestPostCtlCommon;
    hdr->fldSet        = fldSetDestPostCtlCommon;
    hdr->fldGet        = fldGetDestPostCtlCommon;
    hdr->print         = printDestPostCtlCommon;
    hdr->reset         = resetDestPostCtlCommon;
    hdr->destroy       = destroyDestPostCtlCommon;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlCpuStats");
    hdr->name          = "CtlCpuStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlCpuStats;
    hdr->write         = writeCtlCpuStats;
    hdr->set           = setCtlCpuStats;
    hdr->fldSet        = fldSetCtlCpuStats;
    hdr->fldGet        = fldGetCtlCpuStats;
    hdr->print         = printCtlCpuStats;
    hdr->reset         = resetCtlCpuStats;
    hdr->destroy       = destroyCtlCpuStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdDest");
    hdr->name          = "CtlFwdDest";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdDest;
    hdr->write         = writeCtlFwdDest;
    hdr->set           = setCtlFwdDest;
    hdr->fldSet        = fldSetCtlFwdDest;
    hdr->fldGet        = fldGetCtlFwdDest;
    hdr->print         = printCtlFwdDest;
    hdr->reset         = resetCtlFwdDest;
    hdr->destroy       = destroyCtlFwdDest;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdEgressFilter");
    hdr->name          = "CtlFwdEgressFilter";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000018;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdEgressFilter;
    hdr->write         = writeCtlFwdEgressFilter;
    hdr->set           = setCtlFwdEgressFilter;
    hdr->fldSet        = fldSetCtlFwdEgressFilter;
    hdr->fldGet        = fldGetCtlFwdEgressFilter;
    hdr->print         = printCtlFwdEgressFilter;
    hdr->reset         = resetCtlFwdEgressFilter;
    hdr->destroy       = destroyCtlFwdEgressFilter;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdEgressSpan");
    hdr->name          = "CtlFwdEgressSpan";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdEgressSpan;
    hdr->write         = writeCtlFwdEgressSpan;
    hdr->set           = setCtlFwdEgressSpan;
    hdr->fldSet        = fldSetCtlFwdEgressSpan;
    hdr->fldGet        = fldGetCtlFwdEgressSpan;
    hdr->print         = printCtlFwdEgressSpan;
    hdr->reset         = resetCtlFwdEgressSpan;
    hdr->destroy       = destroyCtlFwdEgressSpan;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdExcp");
    hdr->name          = "CtlFwdExcp";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000028;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdExcp;
    hdr->write         = writeCtlFwdExcp;
    hdr->set           = setCtlFwdExcp;
    hdr->fldSet        = fldSetCtlFwdExcp;
    hdr->fldGet        = fldGetCtlFwdExcp;
    hdr->print         = printCtlFwdExcp;
    hdr->reset         = resetCtlFwdExcp;
    hdr->destroy       = destroyCtlFwdExcp;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdLog");
    hdr->name          = "CtlFwdLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdLog;
    hdr->write         = writeCtlFwdLog;
    hdr->set           = setCtlFwdLog;
    hdr->fldSet        = fldSetCtlFwdLog;
    hdr->fldGet        = fldGetCtlFwdLog;
    hdr->print         = printCtlFwdLog;
    hdr->reset         = resetCtlFwdLog;
    hdr->destroy       = destroyCtlFwdLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdMcast");
    hdr->name          = "CtlFwdMcast";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000038;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdMcast;
    hdr->write         = writeCtlFwdMcast;
    hdr->set           = setCtlFwdMcast;
    hdr->fldSet        = fldSetCtlFwdMcast;
    hdr->fldGet        = fldGetCtlFwdMcast;
    hdr->print         = printCtlFwdMcast;
    hdr->reset         = resetCtlFwdMcast;
    hdr->destroy       = destroyCtlFwdMcast;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdPortIsolate");
    hdr->name          = "CtlFwdPortIsolate";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdPortIsolate;
    hdr->write         = writeCtlFwdPortIsolate;
    hdr->set           = setCtlFwdPortIsolate;
    hdr->fldSet        = fldSetCtlFwdPortIsolate;
    hdr->fldGet        = fldGetCtlFwdPortIsolate;
    hdr->print         = printCtlFwdPortIsolate;
    hdr->reset         = resetCtlFwdPortIsolate;
    hdr->destroy       = destroyCtlFwdPortIsolate;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlFwdUnknownFilter");
    hdr->name          = "CtlFwdUnknownFilter";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000048;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlFwdUnknownFilter;
    hdr->write         = writeCtlFwdUnknownFilter;
    hdr->set           = setCtlFwdUnknownFilter;
    hdr->fldSet        = fldSetCtlFwdUnknownFilter;
    hdr->fldGet        = fldGetCtlFwdUnknownFilter;
    hdr->print         = printCtlFwdUnknownFilter;
    hdr->reset         = resetCtlFwdUnknownFilter;
    hdr->destroy       = destroyCtlFwdUnknownFilter;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemAclTsn");
    hdr->name          = "DestPostDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemAclTsn;
    hdr->write         = writeDestPostDsMemAclTsn;
    hdr->set           = setDestPostDsMemAclTsn;
    hdr->fldSet        = fldSetDestPostDsMemAclTsn;
    hdr->fldGet        = fldGetDestPostDsMemAclTsn;
    hdr->print         = printDestPostDsMemAclTsn;
    hdr->reset         = resetDestPostDsMemAclTsn;
    hdr->destroy       = destroyDestPostDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCpuStats");
    hdr->name          = "DsMemCpuStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000058;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCpuStats;
    hdr->write         = writeDsMemCpuStats;
    hdr->set           = setDsMemCpuStats;
    hdr->fldSet        = fldSetDsMemCpuStats;
    hdr->fldGet        = fldGetDsMemCpuStats;
    hdr->print         = printDsMemCpuStats;
    hdr->reset         = resetDsMemCpuStats;
    hdr->destroy       = destroyDsMemCpuStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemFlowColorStats");
    hdr->name          = "DestPostDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemFlowColorStats;
    hdr->write         = writeDestPostDsMemFlowColorStats;
    hdr->set           = setDestPostDsMemFlowColorStats;
    hdr->fldSet        = fldSetDestPostDsMemFlowColorStats;
    hdr->fldGet        = fldGetDestPostDsMemFlowColorStats;
    hdr->print         = printDestPostDsMemFlowColorStats;
    hdr->reset         = resetDestPostDsMemFlowColorStats;
    hdr->destroy       = destroyDestPostDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemFlowPolice");
    hdr->name          = "DestPostDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemFlowPolice;
    hdr->write         = writeDestPostDsMemFlowPolice;
    hdr->set           = setDestPostDsMemFlowPolice;
    hdr->fldSet        = fldSetDestPostDsMemFlowPolice;
    hdr->fldGet        = fldGetDestPostDsMemFlowPolice;
    hdr->print         = printDestPostDsMemFlowPolice;
    hdr->reset         = resetDestPostDsMemFlowPolice;
    hdr->destroy       = destroyDestPostDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemFlowPoliceCfg");
    hdr->name          = "DestPostDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemFlowPoliceCfg;
    hdr->write         = writeDestPostDsMemFlowPoliceCfg;
    hdr->set           = setDestPostDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetDestPostDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetDestPostDsMemFlowPoliceCfg;
    hdr->print         = printDestPostDsMemFlowPoliceCfg;
    hdr->reset         = resetDestPostDsMemFlowPoliceCfg;
    hdr->destroy       = destroyDestPostDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostRoute");
    hdr->name          = "DestPostDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostRoute;
    hdr->write         = writeDestPostDsMemHostRoute;
    hdr->set           = setDestPostDsMemHostRoute;
    hdr->fldSet        = fldSetDestPostDsMemHostRoute;
    hdr->fldGet        = fldGetDestPostDsMemHostRoute;
    hdr->print         = printDestPostDsMemHostRoute;
    hdr->reset         = resetDestPostDsMemHostRoute;
    hdr->destroy       = destroyDestPostDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostRouteLeft");
    hdr->name          = "DestPostDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostRouteLeft;
    hdr->write         = writeDestPostDsMemHostRouteLeft;
    hdr->set           = setDestPostDsMemHostRouteLeft;
    hdr->fldSet        = fldSetDestPostDsMemHostRouteLeft;
    hdr->fldGet        = fldGetDestPostDsMemHostRouteLeft;
    hdr->print         = printDestPostDsMemHostRouteLeft;
    hdr->reset         = resetDestPostDsMemHostRouteLeft;
    hdr->destroy       = destroyDestPostDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostRouteLeftKey");
    hdr->name          = "DestPostDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostRouteLeftKey;
    hdr->write         = writeDestPostDsMemHostRouteLeftKey;
    hdr->set           = setDestPostDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetDestPostDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetDestPostDsMemHostRouteLeftKey;
    hdr->print         = printDestPostDsMemHostRouteLeftKey;
    hdr->reset         = resetDestPostDsMemHostRouteLeftKey;
    hdr->destroy       = destroyDestPostDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostRouteLeftValid");
    hdr->name          = "DestPostDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostRouteLeftValid;
    hdr->write         = writeDestPostDsMemHostRouteLeftValid;
    hdr->set           = setDestPostDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetDestPostDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetDestPostDsMemHostRouteLeftValid;
    hdr->print         = printDestPostDsMemHostRouteLeftValid;
    hdr->reset         = resetDestPostDsMemHostRouteLeftValid;
    hdr->destroy       = destroyDestPostDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostRouteRight");
    hdr->name          = "DestPostDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostRouteRight;
    hdr->write         = writeDestPostDsMemHostRouteRight;
    hdr->set           = setDestPostDsMemHostRouteRight;
    hdr->fldSet        = fldSetDestPostDsMemHostRouteRight;
    hdr->fldGet        = fldGetDestPostDsMemHostRouteRight;
    hdr->print         = printDestPostDsMemHostRouteRight;
    hdr->reset         = resetDestPostDsMemHostRouteRight;
    hdr->destroy       = destroyDestPostDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostRouteRightKey");
    hdr->name          = "DestPostDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostRouteRightKey;
    hdr->write         = writeDestPostDsMemHostRouteRightKey;
    hdr->set           = setDestPostDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetDestPostDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetDestPostDsMemHostRouteRightKey;
    hdr->print         = printDestPostDsMemHostRouteRightKey;
    hdr->reset         = resetDestPostDsMemHostRouteRightKey;
    hdr->destroy       = destroyDestPostDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostRouteRightValid");
    hdr->name          = "DestPostDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostRouteRightValid;
    hdr->write         = writeDestPostDsMemHostRouteRightValid;
    hdr->set           = setDestPostDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetDestPostDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetDestPostDsMemHostRouteRightValid;
    hdr->print         = printDestPostDsMemHostRouteRightValid;
    hdr->reset         = resetDestPostDsMemHostRouteRightValid;
    hdr->destroy       = destroyDestPostDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostTsn");
    hdr->name          = "DestPostDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostTsn;
    hdr->write         = writeDestPostDsMemHostTsn;
    hdr->set           = setDestPostDsMemHostTsn;
    hdr->fldSet        = fldSetDestPostDsMemHostTsn;
    hdr->fldGet        = fldGetDestPostDsMemHostTsn;
    hdr->print         = printDestPostDsMemHostTsn;
    hdr->reset         = resetDestPostDsMemHostTsn;
    hdr->destroy       = destroyDestPostDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostTsnLeft");
    hdr->name          = "DestPostDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostTsnLeft;
    hdr->write         = writeDestPostDsMemHostTsnLeft;
    hdr->set           = setDestPostDsMemHostTsnLeft;
    hdr->fldSet        = fldSetDestPostDsMemHostTsnLeft;
    hdr->fldGet        = fldGetDestPostDsMemHostTsnLeft;
    hdr->print         = printDestPostDsMemHostTsnLeft;
    hdr->reset         = resetDestPostDsMemHostTsnLeft;
    hdr->destroy       = destroyDestPostDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemHostTsnRight");
    hdr->name          = "DestPostDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemHostTsnRight;
    hdr->write         = writeDestPostDsMemHostTsnRight;
    hdr->set           = setDestPostDsMemHostTsnRight;
    hdr->fldSet        = fldSetDestPostDsMemHostTsnRight;
    hdr->fldGet        = fldGetDestPostDsMemHostTsnRight;
    hdr->print         = printDestPostDsMemHostTsnRight;
    hdr->reset         = resetDestPostDsMemHostTsnRight;
    hdr->destroy       = destroyDestPostDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemIndvRcvyCfg");
    hdr->name          = "DestPostDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemIndvRcvyCfg;
    hdr->write         = writeDestPostDsMemIndvRcvyCfg;
    hdr->set           = setDestPostDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetDestPostDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetDestPostDsMemIndvRcvyCfg;
    hdr->print         = printDestPostDsMemIndvRcvyCfg;
    hdr->reset         = resetDestPostDsMemIndvRcvyCfg;
    hdr->destroy       = destroyDestPostDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemIndvRcvyCnt");
    hdr->name          = "DestPostDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemIndvRcvyCnt;
    hdr->write         = writeDestPostDsMemIndvRcvyCnt;
    hdr->set           = setDestPostDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetDestPostDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetDestPostDsMemIndvRcvyCnt;
    hdr->print         = printDestPostDsMemIndvRcvyCnt;
    hdr->reset         = resetDestPostDsMemIndvRcvyCnt;
    hdr->destroy       = destroyDestPostDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemIndvRcvySeq");
    hdr->name          = "DestPostDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemIndvRcvySeq;
    hdr->write         = writeDestPostDsMemIndvRcvySeq;
    hdr->set           = setDestPostDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetDestPostDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetDestPostDsMemIndvRcvySeq;
    hdr->print         = printDestPostDsMemIndvRcvySeq;
    hdr->reset         = resetDestPostDsMemIndvRcvySeq;
    hdr->destroy       = destroyDestPostDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacAgingLeft");
    hdr->name          = "DestPostDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacAgingLeft;
    hdr->write         = writeDestPostDsMemMacAgingLeft;
    hdr->set           = setDestPostDsMemMacAgingLeft;
    hdr->fldSet        = fldSetDestPostDsMemMacAgingLeft;
    hdr->fldGet        = fldGetDestPostDsMemMacAgingLeft;
    hdr->print         = printDestPostDsMemMacAgingLeft;
    hdr->reset         = resetDestPostDsMemMacAgingLeft;
    hdr->destroy       = destroyDestPostDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacAgingRight");
    hdr->name          = "DestPostDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacAgingRight;
    hdr->write         = writeDestPostDsMemMacAgingRight;
    hdr->set           = setDestPostDsMemMacAgingRight;
    hdr->fldSet        = fldSetDestPostDsMemMacAgingRight;
    hdr->fldGet        = fldGetDestPostDsMemMacAgingRight;
    hdr->print         = printDestPostDsMemMacAgingRight;
    hdr->reset         = resetDestPostDsMemMacAgingRight;
    hdr->destroy       = destroyDestPostDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacKeyLeft");
    hdr->name          = "DestPostDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacKeyLeft;
    hdr->write         = writeDestPostDsMemMacKeyLeft;
    hdr->set           = setDestPostDsMemMacKeyLeft;
    hdr->fldSet        = fldSetDestPostDsMemMacKeyLeft;
    hdr->fldGet        = fldGetDestPostDsMemMacKeyLeft;
    hdr->print         = printDestPostDsMemMacKeyLeft;
    hdr->reset         = resetDestPostDsMemMacKeyLeft;
    hdr->destroy       = destroyDestPostDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacKeyRight");
    hdr->name          = "DestPostDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacKeyRight;
    hdr->write         = writeDestPostDsMemMacKeyRight;
    hdr->set           = setDestPostDsMemMacKeyRight;
    hdr->fldSet        = fldSetDestPostDsMemMacKeyRight;
    hdr->fldGet        = fldGetDestPostDsMemMacKeyRight;
    hdr->print         = printDestPostDsMemMacKeyRight;
    hdr->reset         = resetDestPostDsMemMacKeyRight;
    hdr->destroy       = destroyDestPostDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacLeft");
    hdr->name          = "DestPostDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacLeft;
    hdr->write         = writeDestPostDsMemMacLeft;
    hdr->set           = setDestPostDsMemMacLeft;
    hdr->fldSet        = fldSetDestPostDsMemMacLeft;
    hdr->fldGet        = fldGetDestPostDsMemMacLeft;
    hdr->print         = printDestPostDsMemMacLeft;
    hdr->reset         = resetDestPostDsMemMacLeft;
    hdr->destroy       = destroyDestPostDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacRight");
    hdr->name          = "DestPostDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacRight;
    hdr->write         = writeDestPostDsMemMacRight;
    hdr->set           = setDestPostDsMemMacRight;
    hdr->fldSet        = fldSetDestPostDsMemMacRight;
    hdr->fldGet        = fldGetDestPostDsMemMacRight;
    hdr->print         = printDestPostDsMemMacRight;
    hdr->reset         = resetDestPostDsMemMacRight;
    hdr->destroy       = destroyDestPostDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacStaticLeft");
    hdr->name          = "DestPostDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacStaticLeft;
    hdr->write         = writeDestPostDsMemMacStaticLeft;
    hdr->set           = setDestPostDsMemMacStaticLeft;
    hdr->fldSet        = fldSetDestPostDsMemMacStaticLeft;
    hdr->fldGet        = fldGetDestPostDsMemMacStaticLeft;
    hdr->print         = printDestPostDsMemMacStaticLeft;
    hdr->reset         = resetDestPostDsMemMacStaticLeft;
    hdr->destroy       = destroyDestPostDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacStaticRight");
    hdr->name          = "DestPostDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacStaticRight;
    hdr->write         = writeDestPostDsMemMacStaticRight;
    hdr->set           = setDestPostDsMemMacStaticRight;
    hdr->fldSet        = fldSetDestPostDsMemMacStaticRight;
    hdr->fldGet        = fldGetDestPostDsMemMacStaticRight;
    hdr->print         = printDestPostDsMemMacStaticRight;
    hdr->reset         = resetDestPostDsMemMacStaticRight;
    hdr->destroy       = destroyDestPostDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacTsn");
    hdr->name          = "DestPostDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacTsn;
    hdr->write         = writeDestPostDsMemMacTsn;
    hdr->set           = setDestPostDsMemMacTsn;
    hdr->fldSet        = fldSetDestPostDsMemMacTsn;
    hdr->fldGet        = fldGetDestPostDsMemMacTsn;
    hdr->print         = printDestPostDsMemMacTsn;
    hdr->reset         = resetDestPostDsMemMacTsn;
    hdr->destroy       = destroyDestPostDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacTsnLeft");
    hdr->name          = "DestPostDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacTsnLeft;
    hdr->write         = writeDestPostDsMemMacTsnLeft;
    hdr->set           = setDestPostDsMemMacTsnLeft;
    hdr->fldSet        = fldSetDestPostDsMemMacTsnLeft;
    hdr->fldGet        = fldGetDestPostDsMemMacTsnLeft;
    hdr->print         = printDestPostDsMemMacTsnLeft;
    hdr->reset         = resetDestPostDsMemMacTsnLeft;
    hdr->destroy       = destroyDestPostDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacTsnRight");
    hdr->name          = "DestPostDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacTsnRight;
    hdr->write         = writeDestPostDsMemMacTsnRight;
    hdr->set           = setDestPostDsMemMacTsnRight;
    hdr->fldSet        = fldSetDestPostDsMemMacTsnRight;
    hdr->fldGet        = fldGetDestPostDsMemMacTsnRight;
    hdr->print         = printDestPostDsMemMacTsnRight;
    hdr->reset         = resetDestPostDsMemMacTsnRight;
    hdr->destroy       = destroyDestPostDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacValidLeft");
    hdr->name          = "DestPostDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacValidLeft;
    hdr->write         = writeDestPostDsMemMacValidLeft;
    hdr->set           = setDestPostDsMemMacValidLeft;
    hdr->fldSet        = fldSetDestPostDsMemMacValidLeft;
    hdr->fldGet        = fldGetDestPostDsMemMacValidLeft;
    hdr->print         = printDestPostDsMemMacValidLeft;
    hdr->reset         = resetDestPostDsMemMacValidLeft;
    hdr->destroy       = destroyDestPostDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemMacValidRight");
    hdr->name          = "DestPostDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemMacValidRight;
    hdr->write         = writeDestPostDsMemMacValidRight;
    hdr->set           = setDestPostDsMemMacValidRight;
    hdr->fldSet        = fldSetDestPostDsMemMacValidRight;
    hdr->fldGet        = fldGetDestPostDsMemMacValidRight;
    hdr->print         = printDestPostDsMemMacValidRight;
    hdr->reset         = resetDestPostDsMemMacValidRight;
    hdr->destroy       = destroyDestPostDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMcastPort");
    hdr->name          = "DsMemMcastPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000148;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMcastPort;
    hdr->write         = writeDsMemMcastPort;
    hdr->set           = setDsMemMcastPort;
    hdr->fldSet        = fldSetDsMemMcastPort;
    hdr->fldGet        = fldGetDsMemMcastPort;
    hdr->print         = printDsMemMcastPort;
    hdr->reset         = resetDsMemMcastPort;
    hdr->destroy       = destroyDsMemMcastPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemPortColorStats");
    hdr->name          = "DestPostDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemPortColorStats;
    hdr->write         = writeDestPostDsMemPortColorStats;
    hdr->set           = setDestPostDsMemPortColorStats;
    hdr->fldSet        = fldSetDestPostDsMemPortColorStats;
    hdr->fldGet        = fldGetDestPostDsMemPortColorStats;
    hdr->print         = printDestPostDsMemPortColorStats;
    hdr->reset         = resetDestPostDsMemPortColorStats;
    hdr->destroy       = destroyDestPostDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemPortPolice");
    hdr->name          = "DestPostDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemPortPolice;
    hdr->write         = writeDestPostDsMemPortPolice;
    hdr->set           = setDestPostDsMemPortPolice;
    hdr->fldSet        = fldSetDestPostDsMemPortPolice;
    hdr->fldGet        = fldGetDestPostDsMemPortPolice;
    hdr->print         = printDestPostDsMemPortPolice;
    hdr->reset         = resetDestPostDsMemPortPolice;
    hdr->destroy       = destroyDestPostDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemPortPoliceCfg");
    hdr->name          = "DestPostDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemPortPoliceCfg;
    hdr->write         = writeDestPostDsMemPortPoliceCfg;
    hdr->set           = setDestPostDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetDestPostDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetDestPostDsMemPortPoliceCfg;
    hdr->print         = printDestPostDsMemPortPoliceCfg;
    hdr->reset         = resetDestPostDsMemPortPoliceCfg;
    hdr->destroy       = destroyDestPostDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemRouteTsn");
    hdr->name          = "DestPostDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemRouteTsn;
    hdr->write         = writeDestPostDsMemRouteTsn;
    hdr->set           = setDestPostDsMemRouteTsn;
    hdr->fldSet        = fldSetDestPostDsMemRouteTsn;
    hdr->fldGet        = fldGetDestPostDsMemRouteTsn;
    hdr->print         = printDestPostDsMemRouteTsn;
    hdr->reset         = resetDestPostDsMemRouteTsn;
    hdr->destroy       = destroyDestPostDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemSrcPortEgressMask");
    hdr->name          = "DsMemSrcPortEgressMask";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemSrcPortEgressMask;
    hdr->write         = writeDsMemSrcPortEgressMask;
    hdr->set           = setDsMemSrcPortEgressMask;
    hdr->fldSet        = fldSetDsMemSrcPortEgressMask;
    hdr->fldGet        = fldGetDsMemSrcPortEgressMask;
    hdr->print         = printDsMemSrcPortEgressMask;
    hdr->reset         = resetDsMemSrcPortEgressMask;
    hdr->destroy       = destroyDsMemSrcPortEgressMask;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemStreamRcvyCfg");
    hdr->name          = "DestPostDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemStreamRcvyCfg;
    hdr->write         = writeDestPostDsMemStreamRcvyCfg;
    hdr->set           = setDestPostDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetDestPostDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetDestPostDsMemStreamRcvyCfg;
    hdr->print         = printDestPostDsMemStreamRcvyCfg;
    hdr->reset         = resetDestPostDsMemStreamRcvyCfg;
    hdr->destroy       = destroyDestPostDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemStreamRcvyCnt");
    hdr->name          = "DestPostDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000300;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemStreamRcvyCnt;
    hdr->write         = writeDestPostDsMemStreamRcvyCnt;
    hdr->set           = setDestPostDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetDestPostDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetDestPostDsMemStreamRcvyCnt;
    hdr->print         = printDestPostDsMemStreamRcvyCnt;
    hdr->reset         = resetDestPostDsMemStreamRcvyCnt;
    hdr->destroy       = destroyDestPostDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostDsMemStreamRcvySeq");
    hdr->name          = "DestPostDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000310;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostDsMemStreamRcvySeq;
    hdr->write         = writeDestPostDsMemStreamRcvySeq;
    hdr->set           = setDestPostDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetDestPostDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetDestPostDsMemStreamRcvySeq;
    hdr->print         = printDestPostDsMemStreamRcvySeq;
    hdr->reset         = resetDestPostDsMemStreamRcvySeq;
    hdr->destroy       = destroyDestPostDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemTsnEdit");
    hdr->name          = "DsMemTsnEdit";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemTsnEdit;
    hdr->write         = writeDsMemTsnEdit;
    hdr->set           = setDsMemTsnEdit;
    hdr->fldSet        = fldSetDsMemTsnEdit;
    hdr->fldGet        = fldGetDsMemTsnEdit;
    hdr->print         = printDsMemTsnEdit;
    hdr->reset         = resetDsMemTsnEdit;
    hdr->destroy       = destroyDsMemTsnEdit;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemTsnSpec");
    hdr->name          = "DsMemTsnSpec";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000198;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemTsnSpec;
    hdr->write         = writeDsMemTsnSpec;
    hdr->set           = setDsMemTsnSpec;
    hdr->fldSet        = fldSetDsMemTsnSpec;
    hdr->fldGet        = fldGetDsMemTsnSpec;
    hdr->print         = printDsMemTsnSpec;
    hdr->reset         = resetDsMemTsnSpec;
    hdr->destroy       = destroyDsMemTsnSpec;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemTsnSplit");
    hdr->name          = "DsMemTsnSplit";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemTsnSplit;
    hdr->write         = writeDsMemTsnSplit;
    hdr->set           = setDsMemTsnSplit;
    hdr->fldSet        = fldSetDsMemTsnSplit;
    hdr->fldGet        = fldGetDsMemTsnSplit;
    hdr->print         = printDsMemTsnSplit;
    hdr->reset         = resetDsMemTsnSplit;
    hdr->destroy       = destroyDsMemTsnSplit;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemVlanPortMask");
    hdr->name          = "DsMemVlanPortMask";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a8;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemVlanPortMask;
    hdr->write         = writeDsMemVlanPortMask;
    hdr->set           = setDsMemVlanPortMask;
    hdr->fldSet        = fldSetDsMemVlanPortMask;
    hdr->fldGet        = fldGetDsMemVlanPortMask;
    hdr->print         = printDsMemVlanPortMask;
    hdr->reset         = resetDsMemVlanPortMask;
    hdr->destroy       = destroyDsMemVlanPortMask;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegDestPortChnlMap");
    hdr->name          = "DsRegDestPortChnlMap";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegDestPortChnlMap;
    hdr->write         = writeDsRegDestPortChnlMap;
    hdr->set           = setDsRegDestPortChnlMap;
    hdr->fldSet        = fldSetDsRegDestPortChnlMap;
    hdr->fldGet        = fldGetDsRegDestPortChnlMap;
    hdr->print         = printDsRegDestPortChnlMap;
    hdr->reset         = resetDsRegDestPortChnlMap;
    hdr->destroy       = destroyDsRegDestPortChnlMap;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegLagGrp");
    hdr->name          = "DsRegLagGrp";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b8;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegLagGrp;
    hdr->write         = writeDsRegLagGrp;
    hdr->set           = setDsRegLagGrp;
    hdr->fldSet        = fldSetDsRegLagGrp;
    hdr->fldGet        = fldGetDsRegLagGrp;
    hdr->print         = printDsRegLagGrp;
    hdr->reset         = resetDsRegLagGrp;
    hdr->destroy       = destroyDsRegLagGrp;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegLagPort");
    hdr->name          = "DsRegLagPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegLagPort;
    hdr->write         = writeDsRegLagPort;
    hdr->set           = setDsRegLagPort;
    hdr->fldSet        = fldSetDsRegLagPort;
    hdr->fldGet        = fldGetDsRegLagPort;
    hdr->print         = printDsRegLagPort;
    hdr->reset         = resetDsRegLagPort;
    hdr->destroy       = destroyDsRegLagPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostMsgAdmInfo0");
    hdr->name          = "DestPostMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000390;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostMsgAdmInfo0;
    hdr->write         = writeDestPostMsgAdmInfo0;
    hdr->set           = setDestPostMsgAdmInfo0;
    hdr->fldSet        = fldSetDestPostMsgAdmInfo0;
    hdr->fldGet        = fldGetDestPostMsgAdmInfo0;
    hdr->print         = printDestPostMsgAdmInfo0;
    hdr->reset         = resetDestPostMsgAdmInfo0;
    hdr->destroy       = destroyDestPostMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DestPostTmpDsMemMac");
    hdr->name          = "DestPostTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0003a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDestPostTmpDsMemMac;
    hdr->write         = writeDestPostTmpDsMemMac;
    hdr->set           = setDestPostTmpDsMemMac;
    hdr->fldSet        = fldSetDestPostTmpDsMemMac;
    hdr->fldGet        = fldGetDestPostTmpDsMemMac;
    hdr->print         = printDestPostTmpDsMemMac;
    hdr->reset         = resetDestPostTmpDsMemMac;
    hdr->destroy       = destroyDestPostTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
