/*
 * Software Development Kit for Fisilink
 * @file: HeaderAdjust.c
 * @description: C language expression for HeaderAdjust module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/HeaderAdjustOpr.h>


int insertHeaderAdjustHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlCommon");
    hdr->name          = "CtlCommon";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlCommon;
    hdr->write         = writeCtlCommon;
    hdr->set           = setCtlCommon;
    hdr->fldSet        = fldSetCtlCommon;
    hdr->fldGet        = fldGetCtlCommon;
    hdr->print         = printCtlCommon;
    hdr->reset         = resetCtlCommon;
    hdr->destroy       = destroyCtlCommon;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlHdrAdjLog");
    hdr->name          = "CtlHdrAdjLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlHdrAdjLog;
    hdr->write         = writeCtlHdrAdjLog;
    hdr->set           = setCtlHdrAdjLog;
    hdr->fldSet        = fldSetCtlHdrAdjLog;
    hdr->fldGet        = fldGetCtlHdrAdjLog;
    hdr->print         = printCtlHdrAdjLog;
    hdr->reset         = resetCtlHdrAdjLog;
    hdr->destroy       = destroyCtlHdrAdjLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemAclTsn");
    hdr->name          = "DsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemAclTsn;
    hdr->write         = writeDsMemAclTsn;
    hdr->set           = setDsMemAclTsn;
    hdr->fldSet        = fldSetDsMemAclTsn;
    hdr->fldGet        = fldGetDsMemAclTsn;
    hdr->print         = printDsMemAclTsn;
    hdr->reset         = resetDsMemAclTsn;
    hdr->destroy       = destroyDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemFlowColorStats");
    hdr->name          = "DsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemFlowColorStats;
    hdr->write         = writeDsMemFlowColorStats;
    hdr->set           = setDsMemFlowColorStats;
    hdr->fldSet        = fldSetDsMemFlowColorStats;
    hdr->fldGet        = fldGetDsMemFlowColorStats;
    hdr->print         = printDsMemFlowColorStats;
    hdr->reset         = resetDsMemFlowColorStats;
    hdr->destroy       = destroyDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemFlowPolice");
    hdr->name          = "DsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemFlowPolice;
    hdr->write         = writeDsMemFlowPolice;
    hdr->set           = setDsMemFlowPolice;
    hdr->fldSet        = fldSetDsMemFlowPolice;
    hdr->fldGet        = fldGetDsMemFlowPolice;
    hdr->print         = printDsMemFlowPolice;
    hdr->reset         = resetDsMemFlowPolice;
    hdr->destroy       = destroyDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemFlowPoliceCfg");
    hdr->name          = "DsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000050;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemFlowPoliceCfg;
    hdr->write         = writeDsMemFlowPoliceCfg;
    hdr->set           = setDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetDsMemFlowPoliceCfg;
    hdr->print         = printDsMemFlowPoliceCfg;
    hdr->reset         = resetDsMemFlowPoliceCfg;
    hdr->destroy       = destroyDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostRoute");
    hdr->name          = "DsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostRoute;
    hdr->write         = writeDsMemHostRoute;
    hdr->set           = setDsMemHostRoute;
    hdr->fldSet        = fldSetDsMemHostRoute;
    hdr->fldGet        = fldGetDsMemHostRoute;
    hdr->print         = printDsMemHostRoute;
    hdr->reset         = resetDsMemHostRoute;
    hdr->destroy       = destroyDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostRouteLeft");
    hdr->name          = "DsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostRouteLeft;
    hdr->write         = writeDsMemHostRouteLeft;
    hdr->set           = setDsMemHostRouteLeft;
    hdr->fldSet        = fldSetDsMemHostRouteLeft;
    hdr->fldGet        = fldGetDsMemHostRouteLeft;
    hdr->print         = printDsMemHostRouteLeft;
    hdr->reset         = resetDsMemHostRouteLeft;
    hdr->destroy       = destroyDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostRouteLeftKey");
    hdr->name          = "DsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000080;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostRouteLeftKey;
    hdr->write         = writeDsMemHostRouteLeftKey;
    hdr->set           = setDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetDsMemHostRouteLeftKey;
    hdr->print         = printDsMemHostRouteLeftKey;
    hdr->reset         = resetDsMemHostRouteLeftKey;
    hdr->destroy       = destroyDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostRouteLeftValid");
    hdr->name          = "DsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostRouteLeftValid;
    hdr->write         = writeDsMemHostRouteLeftValid;
    hdr->set           = setDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetDsMemHostRouteLeftValid;
    hdr->print         = printDsMemHostRouteLeftValid;
    hdr->reset         = resetDsMemHostRouteLeftValid;
    hdr->destroy       = destroyDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostRouteRight");
    hdr->name          = "DsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostRouteRight;
    hdr->write         = writeDsMemHostRouteRight;
    hdr->set           = setDsMemHostRouteRight;
    hdr->fldSet        = fldSetDsMemHostRouteRight;
    hdr->fldGet        = fldGetDsMemHostRouteRight;
    hdr->print         = printDsMemHostRouteRight;
    hdr->reset         = resetDsMemHostRouteRight;
    hdr->destroy       = destroyDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostRouteRightKey");
    hdr->name          = "DsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostRouteRightKey;
    hdr->write         = writeDsMemHostRouteRightKey;
    hdr->set           = setDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetDsMemHostRouteRightKey;
    hdr->print         = printDsMemHostRouteRightKey;
    hdr->reset         = resetDsMemHostRouteRightKey;
    hdr->destroy       = destroyDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostRouteRightValid");
    hdr->name          = "DsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostRouteRightValid;
    hdr->write         = writeDsMemHostRouteRightValid;
    hdr->set           = setDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetDsMemHostRouteRightValid;
    hdr->print         = printDsMemHostRouteRightValid;
    hdr->reset         = resetDsMemHostRouteRightValid;
    hdr->destroy       = destroyDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostTsn");
    hdr->name          = "DsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostTsn;
    hdr->write         = writeDsMemHostTsn;
    hdr->set           = setDsMemHostTsn;
    hdr->fldSet        = fldSetDsMemHostTsn;
    hdr->fldGet        = fldGetDsMemHostTsn;
    hdr->print         = printDsMemHostTsn;
    hdr->reset         = resetDsMemHostTsn;
    hdr->destroy       = destroyDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostTsnLeft");
    hdr->name          = "DsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostTsnLeft;
    hdr->write         = writeDsMemHostTsnLeft;
    hdr->set           = setDsMemHostTsnLeft;
    hdr->fldSet        = fldSetDsMemHostTsnLeft;
    hdr->fldGet        = fldGetDsMemHostTsnLeft;
    hdr->print         = printDsMemHostTsnLeft;
    hdr->reset         = resetDsMemHostTsnLeft;
    hdr->destroy       = destroyDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHostTsnRight");
    hdr->name          = "DsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHostTsnRight;
    hdr->write         = writeDsMemHostTsnRight;
    hdr->set           = setDsMemHostTsnRight;
    hdr->fldSet        = fldSetDsMemHostTsnRight;
    hdr->fldGet        = fldGetDsMemHostTsnRight;
    hdr->print         = printDsMemHostTsnRight;
    hdr->reset         = resetDsMemHostTsnRight;
    hdr->destroy       = destroyDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemIndvRcvyCfg");
    hdr->name          = "DsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemIndvRcvyCfg;
    hdr->write         = writeDsMemIndvRcvyCfg;
    hdr->set           = setDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetDsMemIndvRcvyCfg;
    hdr->print         = printDsMemIndvRcvyCfg;
    hdr->reset         = resetDsMemIndvRcvyCfg;
    hdr->destroy       = destroyDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemIndvRcvyCnt");
    hdr->name          = "DsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemIndvRcvyCnt;
    hdr->write         = writeDsMemIndvRcvyCnt;
    hdr->set           = setDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetDsMemIndvRcvyCnt;
    hdr->print         = printDsMemIndvRcvyCnt;
    hdr->reset         = resetDsMemIndvRcvyCnt;
    hdr->destroy       = destroyDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemIndvRcvySeq");
    hdr->name          = "DsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemIndvRcvySeq;
    hdr->write         = writeDsMemIndvRcvySeq;
    hdr->set           = setDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetDsMemIndvRcvySeq;
    hdr->print         = printDsMemIndvRcvySeq;
    hdr->reset         = resetDsMemIndvRcvySeq;
    hdr->destroy       = destroyDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacAgingLeft");
    hdr->name          = "DsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacAgingLeft;
    hdr->write         = writeDsMemMacAgingLeft;
    hdr->set           = setDsMemMacAgingLeft;
    hdr->fldSet        = fldSetDsMemMacAgingLeft;
    hdr->fldGet        = fldGetDsMemMacAgingLeft;
    hdr->print         = printDsMemMacAgingLeft;
    hdr->reset         = resetDsMemMacAgingLeft;
    hdr->destroy       = destroyDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacAgingRight");
    hdr->name          = "DsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacAgingRight;
    hdr->write         = writeDsMemMacAgingRight;
    hdr->set           = setDsMemMacAgingRight;
    hdr->fldSet        = fldSetDsMemMacAgingRight;
    hdr->fldGet        = fldGetDsMemMacAgingRight;
    hdr->print         = printDsMemMacAgingRight;
    hdr->reset         = resetDsMemMacAgingRight;
    hdr->destroy       = destroyDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacKeyLeft");
    hdr->name          = "DsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacKeyLeft;
    hdr->write         = writeDsMemMacKeyLeft;
    hdr->set           = setDsMemMacKeyLeft;
    hdr->fldSet        = fldSetDsMemMacKeyLeft;
    hdr->fldGet        = fldGetDsMemMacKeyLeft;
    hdr->print         = printDsMemMacKeyLeft;
    hdr->reset         = resetDsMemMacKeyLeft;
    hdr->destroy       = destroyDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacKeyRight");
    hdr->name          = "DsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacKeyRight;
    hdr->write         = writeDsMemMacKeyRight;
    hdr->set           = setDsMemMacKeyRight;
    hdr->fldSet        = fldSetDsMemMacKeyRight;
    hdr->fldGet        = fldGetDsMemMacKeyRight;
    hdr->print         = printDsMemMacKeyRight;
    hdr->reset         = resetDsMemMacKeyRight;
    hdr->destroy       = destroyDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacLeft");
    hdr->name          = "DsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacLeft;
    hdr->write         = writeDsMemMacLeft;
    hdr->set           = setDsMemMacLeft;
    hdr->fldSet        = fldSetDsMemMacLeft;
    hdr->fldGet        = fldGetDsMemMacLeft;
    hdr->print         = printDsMemMacLeft;
    hdr->reset         = resetDsMemMacLeft;
    hdr->destroy       = destroyDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacRight");
    hdr->name          = "DsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacRight;
    hdr->write         = writeDsMemMacRight;
    hdr->set           = setDsMemMacRight;
    hdr->fldSet        = fldSetDsMemMacRight;
    hdr->fldGet        = fldGetDsMemMacRight;
    hdr->print         = printDsMemMacRight;
    hdr->reset         = resetDsMemMacRight;
    hdr->destroy       = destroyDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacStaticLeft");
    hdr->name          = "DsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacStaticLeft;
    hdr->write         = writeDsMemMacStaticLeft;
    hdr->set           = setDsMemMacStaticLeft;
    hdr->fldSet        = fldSetDsMemMacStaticLeft;
    hdr->fldGet        = fldGetDsMemMacStaticLeft;
    hdr->print         = printDsMemMacStaticLeft;
    hdr->reset         = resetDsMemMacStaticLeft;
    hdr->destroy       = destroyDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacStaticRight");
    hdr->name          = "DsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacStaticRight;
    hdr->write         = writeDsMemMacStaticRight;
    hdr->set           = setDsMemMacStaticRight;
    hdr->fldSet        = fldSetDsMemMacStaticRight;
    hdr->fldGet        = fldGetDsMemMacStaticRight;
    hdr->print         = printDsMemMacStaticRight;
    hdr->reset         = resetDsMemMacStaticRight;
    hdr->destroy       = destroyDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacTsn");
    hdr->name          = "DsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacTsn;
    hdr->write         = writeDsMemMacTsn;
    hdr->set           = setDsMemMacTsn;
    hdr->fldSet        = fldSetDsMemMacTsn;
    hdr->fldGet        = fldGetDsMemMacTsn;
    hdr->print         = printDsMemMacTsn;
    hdr->reset         = resetDsMemMacTsn;
    hdr->destroy       = destroyDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacTsnLeft");
    hdr->name          = "DsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacTsnLeft;
    hdr->write         = writeDsMemMacTsnLeft;
    hdr->set           = setDsMemMacTsnLeft;
    hdr->fldSet        = fldSetDsMemMacTsnLeft;
    hdr->fldGet        = fldGetDsMemMacTsnLeft;
    hdr->print         = printDsMemMacTsnLeft;
    hdr->reset         = resetDsMemMacTsnLeft;
    hdr->destroy       = destroyDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacTsnRight");
    hdr->name          = "DsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacTsnRight;
    hdr->write         = writeDsMemMacTsnRight;
    hdr->set           = setDsMemMacTsnRight;
    hdr->fldSet        = fldSetDsMemMacTsnRight;
    hdr->fldGet        = fldGetDsMemMacTsnRight;
    hdr->print         = printDsMemMacTsnRight;
    hdr->reset         = resetDsMemMacTsnRight;
    hdr->destroy       = destroyDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacValidLeft");
    hdr->name          = "DsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacValidLeft;
    hdr->write         = writeDsMemMacValidLeft;
    hdr->set           = setDsMemMacValidLeft;
    hdr->fldSet        = fldSetDsMemMacValidLeft;
    hdr->fldGet        = fldGetDsMemMacValidLeft;
    hdr->print         = printDsMemMacValidLeft;
    hdr->reset         = resetDsMemMacValidLeft;
    hdr->destroy       = destroyDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacValidRight");
    hdr->name          = "DsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacValidRight;
    hdr->write         = writeDsMemMacValidRight;
    hdr->set           = setDsMemMacValidRight;
    hdr->fldSet        = fldSetDsMemMacValidRight;
    hdr->fldGet        = fldGetDsMemMacValidRight;
    hdr->print         = printDsMemMacValidRight;
    hdr->reset         = resetDsMemMacValidRight;
    hdr->destroy       = destroyDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemPortColorStats");
    hdr->name          = "DsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemPortColorStats;
    hdr->write         = writeDsMemPortColorStats;
    hdr->set           = setDsMemPortColorStats;
    hdr->fldSet        = fldSetDsMemPortColorStats;
    hdr->fldGet        = fldGetDsMemPortColorStats;
    hdr->print         = printDsMemPortColorStats;
    hdr->reset         = resetDsMemPortColorStats;
    hdr->destroy       = destroyDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemPortPolice");
    hdr->name          = "DsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemPortPolice;
    hdr->write         = writeDsMemPortPolice;
    hdr->set           = setDsMemPortPolice;
    hdr->fldSet        = fldSetDsMemPortPolice;
    hdr->fldGet        = fldGetDsMemPortPolice;
    hdr->print         = printDsMemPortPolice;
    hdr->reset         = resetDsMemPortPolice;
    hdr->destroy       = destroyDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemPortPoliceCfg");
    hdr->name          = "DsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemPortPoliceCfg;
    hdr->write         = writeDsMemPortPoliceCfg;
    hdr->set           = setDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetDsMemPortPoliceCfg;
    hdr->print         = printDsMemPortPoliceCfg;
    hdr->reset         = resetDsMemPortPoliceCfg;
    hdr->destroy       = destroyDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemRouteTsn");
    hdr->name          = "DsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemRouteTsn;
    hdr->write         = writeDsMemRouteTsn;
    hdr->set           = setDsMemRouteTsn;
    hdr->fldSet        = fldSetDsMemRouteTsn;
    hdr->fldGet        = fldGetDsMemRouteTsn;
    hdr->print         = printDsMemRouteTsn;
    hdr->reset         = resetDsMemRouteTsn;
    hdr->destroy       = destroyDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemStreamRcvyCfg");
    hdr->name          = "DsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemStreamRcvyCfg;
    hdr->write         = writeDsMemStreamRcvyCfg;
    hdr->set           = setDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetDsMemStreamRcvyCfg;
    hdr->print         = printDsMemStreamRcvyCfg;
    hdr->reset         = resetDsMemStreamRcvyCfg;
    hdr->destroy       = destroyDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemStreamRcvyCnt");
    hdr->name          = "DsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemStreamRcvyCnt;
    hdr->write         = writeDsMemStreamRcvyCnt;
    hdr->set           = setDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetDsMemStreamRcvyCnt;
    hdr->print         = printDsMemStreamRcvyCnt;
    hdr->reset         = resetDsMemStreamRcvyCnt;
    hdr->destroy       = destroyDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemStreamRcvySeq");
    hdr->name          = "DsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemStreamRcvySeq;
    hdr->write         = writeDsMemStreamRcvySeq;
    hdr->set           = setDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetDsMemStreamRcvySeq;
    hdr->print         = printDsMemStreamRcvySeq;
    hdr->reset         = resetDsMemStreamRcvySeq;
    hdr->destroy       = destroyDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegChnlAttr");
    hdr->name          = "DsRegChnlAttr";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000138;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegChnlAttr;
    hdr->write         = writeDsRegChnlAttr;
    hdr->set           = setDsRegChnlAttr;
    hdr->fldSet        = fldSetDsRegChnlAttr;
    hdr->fldGet        = fldGetDsRegChnlAttr;
    hdr->print         = printDsRegChnlAttr;
    hdr->reset         = resetDsRegChnlAttr;
    hdr->destroy       = destroyDsRegChnlAttr;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("MsgAdmInfo0");
    hdr->name          = "MsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readMsgAdmInfo0;
    hdr->write         = writeMsgAdmInfo0;
    hdr->set           = setMsgAdmInfo0;
    hdr->fldSet        = fldSetMsgAdmInfo0;
    hdr->fldGet        = fldGetMsgAdmInfo0;
    hdr->print         = printMsgAdmInfo0;
    hdr->reset         = resetMsgAdmInfo0;
    hdr->destroy       = destroyMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TmpDsMemMac");
    hdr->name          = "TmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000290;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTmpDsMemMac;
    hdr->write         = writeTmpDsMemMac;
    hdr->set           = setTmpDsMemMac;
    hdr->fldSet        = fldSetTmpDsMemMac;
    hdr->fldGet        = fldGetTmpDsMemMac;
    hdr->print         = printTmpDsMemMac;
    hdr->reset         = resetTmpDsMemMac;
    hdr->destroy       = destroyTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
