/*
 * Software Development Kit for Fisilink
 * @file: IngressPolice.c
 * @description: C language expression for IngressPolice module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/IngressPoliceOpr.h>


int insertIngressPoliceHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlCpuPolice");
    hdr->name          = "CtlCpuPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlCpuPolice;
    hdr->write         = writeCtlCpuPolice;
    hdr->set           = setCtlCpuPolice;
    hdr->fldSet        = fldSetCtlCpuPolice;
    hdr->fldGet        = fldGetCtlCpuPolice;
    hdr->print         = printCtlCpuPolice;
    hdr->reset         = resetCtlCpuPolice;
    hdr->destroy       = destroyCtlCpuPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlPolice");
    hdr->name          = "CtlPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlPolice;
    hdr->write         = writeCtlPolice;
    hdr->set           = setCtlPolice;
    hdr->fldSet        = fldSetCtlPolice;
    hdr->fldGet        = fldGetCtlPolice;
    hdr->print         = printCtlPolice;
    hdr->reset         = resetCtlPolice;
    hdr->destroy       = destroyCtlPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlPoliceLog");
    hdr->name          = "CtlPoliceLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlPoliceLog;
    hdr->write         = writeCtlPoliceLog;
    hdr->set           = setCtlPoliceLog;
    hdr->fldSet        = fldSetCtlPoliceLog;
    hdr->fldGet        = fldGetCtlPoliceLog;
    hdr->print         = printCtlPoliceLog;
    hdr->reset         = resetCtlPoliceLog;
    hdr->destroy       = destroyCtlPoliceLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemAclTsn");
    hdr->name          = "IngressPoliceDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemAclTsn;
    hdr->write         = writeIngressPoliceDsMemAclTsn;
    hdr->set           = setIngressPoliceDsMemAclTsn;
    hdr->fldSet        = fldSetIngressPoliceDsMemAclTsn;
    hdr->fldGet        = fldGetIngressPoliceDsMemAclTsn;
    hdr->print         = printIngressPoliceDsMemAclTsn;
    hdr->reset         = resetIngressPoliceDsMemAclTsn;
    hdr->destroy       = destroyIngressPoliceDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemColorStats");
    hdr->name          = "DsMemColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemColorStats;
    hdr->write         = writeDsMemColorStats;
    hdr->set           = setDsMemColorStats;
    hdr->fldSet        = fldSetDsMemColorStats;
    hdr->fldGet        = fldGetDsMemColorStats;
    hdr->print         = printDsMemColorStats;
    hdr->reset         = resetDsMemColorStats;
    hdr->destroy       = destroyDsMemColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCpuPolicePtrMap");
    hdr->name          = "DsMemCpuPolicePtrMap";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000028;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCpuPolicePtrMap;
    hdr->write         = writeDsMemCpuPolicePtrMap;
    hdr->set           = setDsMemCpuPolicePtrMap;
    hdr->fldSet        = fldSetDsMemCpuPolicePtrMap;
    hdr->fldGet        = fldGetDsMemCpuPolicePtrMap;
    hdr->print         = printDsMemCpuPolicePtrMap;
    hdr->reset         = resetDsMemCpuPolicePtrMap;
    hdr->destroy       = destroyDsMemCpuPolicePtrMap;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemFlowColorStats");
    hdr->name          = "IngressPoliceDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemFlowColorStats;
    hdr->write         = writeIngressPoliceDsMemFlowColorStats;
    hdr->set           = setIngressPoliceDsMemFlowColorStats;
    hdr->fldSet        = fldSetIngressPoliceDsMemFlowColorStats;
    hdr->fldGet        = fldGetIngressPoliceDsMemFlowColorStats;
    hdr->print         = printIngressPoliceDsMemFlowColorStats;
    hdr->reset         = resetIngressPoliceDsMemFlowColorStats;
    hdr->destroy       = destroyIngressPoliceDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemFlowPolice");
    hdr->name          = "IngressPoliceDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemFlowPolice;
    hdr->write         = writeIngressPoliceDsMemFlowPolice;
    hdr->set           = setIngressPoliceDsMemFlowPolice;
    hdr->fldSet        = fldSetIngressPoliceDsMemFlowPolice;
    hdr->fldGet        = fldGetIngressPoliceDsMemFlowPolice;
    hdr->print         = printIngressPoliceDsMemFlowPolice;
    hdr->reset         = resetIngressPoliceDsMemFlowPolice;
    hdr->destroy       = destroyIngressPoliceDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemFlowPoliceCfg");
    hdr->name          = "IngressPoliceDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemFlowPoliceCfg;
    hdr->write         = writeIngressPoliceDsMemFlowPoliceCfg;
    hdr->set           = setIngressPoliceDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetIngressPoliceDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetIngressPoliceDsMemFlowPoliceCfg;
    hdr->print         = printIngressPoliceDsMemFlowPoliceCfg;
    hdr->reset         = resetIngressPoliceDsMemFlowPoliceCfg;
    hdr->destroy       = destroyIngressPoliceDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostRoute");
    hdr->name          = "IngressPoliceDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostRoute;
    hdr->write         = writeIngressPoliceDsMemHostRoute;
    hdr->set           = setIngressPoliceDsMemHostRoute;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostRoute;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostRoute;
    hdr->print         = printIngressPoliceDsMemHostRoute;
    hdr->reset         = resetIngressPoliceDsMemHostRoute;
    hdr->destroy       = destroyIngressPoliceDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostRouteLeft");
    hdr->name          = "IngressPoliceDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostRouteLeft;
    hdr->write         = writeIngressPoliceDsMemHostRouteLeft;
    hdr->set           = setIngressPoliceDsMemHostRouteLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostRouteLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostRouteLeft;
    hdr->print         = printIngressPoliceDsMemHostRouteLeft;
    hdr->reset         = resetIngressPoliceDsMemHostRouteLeft;
    hdr->destroy       = destroyIngressPoliceDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostRouteLeftKey");
    hdr->name          = "IngressPoliceDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostRouteLeftKey;
    hdr->write         = writeIngressPoliceDsMemHostRouteLeftKey;
    hdr->set           = setIngressPoliceDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostRouteLeftKey;
    hdr->print         = printIngressPoliceDsMemHostRouteLeftKey;
    hdr->reset         = resetIngressPoliceDsMemHostRouteLeftKey;
    hdr->destroy       = destroyIngressPoliceDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostRouteLeftValid");
    hdr->name          = "IngressPoliceDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostRouteLeftValid;
    hdr->write         = writeIngressPoliceDsMemHostRouteLeftValid;
    hdr->set           = setIngressPoliceDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostRouteLeftValid;
    hdr->print         = printIngressPoliceDsMemHostRouteLeftValid;
    hdr->reset         = resetIngressPoliceDsMemHostRouteLeftValid;
    hdr->destroy       = destroyIngressPoliceDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostRouteRight");
    hdr->name          = "IngressPoliceDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostRouteRight;
    hdr->write         = writeIngressPoliceDsMemHostRouteRight;
    hdr->set           = setIngressPoliceDsMemHostRouteRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostRouteRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostRouteRight;
    hdr->print         = printIngressPoliceDsMemHostRouteRight;
    hdr->reset         = resetIngressPoliceDsMemHostRouteRight;
    hdr->destroy       = destroyIngressPoliceDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostRouteRightKey");
    hdr->name          = "IngressPoliceDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostRouteRightKey;
    hdr->write         = writeIngressPoliceDsMemHostRouteRightKey;
    hdr->set           = setIngressPoliceDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostRouteRightKey;
    hdr->print         = printIngressPoliceDsMemHostRouteRightKey;
    hdr->reset         = resetIngressPoliceDsMemHostRouteRightKey;
    hdr->destroy       = destroyIngressPoliceDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostRouteRightValid");
    hdr->name          = "IngressPoliceDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostRouteRightValid;
    hdr->write         = writeIngressPoliceDsMemHostRouteRightValid;
    hdr->set           = setIngressPoliceDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostRouteRightValid;
    hdr->print         = printIngressPoliceDsMemHostRouteRightValid;
    hdr->reset         = resetIngressPoliceDsMemHostRouteRightValid;
    hdr->destroy       = destroyIngressPoliceDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostTsn");
    hdr->name          = "IngressPoliceDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostTsn;
    hdr->write         = writeIngressPoliceDsMemHostTsn;
    hdr->set           = setIngressPoliceDsMemHostTsn;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostTsn;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostTsn;
    hdr->print         = printIngressPoliceDsMemHostTsn;
    hdr->reset         = resetIngressPoliceDsMemHostTsn;
    hdr->destroy       = destroyIngressPoliceDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostTsnLeft");
    hdr->name          = "IngressPoliceDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostTsnLeft;
    hdr->write         = writeIngressPoliceDsMemHostTsnLeft;
    hdr->set           = setIngressPoliceDsMemHostTsnLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostTsnLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostTsnLeft;
    hdr->print         = printIngressPoliceDsMemHostTsnLeft;
    hdr->reset         = resetIngressPoliceDsMemHostTsnLeft;
    hdr->destroy       = destroyIngressPoliceDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemHostTsnRight");
    hdr->name          = "IngressPoliceDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemHostTsnRight;
    hdr->write         = writeIngressPoliceDsMemHostTsnRight;
    hdr->set           = setIngressPoliceDsMemHostTsnRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemHostTsnRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemHostTsnRight;
    hdr->print         = printIngressPoliceDsMemHostTsnRight;
    hdr->reset         = resetIngressPoliceDsMemHostTsnRight;
    hdr->destroy       = destroyIngressPoliceDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemIndvRcvyCfg");
    hdr->name          = "IngressPoliceDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemIndvRcvyCfg;
    hdr->write         = writeIngressPoliceDsMemIndvRcvyCfg;
    hdr->set           = setIngressPoliceDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetIngressPoliceDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetIngressPoliceDsMemIndvRcvyCfg;
    hdr->print         = printIngressPoliceDsMemIndvRcvyCfg;
    hdr->reset         = resetIngressPoliceDsMemIndvRcvyCfg;
    hdr->destroy       = destroyIngressPoliceDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemIndvRcvyCnt");
    hdr->name          = "IngressPoliceDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemIndvRcvyCnt;
    hdr->write         = writeIngressPoliceDsMemIndvRcvyCnt;
    hdr->set           = setIngressPoliceDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetIngressPoliceDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetIngressPoliceDsMemIndvRcvyCnt;
    hdr->print         = printIngressPoliceDsMemIndvRcvyCnt;
    hdr->reset         = resetIngressPoliceDsMemIndvRcvyCnt;
    hdr->destroy       = destroyIngressPoliceDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemIndvRcvySeq");
    hdr->name          = "IngressPoliceDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemIndvRcvySeq;
    hdr->write         = writeIngressPoliceDsMemIndvRcvySeq;
    hdr->set           = setIngressPoliceDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetIngressPoliceDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetIngressPoliceDsMemIndvRcvySeq;
    hdr->print         = printIngressPoliceDsMemIndvRcvySeq;
    hdr->reset         = resetIngressPoliceDsMemIndvRcvySeq;
    hdr->destroy       = destroyIngressPoliceDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacAgingLeft");
    hdr->name          = "IngressPoliceDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacAgingLeft;
    hdr->write         = writeIngressPoliceDsMemMacAgingLeft;
    hdr->set           = setIngressPoliceDsMemMacAgingLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacAgingLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacAgingLeft;
    hdr->print         = printIngressPoliceDsMemMacAgingLeft;
    hdr->reset         = resetIngressPoliceDsMemMacAgingLeft;
    hdr->destroy       = destroyIngressPoliceDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacAgingRight");
    hdr->name          = "IngressPoliceDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacAgingRight;
    hdr->write         = writeIngressPoliceDsMemMacAgingRight;
    hdr->set           = setIngressPoliceDsMemMacAgingRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacAgingRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacAgingRight;
    hdr->print         = printIngressPoliceDsMemMacAgingRight;
    hdr->reset         = resetIngressPoliceDsMemMacAgingRight;
    hdr->destroy       = destroyIngressPoliceDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacKeyLeft");
    hdr->name          = "IngressPoliceDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacKeyLeft;
    hdr->write         = writeIngressPoliceDsMemMacKeyLeft;
    hdr->set           = setIngressPoliceDsMemMacKeyLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacKeyLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacKeyLeft;
    hdr->print         = printIngressPoliceDsMemMacKeyLeft;
    hdr->reset         = resetIngressPoliceDsMemMacKeyLeft;
    hdr->destroy       = destroyIngressPoliceDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacKeyRight");
    hdr->name          = "IngressPoliceDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacKeyRight;
    hdr->write         = writeIngressPoliceDsMemMacKeyRight;
    hdr->set           = setIngressPoliceDsMemMacKeyRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacKeyRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacKeyRight;
    hdr->print         = printIngressPoliceDsMemMacKeyRight;
    hdr->reset         = resetIngressPoliceDsMemMacKeyRight;
    hdr->destroy       = destroyIngressPoliceDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacLeft");
    hdr->name          = "IngressPoliceDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacLeft;
    hdr->write         = writeIngressPoliceDsMemMacLeft;
    hdr->set           = setIngressPoliceDsMemMacLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacLeft;
    hdr->print         = printIngressPoliceDsMemMacLeft;
    hdr->reset         = resetIngressPoliceDsMemMacLeft;
    hdr->destroy       = destroyIngressPoliceDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacRight");
    hdr->name          = "IngressPoliceDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacRight;
    hdr->write         = writeIngressPoliceDsMemMacRight;
    hdr->set           = setIngressPoliceDsMemMacRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacRight;
    hdr->print         = printIngressPoliceDsMemMacRight;
    hdr->reset         = resetIngressPoliceDsMemMacRight;
    hdr->destroy       = destroyIngressPoliceDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacStaticLeft");
    hdr->name          = "IngressPoliceDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacStaticLeft;
    hdr->write         = writeIngressPoliceDsMemMacStaticLeft;
    hdr->set           = setIngressPoliceDsMemMacStaticLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacStaticLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacStaticLeft;
    hdr->print         = printIngressPoliceDsMemMacStaticLeft;
    hdr->reset         = resetIngressPoliceDsMemMacStaticLeft;
    hdr->destroy       = destroyIngressPoliceDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacStaticRight");
    hdr->name          = "IngressPoliceDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacStaticRight;
    hdr->write         = writeIngressPoliceDsMemMacStaticRight;
    hdr->set           = setIngressPoliceDsMemMacStaticRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacStaticRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacStaticRight;
    hdr->print         = printIngressPoliceDsMemMacStaticRight;
    hdr->reset         = resetIngressPoliceDsMemMacStaticRight;
    hdr->destroy       = destroyIngressPoliceDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacTsn");
    hdr->name          = "IngressPoliceDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacTsn;
    hdr->write         = writeIngressPoliceDsMemMacTsn;
    hdr->set           = setIngressPoliceDsMemMacTsn;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacTsn;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacTsn;
    hdr->print         = printIngressPoliceDsMemMacTsn;
    hdr->reset         = resetIngressPoliceDsMemMacTsn;
    hdr->destroy       = destroyIngressPoliceDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacTsnLeft");
    hdr->name          = "IngressPoliceDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacTsnLeft;
    hdr->write         = writeIngressPoliceDsMemMacTsnLeft;
    hdr->set           = setIngressPoliceDsMemMacTsnLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacTsnLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacTsnLeft;
    hdr->print         = printIngressPoliceDsMemMacTsnLeft;
    hdr->reset         = resetIngressPoliceDsMemMacTsnLeft;
    hdr->destroy       = destroyIngressPoliceDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacTsnRight");
    hdr->name          = "IngressPoliceDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacTsnRight;
    hdr->write         = writeIngressPoliceDsMemMacTsnRight;
    hdr->set           = setIngressPoliceDsMemMacTsnRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacTsnRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacTsnRight;
    hdr->print         = printIngressPoliceDsMemMacTsnRight;
    hdr->reset         = resetIngressPoliceDsMemMacTsnRight;
    hdr->destroy       = destroyIngressPoliceDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacValidLeft");
    hdr->name          = "IngressPoliceDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacValidLeft;
    hdr->write         = writeIngressPoliceDsMemMacValidLeft;
    hdr->set           = setIngressPoliceDsMemMacValidLeft;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacValidLeft;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacValidLeft;
    hdr->print         = printIngressPoliceDsMemMacValidLeft;
    hdr->reset         = resetIngressPoliceDsMemMacValidLeft;
    hdr->destroy       = destroyIngressPoliceDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemMacValidRight");
    hdr->name          = "IngressPoliceDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemMacValidRight;
    hdr->write         = writeIngressPoliceDsMemMacValidRight;
    hdr->set           = setIngressPoliceDsMemMacValidRight;
    hdr->fldSet        = fldSetIngressPoliceDsMemMacValidRight;
    hdr->fldGet        = fldGetIngressPoliceDsMemMacValidRight;
    hdr->print         = printIngressPoliceDsMemMacValidRight;
    hdr->reset         = resetIngressPoliceDsMemMacValidRight;
    hdr->destroy       = destroyIngressPoliceDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemPolice");
    hdr->name          = "DsMemPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000118;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemPolice;
    hdr->write         = writeDsMemPolice;
    hdr->set           = setDsMemPolice;
    hdr->fldSet        = fldSetDsMemPolice;
    hdr->fldGet        = fldGetDsMemPolice;
    hdr->print         = printDsMemPolice;
    hdr->reset         = resetDsMemPolice;
    hdr->destroy       = destroyDsMemPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemPoliceCfg");
    hdr->name          = "DsMemPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemPoliceCfg;
    hdr->write         = writeDsMemPoliceCfg;
    hdr->set           = setDsMemPoliceCfg;
    hdr->fldSet        = fldSetDsMemPoliceCfg;
    hdr->fldGet        = fldGetDsMemPoliceCfg;
    hdr->print         = printDsMemPoliceCfg;
    hdr->reset         = resetDsMemPoliceCfg;
    hdr->destroy       = destroyDsMemPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemPortColorStats");
    hdr->name          = "IngressPoliceDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemPortColorStats;
    hdr->write         = writeIngressPoliceDsMemPortColorStats;
    hdr->set           = setIngressPoliceDsMemPortColorStats;
    hdr->fldSet        = fldSetIngressPoliceDsMemPortColorStats;
    hdr->fldGet        = fldGetIngressPoliceDsMemPortColorStats;
    hdr->print         = printIngressPoliceDsMemPortColorStats;
    hdr->reset         = resetIngressPoliceDsMemPortColorStats;
    hdr->destroy       = destroyIngressPoliceDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemPortPolice");
    hdr->name          = "IngressPoliceDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemPortPolice;
    hdr->write         = writeIngressPoliceDsMemPortPolice;
    hdr->set           = setIngressPoliceDsMemPortPolice;
    hdr->fldSet        = fldSetIngressPoliceDsMemPortPolice;
    hdr->fldGet        = fldGetIngressPoliceDsMemPortPolice;
    hdr->print         = printIngressPoliceDsMemPortPolice;
    hdr->reset         = resetIngressPoliceDsMemPortPolice;
    hdr->destroy       = destroyIngressPoliceDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemPortPoliceCfg");
    hdr->name          = "IngressPoliceDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000138;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemPortPoliceCfg;
    hdr->write         = writeIngressPoliceDsMemPortPoliceCfg;
    hdr->set           = setIngressPoliceDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetIngressPoliceDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetIngressPoliceDsMemPortPoliceCfg;
    hdr->print         = printIngressPoliceDsMemPortPoliceCfg;
    hdr->reset         = resetIngressPoliceDsMemPortPoliceCfg;
    hdr->destroy       = destroyIngressPoliceDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemRouteTsn");
    hdr->name          = "IngressPoliceDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemRouteTsn;
    hdr->write         = writeIngressPoliceDsMemRouteTsn;
    hdr->set           = setIngressPoliceDsMemRouteTsn;
    hdr->fldSet        = fldSetIngressPoliceDsMemRouteTsn;
    hdr->fldGet        = fldGetIngressPoliceDsMemRouteTsn;
    hdr->print         = printIngressPoliceDsMemRouteTsn;
    hdr->reset         = resetIngressPoliceDsMemRouteTsn;
    hdr->destroy       = destroyIngressPoliceDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemStreamRcvyCfg");
    hdr->name          = "IngressPoliceDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000290;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemStreamRcvyCfg;
    hdr->write         = writeIngressPoliceDsMemStreamRcvyCfg;
    hdr->set           = setIngressPoliceDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetIngressPoliceDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetIngressPoliceDsMemStreamRcvyCfg;
    hdr->print         = printIngressPoliceDsMemStreamRcvyCfg;
    hdr->reset         = resetIngressPoliceDsMemStreamRcvyCfg;
    hdr->destroy       = destroyIngressPoliceDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemStreamRcvyCnt");
    hdr->name          = "IngressPoliceDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemStreamRcvyCnt;
    hdr->write         = writeIngressPoliceDsMemStreamRcvyCnt;
    hdr->set           = setIngressPoliceDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetIngressPoliceDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetIngressPoliceDsMemStreamRcvyCnt;
    hdr->print         = printIngressPoliceDsMemStreamRcvyCnt;
    hdr->reset         = resetIngressPoliceDsMemStreamRcvyCnt;
    hdr->destroy       = destroyIngressPoliceDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceDsMemStreamRcvySeq");
    hdr->name          = "IngressPoliceDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceDsMemStreamRcvySeq;
    hdr->write         = writeIngressPoliceDsMemStreamRcvySeq;
    hdr->set           = setIngressPoliceDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetIngressPoliceDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetIngressPoliceDsMemStreamRcvySeq;
    hdr->print         = printIngressPoliceDsMemStreamRcvySeq;
    hdr->reset         = resetIngressPoliceDsMemStreamRcvySeq;
    hdr->destroy       = destroyIngressPoliceDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemTsnPolice");
    hdr->name          = "DsMemTsnPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemTsnPolice;
    hdr->write         = writeDsMemTsnPolice;
    hdr->set           = setDsMemTsnPolice;
    hdr->fldSet        = fldSetDsMemTsnPolice;
    hdr->fldGet        = fldGetDsMemTsnPolice;
    hdr->print         = printDsMemTsnPolice;
    hdr->reset         = resetDsMemTsnPolice;
    hdr->destroy       = destroyDsMemTsnPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceMsgAdmInfo0");
    hdr->name          = "IngressPoliceMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceMsgAdmInfo0;
    hdr->write         = writeIngressPoliceMsgAdmInfo0;
    hdr->set           = setIngressPoliceMsgAdmInfo0;
    hdr->fldSet        = fldSetIngressPoliceMsgAdmInfo0;
    hdr->fldGet        = fldGetIngressPoliceMsgAdmInfo0;
    hdr->print         = printIngressPoliceMsgAdmInfo0;
    hdr->reset         = resetIngressPoliceMsgAdmInfo0;
    hdr->destroy       = destroyIngressPoliceMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("IngressPoliceTmpDsMemMac");
    hdr->name          = "IngressPoliceTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readIngressPoliceTmpDsMemMac;
    hdr->write         = writeIngressPoliceTmpDsMemMac;
    hdr->set           = setIngressPoliceTmpDsMemMac;
    hdr->fldSet        = fldSetIngressPoliceTmpDsMemMac;
    hdr->fldGet        = fldGetIngressPoliceTmpDsMemMac;
    hdr->print         = printIngressPoliceTmpDsMemMac;
    hdr->reset         = resetIngressPoliceTmpDsMemMac;
    hdr->destroy       = destroyIngressPoliceTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
