/*
 * Software Development Kit for Fisilink
 * @file: Interface.c
 * @description: C language expression for Interface module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/InterfaceOpr.h>


int insertInterfaceHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceCtlCommon");
    hdr->name          = "InterfaceCtlCommon";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceCtlCommon;
    hdr->write         = writeInterfaceCtlCommon;
    hdr->set           = setInterfaceCtlCommon;
    hdr->fldSet        = fldSetInterfaceCtlCommon;
    hdr->fldGet        = fldGetInterfaceCtlCommon;
    hdr->print         = printInterfaceCtlCommon;
    hdr->reset         = resetInterfaceCtlCommon;
    hdr->destroy       = destroyInterfaceCtlCommon;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlCosMapPrior");
    hdr->name          = "CtlCosMapPrior";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlCosMapPrior;
    hdr->write         = writeCtlCosMapPrior;
    hdr->set           = setCtlCosMapPrior;
    hdr->fldSet        = fldSetCtlCosMapPrior;
    hdr->fldGet        = fldGetCtlCosMapPrior;
    hdr->print         = printCtlCosMapPrior;
    hdr->reset         = resetCtlCosMapPrior;
    hdr->destroy       = destroyCtlCosMapPrior;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlDscpMapPrior");
    hdr->name          = "CtlDscpMapPrior";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlDscpMapPrior;
    hdr->write         = writeCtlDscpMapPrior;
    hdr->set           = setCtlDscpMapPrior;
    hdr->fldSet        = fldSetCtlDscpMapPrior;
    hdr->fldGet        = fldGetCtlDscpMapPrior;
    hdr->print         = printCtlDscpMapPrior;
    hdr->reset         = resetCtlDscpMapPrior;
    hdr->destroy       = destroyCtlDscpMapPrior;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlIntfBpduMac");
    hdr->name          = "CtlIntfBpduMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000018;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlIntfBpduMac;
    hdr->write         = writeCtlIntfBpduMac;
    hdr->set           = setCtlIntfBpduMac;
    hdr->fldSet        = fldSetCtlIntfBpduMac;
    hdr->fldGet        = fldGetCtlIntfBpduMac;
    hdr->print         = printCtlIntfBpduMac;
    hdr->reset         = resetCtlIntfBpduMac;
    hdr->destroy       = destroyCtlIntfBpduMac;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlIntfMapLog");
    hdr->name          = "CtlIntfMapLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlIntfMapLog;
    hdr->write         = writeCtlIntfMapLog;
    hdr->set           = setCtlIntfMapLog;
    hdr->fldSet        = fldSetCtlIntfMapLog;
    hdr->fldGet        = fldGetCtlIntfMapLog;
    hdr->print         = printCtlIntfMapLog;
    hdr->reset         = resetCtlIntfMapLog;
    hdr->destroy       = destroyCtlIntfMapLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlIpPrecdncMapPrior");
    hdr->name          = "CtlIpPrecdncMapPrior";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000028;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlIpPrecdncMapPrior;
    hdr->write         = writeCtlIpPrecdncMapPrior;
    hdr->set           = setCtlIpPrecdncMapPrior;
    hdr->fldSet        = fldSetCtlIpPrecdncMapPrior;
    hdr->fldGet        = fldGetCtlIpPrecdncMapPrior;
    hdr->print         = printCtlIpPrecdncMapPrior;
    hdr->reset         = resetCtlIpPrecdncMapPrior;
    hdr->destroy       = destroyCtlIpPrecdncMapPrior;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlManageVlan");
    hdr->name          = "CtlManageVlan";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlManageVlan;
    hdr->write         = writeCtlManageVlan;
    hdr->set           = setCtlManageVlan;
    hdr->fldSet        = fldSetCtlManageVlan;
    hdr->fldGet        = fldGetCtlManageVlan;
    hdr->print         = printCtlManageVlan;
    hdr->reset         = resetCtlManageVlan;
    hdr->destroy       = destroyCtlManageVlan;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlRouterMac");
    hdr->name          = "CtlRouterMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000038;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlRouterMac;
    hdr->write         = writeCtlRouterMac;
    hdr->set           = setCtlRouterMac;
    hdr->fldSet        = fldSetCtlRouterMac;
    hdr->fldGet        = fldGetCtlRouterMac;
    hdr->print         = printCtlRouterMac;
    hdr->reset         = resetCtlRouterMac;
    hdr->destroy       = destroyCtlRouterMac;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlTsnFunc");
    hdr->name          = "CtlTsnFunc";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlTsnFunc;
    hdr->write         = writeCtlTsnFunc;
    hdr->set           = setCtlTsnFunc;
    hdr->fldSet        = fldSetCtlTsnFunc;
    hdr->fldGet        = fldGetCtlTsnFunc;
    hdr->print         = printCtlTsnFunc;
    hdr->reset         = resetCtlTsnFunc;
    hdr->destroy       = destroyCtlTsnFunc;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemAclTsn");
    hdr->name          = "InterfaceDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemAclTsn;
    hdr->write         = writeInterfaceDsMemAclTsn;
    hdr->set           = setInterfaceDsMemAclTsn;
    hdr->fldSet        = fldSetInterfaceDsMemAclTsn;
    hdr->fldGet        = fldGetInterfaceDsMemAclTsn;
    hdr->print         = printInterfaceDsMemAclTsn;
    hdr->reset         = resetInterfaceDsMemAclTsn;
    hdr->destroy       = destroyInterfaceDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemFlowColorStats");
    hdr->name          = "InterfaceDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemFlowColorStats;
    hdr->write         = writeInterfaceDsMemFlowColorStats;
    hdr->set           = setInterfaceDsMemFlowColorStats;
    hdr->fldSet        = fldSetInterfaceDsMemFlowColorStats;
    hdr->fldGet        = fldGetInterfaceDsMemFlowColorStats;
    hdr->print         = printInterfaceDsMemFlowColorStats;
    hdr->reset         = resetInterfaceDsMemFlowColorStats;
    hdr->destroy       = destroyInterfaceDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemFlowPolice");
    hdr->name          = "InterfaceDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemFlowPolice;
    hdr->write         = writeInterfaceDsMemFlowPolice;
    hdr->set           = setInterfaceDsMemFlowPolice;
    hdr->fldSet        = fldSetInterfaceDsMemFlowPolice;
    hdr->fldGet        = fldGetInterfaceDsMemFlowPolice;
    hdr->print         = printInterfaceDsMemFlowPolice;
    hdr->reset         = resetInterfaceDsMemFlowPolice;
    hdr->destroy       = destroyInterfaceDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemFlowPoliceCfg");
    hdr->name          = "InterfaceDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemFlowPoliceCfg;
    hdr->write         = writeInterfaceDsMemFlowPoliceCfg;
    hdr->set           = setInterfaceDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetInterfaceDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetInterfaceDsMemFlowPoliceCfg;
    hdr->print         = printInterfaceDsMemFlowPoliceCfg;
    hdr->reset         = resetInterfaceDsMemFlowPoliceCfg;
    hdr->destroy       = destroyInterfaceDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostRoute");
    hdr->name          = "InterfaceDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostRoute;
    hdr->write         = writeInterfaceDsMemHostRoute;
    hdr->set           = setInterfaceDsMemHostRoute;
    hdr->fldSet        = fldSetInterfaceDsMemHostRoute;
    hdr->fldGet        = fldGetInterfaceDsMemHostRoute;
    hdr->print         = printInterfaceDsMemHostRoute;
    hdr->reset         = resetInterfaceDsMemHostRoute;
    hdr->destroy       = destroyInterfaceDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostRouteLeft");
    hdr->name          = "InterfaceDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostRouteLeft;
    hdr->write         = writeInterfaceDsMemHostRouteLeft;
    hdr->set           = setInterfaceDsMemHostRouteLeft;
    hdr->fldSet        = fldSetInterfaceDsMemHostRouteLeft;
    hdr->fldGet        = fldGetInterfaceDsMemHostRouteLeft;
    hdr->print         = printInterfaceDsMemHostRouteLeft;
    hdr->reset         = resetInterfaceDsMemHostRouteLeft;
    hdr->destroy       = destroyInterfaceDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostRouteLeftKey");
    hdr->name          = "InterfaceDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostRouteLeftKey;
    hdr->write         = writeInterfaceDsMemHostRouteLeftKey;
    hdr->set           = setInterfaceDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetInterfaceDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetInterfaceDsMemHostRouteLeftKey;
    hdr->print         = printInterfaceDsMemHostRouteLeftKey;
    hdr->reset         = resetInterfaceDsMemHostRouteLeftKey;
    hdr->destroy       = destroyInterfaceDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostRouteLeftValid");
    hdr->name          = "InterfaceDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostRouteLeftValid;
    hdr->write         = writeInterfaceDsMemHostRouteLeftValid;
    hdr->set           = setInterfaceDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetInterfaceDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetInterfaceDsMemHostRouteLeftValid;
    hdr->print         = printInterfaceDsMemHostRouteLeftValid;
    hdr->reset         = resetInterfaceDsMemHostRouteLeftValid;
    hdr->destroy       = destroyInterfaceDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostRouteRight");
    hdr->name          = "InterfaceDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostRouteRight;
    hdr->write         = writeInterfaceDsMemHostRouteRight;
    hdr->set           = setInterfaceDsMemHostRouteRight;
    hdr->fldSet        = fldSetInterfaceDsMemHostRouteRight;
    hdr->fldGet        = fldGetInterfaceDsMemHostRouteRight;
    hdr->print         = printInterfaceDsMemHostRouteRight;
    hdr->reset         = resetInterfaceDsMemHostRouteRight;
    hdr->destroy       = destroyInterfaceDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostRouteRightKey");
    hdr->name          = "InterfaceDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostRouteRightKey;
    hdr->write         = writeInterfaceDsMemHostRouteRightKey;
    hdr->set           = setInterfaceDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetInterfaceDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetInterfaceDsMemHostRouteRightKey;
    hdr->print         = printInterfaceDsMemHostRouteRightKey;
    hdr->reset         = resetInterfaceDsMemHostRouteRightKey;
    hdr->destroy       = destroyInterfaceDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostRouteRightValid");
    hdr->name          = "InterfaceDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostRouteRightValid;
    hdr->write         = writeInterfaceDsMemHostRouteRightValid;
    hdr->set           = setInterfaceDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetInterfaceDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetInterfaceDsMemHostRouteRightValid;
    hdr->print         = printInterfaceDsMemHostRouteRightValid;
    hdr->reset         = resetInterfaceDsMemHostRouteRightValid;
    hdr->destroy       = destroyInterfaceDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostTsn");
    hdr->name          = "InterfaceDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostTsn;
    hdr->write         = writeInterfaceDsMemHostTsn;
    hdr->set           = setInterfaceDsMemHostTsn;
    hdr->fldSet        = fldSetInterfaceDsMemHostTsn;
    hdr->fldGet        = fldGetInterfaceDsMemHostTsn;
    hdr->print         = printInterfaceDsMemHostTsn;
    hdr->reset         = resetInterfaceDsMemHostTsn;
    hdr->destroy       = destroyInterfaceDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostTsnLeft");
    hdr->name          = "InterfaceDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostTsnLeft;
    hdr->write         = writeInterfaceDsMemHostTsnLeft;
    hdr->set           = setInterfaceDsMemHostTsnLeft;
    hdr->fldSet        = fldSetInterfaceDsMemHostTsnLeft;
    hdr->fldGet        = fldGetInterfaceDsMemHostTsnLeft;
    hdr->print         = printInterfaceDsMemHostTsnLeft;
    hdr->reset         = resetInterfaceDsMemHostTsnLeft;
    hdr->destroy       = destroyInterfaceDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemHostTsnRight");
    hdr->name          = "InterfaceDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemHostTsnRight;
    hdr->write         = writeInterfaceDsMemHostTsnRight;
    hdr->set           = setInterfaceDsMemHostTsnRight;
    hdr->fldSet        = fldSetInterfaceDsMemHostTsnRight;
    hdr->fldGet        = fldGetInterfaceDsMemHostTsnRight;
    hdr->print         = printInterfaceDsMemHostTsnRight;
    hdr->reset         = resetInterfaceDsMemHostTsnRight;
    hdr->destroy       = destroyInterfaceDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemIndvRcvyCfg");
    hdr->name          = "InterfaceDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemIndvRcvyCfg;
    hdr->write         = writeInterfaceDsMemIndvRcvyCfg;
    hdr->set           = setInterfaceDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetInterfaceDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetInterfaceDsMemIndvRcvyCfg;
    hdr->print         = printInterfaceDsMemIndvRcvyCfg;
    hdr->reset         = resetInterfaceDsMemIndvRcvyCfg;
    hdr->destroy       = destroyInterfaceDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemIndvRcvyCnt");
    hdr->name          = "InterfaceDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemIndvRcvyCnt;
    hdr->write         = writeInterfaceDsMemIndvRcvyCnt;
    hdr->set           = setInterfaceDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetInterfaceDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetInterfaceDsMemIndvRcvyCnt;
    hdr->print         = printInterfaceDsMemIndvRcvyCnt;
    hdr->reset         = resetInterfaceDsMemIndvRcvyCnt;
    hdr->destroy       = destroyInterfaceDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemIndvRcvySeq");
    hdr->name          = "InterfaceDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemIndvRcvySeq;
    hdr->write         = writeInterfaceDsMemIndvRcvySeq;
    hdr->set           = setInterfaceDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetInterfaceDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetInterfaceDsMemIndvRcvySeq;
    hdr->print         = printInterfaceDsMemIndvRcvySeq;
    hdr->reset         = resetInterfaceDsMemIndvRcvySeq;
    hdr->destroy       = destroyInterfaceDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacAgingLeft");
    hdr->name          = "InterfaceDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacAgingLeft;
    hdr->write         = writeInterfaceDsMemMacAgingLeft;
    hdr->set           = setInterfaceDsMemMacAgingLeft;
    hdr->fldSet        = fldSetInterfaceDsMemMacAgingLeft;
    hdr->fldGet        = fldGetInterfaceDsMemMacAgingLeft;
    hdr->print         = printInterfaceDsMemMacAgingLeft;
    hdr->reset         = resetInterfaceDsMemMacAgingLeft;
    hdr->destroy       = destroyInterfaceDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacAgingRight");
    hdr->name          = "InterfaceDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacAgingRight;
    hdr->write         = writeInterfaceDsMemMacAgingRight;
    hdr->set           = setInterfaceDsMemMacAgingRight;
    hdr->fldSet        = fldSetInterfaceDsMemMacAgingRight;
    hdr->fldGet        = fldGetInterfaceDsMemMacAgingRight;
    hdr->print         = printInterfaceDsMemMacAgingRight;
    hdr->reset         = resetInterfaceDsMemMacAgingRight;
    hdr->destroy       = destroyInterfaceDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacBasedVlan");
    hdr->name          = "DsMemMacBasedVlan";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacBasedVlan;
    hdr->write         = writeDsMemMacBasedVlan;
    hdr->set           = setDsMemMacBasedVlan;
    hdr->fldSet        = fldSetDsMemMacBasedVlan;
    hdr->fldGet        = fldGetDsMemMacBasedVlan;
    hdr->print         = printDsMemMacBasedVlan;
    hdr->reset         = resetDsMemMacBasedVlan;
    hdr->destroy       = destroyDsMemMacBasedVlan;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacKeyLeft");
    hdr->name          = "InterfaceDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacKeyLeft;
    hdr->write         = writeInterfaceDsMemMacKeyLeft;
    hdr->set           = setInterfaceDsMemMacKeyLeft;
    hdr->fldSet        = fldSetInterfaceDsMemMacKeyLeft;
    hdr->fldGet        = fldGetInterfaceDsMemMacKeyLeft;
    hdr->print         = printInterfaceDsMemMacKeyLeft;
    hdr->reset         = resetInterfaceDsMemMacKeyLeft;
    hdr->destroy       = destroyInterfaceDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacKeyRight");
    hdr->name          = "InterfaceDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacKeyRight;
    hdr->write         = writeInterfaceDsMemMacKeyRight;
    hdr->set           = setInterfaceDsMemMacKeyRight;
    hdr->fldSet        = fldSetInterfaceDsMemMacKeyRight;
    hdr->fldGet        = fldGetInterfaceDsMemMacKeyRight;
    hdr->print         = printInterfaceDsMemMacKeyRight;
    hdr->reset         = resetInterfaceDsMemMacKeyRight;
    hdr->destroy       = destroyInterfaceDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacLeft");
    hdr->name          = "InterfaceDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacLeft;
    hdr->write         = writeInterfaceDsMemMacLeft;
    hdr->set           = setInterfaceDsMemMacLeft;
    hdr->fldSet        = fldSetInterfaceDsMemMacLeft;
    hdr->fldGet        = fldGetInterfaceDsMemMacLeft;
    hdr->print         = printInterfaceDsMemMacLeft;
    hdr->reset         = resetInterfaceDsMemMacLeft;
    hdr->destroy       = destroyInterfaceDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacRight");
    hdr->name          = "InterfaceDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacRight;
    hdr->write         = writeInterfaceDsMemMacRight;
    hdr->set           = setInterfaceDsMemMacRight;
    hdr->fldSet        = fldSetInterfaceDsMemMacRight;
    hdr->fldGet        = fldGetInterfaceDsMemMacRight;
    hdr->print         = printInterfaceDsMemMacRight;
    hdr->reset         = resetInterfaceDsMemMacRight;
    hdr->destroy       = destroyInterfaceDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacStaticLeft");
    hdr->name          = "InterfaceDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacStaticLeft;
    hdr->write         = writeInterfaceDsMemMacStaticLeft;
    hdr->set           = setInterfaceDsMemMacStaticLeft;
    hdr->fldSet        = fldSetInterfaceDsMemMacStaticLeft;
    hdr->fldGet        = fldGetInterfaceDsMemMacStaticLeft;
    hdr->print         = printInterfaceDsMemMacStaticLeft;
    hdr->reset         = resetInterfaceDsMemMacStaticLeft;
    hdr->destroy       = destroyInterfaceDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacStaticRight");
    hdr->name          = "InterfaceDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacStaticRight;
    hdr->write         = writeInterfaceDsMemMacStaticRight;
    hdr->set           = setInterfaceDsMemMacStaticRight;
    hdr->fldSet        = fldSetInterfaceDsMemMacStaticRight;
    hdr->fldGet        = fldGetInterfaceDsMemMacStaticRight;
    hdr->print         = printInterfaceDsMemMacStaticRight;
    hdr->reset         = resetInterfaceDsMemMacStaticRight;
    hdr->destroy       = destroyInterfaceDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacTsn");
    hdr->name          = "InterfaceDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacTsn;
    hdr->write         = writeInterfaceDsMemMacTsn;
    hdr->set           = setInterfaceDsMemMacTsn;
    hdr->fldSet        = fldSetInterfaceDsMemMacTsn;
    hdr->fldGet        = fldGetInterfaceDsMemMacTsn;
    hdr->print         = printInterfaceDsMemMacTsn;
    hdr->reset         = resetInterfaceDsMemMacTsn;
    hdr->destroy       = destroyInterfaceDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacTsnLeft");
    hdr->name          = "InterfaceDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacTsnLeft;
    hdr->write         = writeInterfaceDsMemMacTsnLeft;
    hdr->set           = setInterfaceDsMemMacTsnLeft;
    hdr->fldSet        = fldSetInterfaceDsMemMacTsnLeft;
    hdr->fldGet        = fldGetInterfaceDsMemMacTsnLeft;
    hdr->print         = printInterfaceDsMemMacTsnLeft;
    hdr->reset         = resetInterfaceDsMemMacTsnLeft;
    hdr->destroy       = destroyInterfaceDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacTsnRight");
    hdr->name          = "InterfaceDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacTsnRight;
    hdr->write         = writeInterfaceDsMemMacTsnRight;
    hdr->set           = setInterfaceDsMemMacTsnRight;
    hdr->fldSet        = fldSetInterfaceDsMemMacTsnRight;
    hdr->fldGet        = fldGetInterfaceDsMemMacTsnRight;
    hdr->print         = printInterfaceDsMemMacTsnRight;
    hdr->reset         = resetInterfaceDsMemMacTsnRight;
    hdr->destroy       = destroyInterfaceDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacValidLeft");
    hdr->name          = "InterfaceDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacValidLeft;
    hdr->write         = writeInterfaceDsMemMacValidLeft;
    hdr->set           = setInterfaceDsMemMacValidLeft;
    hdr->fldSet        = fldSetInterfaceDsMemMacValidLeft;
    hdr->fldGet        = fldGetInterfaceDsMemMacValidLeft;
    hdr->print         = printInterfaceDsMemMacValidLeft;
    hdr->reset         = resetInterfaceDsMemMacValidLeft;
    hdr->destroy       = destroyInterfaceDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemMacValidRight");
    hdr->name          = "InterfaceDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemMacValidRight;
    hdr->write         = writeInterfaceDsMemMacValidRight;
    hdr->set           = setInterfaceDsMemMacValidRight;
    hdr->fldSet        = fldSetInterfaceDsMemMacValidRight;
    hdr->fldGet        = fldGetInterfaceDsMemMacValidRight;
    hdr->print         = printInterfaceDsMemMacValidRight;
    hdr->reset         = resetInterfaceDsMemMacValidRight;
    hdr->destroy       = destroyInterfaceDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemPortColorStats");
    hdr->name          = "InterfaceDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemPortColorStats;
    hdr->write         = writeInterfaceDsMemPortColorStats;
    hdr->set           = setInterfaceDsMemPortColorStats;
    hdr->fldSet        = fldSetInterfaceDsMemPortColorStats;
    hdr->fldGet        = fldGetInterfaceDsMemPortColorStats;
    hdr->print         = printInterfaceDsMemPortColorStats;
    hdr->reset         = resetInterfaceDsMemPortColorStats;
    hdr->destroy       = destroyInterfaceDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemPortPolice");
    hdr->name          = "InterfaceDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000290;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemPortPolice;
    hdr->write         = writeInterfaceDsMemPortPolice;
    hdr->set           = setInterfaceDsMemPortPolice;
    hdr->fldSet        = fldSetInterfaceDsMemPortPolice;
    hdr->fldGet        = fldGetInterfaceDsMemPortPolice;
    hdr->print         = printInterfaceDsMemPortPolice;
    hdr->reset         = resetInterfaceDsMemPortPolice;
    hdr->destroy       = destroyInterfaceDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemPortPoliceCfg");
    hdr->name          = "InterfaceDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemPortPoliceCfg;
    hdr->write         = writeInterfaceDsMemPortPoliceCfg;
    hdr->set           = setInterfaceDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetInterfaceDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetInterfaceDsMemPortPoliceCfg;
    hdr->print         = printInterfaceDsMemPortPoliceCfg;
    hdr->reset         = resetInterfaceDsMemPortPoliceCfg;
    hdr->destroy       = destroyInterfaceDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemProtocolVlan");
    hdr->name          = "DsMemProtocolVlan";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000158;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemProtocolVlan;
    hdr->write         = writeDsMemProtocolVlan;
    hdr->set           = setDsMemProtocolVlan;
    hdr->fldSet        = fldSetDsMemProtocolVlan;
    hdr->fldGet        = fldGetDsMemProtocolVlan;
    hdr->print         = printDsMemProtocolVlan;
    hdr->reset         = resetDsMemProtocolVlan;
    hdr->destroy       = destroyDsMemProtocolVlan;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemRouteTsn");
    hdr->name          = "InterfaceDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemRouteTsn;
    hdr->write         = writeInterfaceDsMemRouteTsn;
    hdr->set           = setInterfaceDsMemRouteTsn;
    hdr->fldSet        = fldSetInterfaceDsMemRouteTsn;
    hdr->fldGet        = fldGetInterfaceDsMemRouteTsn;
    hdr->print         = printInterfaceDsMemRouteTsn;
    hdr->reset         = resetInterfaceDsMemRouteTsn;
    hdr->destroy       = destroyInterfaceDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemSrcPort");
    hdr->name          = "DsMemSrcPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000168;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemSrcPort;
    hdr->write         = writeDsMemSrcPort;
    hdr->set           = setDsMemSrcPort;
    hdr->fldSet        = fldSetDsMemSrcPort;
    hdr->fldGet        = fldGetDsMemSrcPort;
    hdr->print         = printDsMemSrcPort;
    hdr->reset         = resetDsMemSrcPort;
    hdr->destroy       = destroyDsMemSrcPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemStpState");
    hdr->name          = "DsMemStpState";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemStpState;
    hdr->write         = writeDsMemStpState;
    hdr->set           = setDsMemStpState;
    hdr->fldSet        = fldSetDsMemStpState;
    hdr->fldGet        = fldGetDsMemStpState;
    hdr->print         = printDsMemStpState;
    hdr->reset         = resetDsMemStpState;
    hdr->destroy       = destroyDsMemStpState;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemStreamRcvyCfg");
    hdr->name          = "InterfaceDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemStreamRcvyCfg;
    hdr->write         = writeInterfaceDsMemStreamRcvyCfg;
    hdr->set           = setInterfaceDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetInterfaceDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetInterfaceDsMemStreamRcvyCfg;
    hdr->print         = printInterfaceDsMemStreamRcvyCfg;
    hdr->reset         = resetInterfaceDsMemStreamRcvyCfg;
    hdr->destroy       = destroyInterfaceDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemStreamRcvyCnt");
    hdr->name          = "InterfaceDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000300;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemStreamRcvyCnt;
    hdr->write         = writeInterfaceDsMemStreamRcvyCnt;
    hdr->set           = setInterfaceDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetInterfaceDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetInterfaceDsMemStreamRcvyCnt;
    hdr->print         = printInterfaceDsMemStreamRcvyCnt;
    hdr->reset         = resetInterfaceDsMemStreamRcvyCnt;
    hdr->destroy       = destroyInterfaceDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceDsMemStreamRcvySeq");
    hdr->name          = "InterfaceDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000310;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceDsMemStreamRcvySeq;
    hdr->write         = writeInterfaceDsMemStreamRcvySeq;
    hdr->set           = setInterfaceDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetInterfaceDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetInterfaceDsMemStreamRcvySeq;
    hdr->print         = printInterfaceDsMemStreamRcvySeq;
    hdr->reset         = resetInterfaceDsMemStreamRcvySeq;
    hdr->destroy       = destroyInterfaceDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemTsnDomain");
    hdr->name          = "DsMemTsnDomain";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemTsnDomain;
    hdr->write         = writeDsMemTsnDomain;
    hdr->set           = setDsMemTsnDomain;
    hdr->fldSet        = fldSetDsMemTsnDomain;
    hdr->fldGet        = fldGetDsMemTsnDomain;
    hdr->print         = printDsMemTsnDomain;
    hdr->reset         = resetDsMemTsnDomain;
    hdr->destroy       = destroyDsMemTsnDomain;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemVlan");
    hdr->name          = "DsMemVlan";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000198;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemVlan;
    hdr->write         = writeDsMemVlan;
    hdr->set           = setDsMemVlan;
    hdr->fldSet        = fldSetDsMemVlan;
    hdr->fldGet        = fldGetDsMemVlan;
    hdr->print         = printDsMemVlan;
    hdr->reset         = resetDsMemVlan;
    hdr->destroy       = destroyDsMemVlan;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceMsgAdmInfo0");
    hdr->name          = "InterfaceMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000340;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceMsgAdmInfo0;
    hdr->write         = writeInterfaceMsgAdmInfo0;
    hdr->set           = setInterfaceMsgAdmInfo0;
    hdr->fldSet        = fldSetInterfaceMsgAdmInfo0;
    hdr->fldGet        = fldGetInterfaceMsgAdmInfo0;
    hdr->print         = printInterfaceMsgAdmInfo0;
    hdr->reset         = resetInterfaceMsgAdmInfo0;
    hdr->destroy       = destroyInterfaceMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("InterfaceTmpDsMemMac");
    hdr->name          = "InterfaceTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000350;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readInterfaceTmpDsMemMac;
    hdr->write         = writeInterfaceTmpDsMemMac;
    hdr->set           = setInterfaceTmpDsMemMac;
    hdr->fldSet        = fldSetInterfaceTmpDsMemMac;
    hdr->fldGet        = fldGetInterfaceTmpDsMemMac;
    hdr->print         = printInterfaceTmpDsMemMac;
    hdr->reset         = resetInterfaceTmpDsMemMac;
    hdr->destroy       = destroyInterfaceTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
