/*
 * Software Development Kit for Fisilink
 * @file: LookupManage.c
 * @description: C language expression for LookupManage module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/LookupManageOpr.h>


int insertLookupManageHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlLkpMngLog");
    hdr->name          = "CtlLkpMngLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlLkpMngLog;
    hdr->write         = writeCtlLkpMngLog;
    hdr->set           = setCtlLkpMngLog;
    hdr->fldSet        = fldSetCtlLkpMngLog;
    hdr->fldGet        = fldGetCtlLkpMngLog;
    hdr->print         = printCtlLkpMngLog;
    hdr->reset         = resetCtlLkpMngLog;
    hdr->destroy       = destroyCtlLkpMngLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlLkupCfg");
    hdr->name          = "CtlLkupCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlLkupCfg;
    hdr->write         = writeCtlLkupCfg;
    hdr->set           = setCtlLkupCfg;
    hdr->fldSet        = fldSetCtlLkupCfg;
    hdr->fldGet        = fldGetCtlLkupCfg;
    hdr->print         = printCtlLkupCfg;
    hdr->reset         = resetCtlLkupCfg;
    hdr->destroy       = destroyCtlLkupCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemAclTsn");
    hdr->name          = "LookupManageDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemAclTsn;
    hdr->write         = writeLookupManageDsMemAclTsn;
    hdr->set           = setLookupManageDsMemAclTsn;
    hdr->fldSet        = fldSetLookupManageDsMemAclTsn;
    hdr->fldGet        = fldGetLookupManageDsMemAclTsn;
    hdr->print         = printLookupManageDsMemAclTsn;
    hdr->reset         = resetLookupManageDsMemAclTsn;
    hdr->destroy       = destroyLookupManageDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuIpDportKeyL");
    hdr->name          = "DsMemCuIpDportKeyL";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000018;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuIpDportKeyL;
    hdr->write         = writeDsMemCuIpDportKeyL;
    hdr->set           = setDsMemCuIpDportKeyL;
    hdr->fldSet        = fldSetDsMemCuIpDportKeyL;
    hdr->fldGet        = fldGetDsMemCuIpDportKeyL;
    hdr->print         = printDsMemCuIpDportKeyL;
    hdr->reset         = resetDsMemCuIpDportKeyL;
    hdr->destroy       = destroyDsMemCuIpDportKeyL;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuIpDportKeyR");
    hdr->name          = "DsMemCuIpDportKeyR";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuIpDportKeyR;
    hdr->write         = writeDsMemCuIpDportKeyR;
    hdr->set           = setDsMemCuIpDportKeyR;
    hdr->fldSet        = fldSetDsMemCuIpDportKeyR;
    hdr->fldGet        = fldGetDsMemCuIpDportKeyR;
    hdr->print         = printDsMemCuIpDportKeyR;
    hdr->reset         = resetDsMemCuIpDportKeyR;
    hdr->destroy       = destroyDsMemCuIpDportKeyR;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuIpDscpKeyL");
    hdr->name          = "DsMemCuIpDscpKeyL";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000028;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuIpDscpKeyL;
    hdr->write         = writeDsMemCuIpDscpKeyL;
    hdr->set           = setDsMemCuIpDscpKeyL;
    hdr->fldSet        = fldSetDsMemCuIpDscpKeyL;
    hdr->fldGet        = fldGetDsMemCuIpDscpKeyL;
    hdr->print         = printDsMemCuIpDscpKeyL;
    hdr->reset         = resetDsMemCuIpDscpKeyL;
    hdr->destroy       = destroyDsMemCuIpDscpKeyL;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuIpDscpKeyR");
    hdr->name          = "DsMemCuIpDscpKeyR";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuIpDscpKeyR;
    hdr->write         = writeDsMemCuIpDscpKeyR;
    hdr->set           = setDsMemCuIpDscpKeyR;
    hdr->fldSet        = fldSetDsMemCuIpDscpKeyR;
    hdr->fldGet        = fldGetDsMemCuIpDscpKeyR;
    hdr->print         = printDsMemCuIpDscpKeyR;
    hdr->reset         = resetDsMemCuIpDscpKeyR;
    hdr->destroy       = destroyDsMemCuIpDscpKeyR;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuIpSportKeyL");
    hdr->name          = "DsMemCuIpSportKeyL";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000038;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuIpSportKeyL;
    hdr->write         = writeDsMemCuIpSportKeyL;
    hdr->set           = setDsMemCuIpSportKeyL;
    hdr->fldSet        = fldSetDsMemCuIpSportKeyL;
    hdr->fldGet        = fldGetDsMemCuIpSportKeyL;
    hdr->print         = printDsMemCuIpSportKeyL;
    hdr->reset         = resetDsMemCuIpSportKeyL;
    hdr->destroy       = destroyDsMemCuIpSportKeyL;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuIpSportKeyR");
    hdr->name          = "DsMemCuIpSportKeyR";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuIpSportKeyR;
    hdr->write         = writeDsMemCuIpSportKeyR;
    hdr->set           = setDsMemCuIpSportKeyR;
    hdr->fldSet        = fldSetDsMemCuIpSportKeyR;
    hdr->fldGet        = fldGetDsMemCuIpSportKeyR;
    hdr->print         = printDsMemCuIpSportKeyR;
    hdr->reset         = resetDsMemCuIpSportKeyR;
    hdr->destroy       = destroyDsMemCuIpSportKeyR;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuMacKeyL");
    hdr->name          = "DsMemCuMacKeyL";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000048;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuMacKeyL;
    hdr->write         = writeDsMemCuMacKeyL;
    hdr->set           = setDsMemCuMacKeyL;
    hdr->fldSet        = fldSetDsMemCuMacKeyL;
    hdr->fldGet        = fldGetDsMemCuMacKeyL;
    hdr->print         = printDsMemCuMacKeyL;
    hdr->reset         = resetDsMemCuMacKeyL;
    hdr->destroy       = destroyDsMemCuMacKeyL;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuMacKeyR");
    hdr->name          = "DsMemCuMacKeyR";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000050;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuMacKeyR;
    hdr->write         = writeDsMemCuMacKeyR;
    hdr->set           = setDsMemCuMacKeyR;
    hdr->fldSet        = fldSetDsMemCuMacKeyR;
    hdr->fldGet        = fldGetDsMemCuMacKeyR;
    hdr->print         = printDsMemCuMacKeyR;
    hdr->reset         = resetDsMemCuMacKeyR;
    hdr->destroy       = destroyDsMemCuMacKeyR;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuMacPcpKeyL");
    hdr->name          = "DsMemCuMacPcpKeyL";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000058;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuMacPcpKeyL;
    hdr->write         = writeDsMemCuMacPcpKeyL;
    hdr->set           = setDsMemCuMacPcpKeyL;
    hdr->fldSet        = fldSetDsMemCuMacPcpKeyL;
    hdr->fldGet        = fldGetDsMemCuMacPcpKeyL;
    hdr->print         = printDsMemCuMacPcpKeyL;
    hdr->reset         = resetDsMemCuMacPcpKeyL;
    hdr->destroy       = destroyDsMemCuMacPcpKeyL;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCuMacPcpKeyR");
    hdr->name          = "DsMemCuMacPcpKeyR";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCuMacPcpKeyR;
    hdr->write         = writeDsMemCuMacPcpKeyR;
    hdr->set           = setDsMemCuMacPcpKeyR;
    hdr->fldSet        = fldSetDsMemCuMacPcpKeyR;
    hdr->fldGet        = fldGetDsMemCuMacPcpKeyR;
    hdr->print         = printDsMemCuMacPcpKeyR;
    hdr->reset         = resetDsMemCuMacPcpKeyR;
    hdr->destroy       = destroyDsMemCuMacPcpKeyR;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemFlowColorStats");
    hdr->name          = "LookupManageDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemFlowColorStats;
    hdr->write         = writeLookupManageDsMemFlowColorStats;
    hdr->set           = setLookupManageDsMemFlowColorStats;
    hdr->fldSet        = fldSetLookupManageDsMemFlowColorStats;
    hdr->fldGet        = fldGetLookupManageDsMemFlowColorStats;
    hdr->print         = printLookupManageDsMemFlowColorStats;
    hdr->reset         = resetLookupManageDsMemFlowColorStats;
    hdr->destroy       = destroyLookupManageDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemFlowPolice");
    hdr->name          = "LookupManageDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemFlowPolice;
    hdr->write         = writeLookupManageDsMemFlowPolice;
    hdr->set           = setLookupManageDsMemFlowPolice;
    hdr->fldSet        = fldSetLookupManageDsMemFlowPolice;
    hdr->fldGet        = fldGetLookupManageDsMemFlowPolice;
    hdr->print         = printLookupManageDsMemFlowPolice;
    hdr->reset         = resetLookupManageDsMemFlowPolice;
    hdr->destroy       = destroyLookupManageDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemFlowPoliceCfg");
    hdr->name          = "LookupManageDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemFlowPoliceCfg;
    hdr->write         = writeLookupManageDsMemFlowPoliceCfg;
    hdr->set           = setLookupManageDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetLookupManageDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetLookupManageDsMemFlowPoliceCfg;
    hdr->print         = printLookupManageDsMemFlowPoliceCfg;
    hdr->reset         = resetLookupManageDsMemFlowPoliceCfg;
    hdr->destroy       = destroyLookupManageDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostRoute");
    hdr->name          = "LookupManageDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostRoute;
    hdr->write         = writeLookupManageDsMemHostRoute;
    hdr->set           = setLookupManageDsMemHostRoute;
    hdr->fldSet        = fldSetLookupManageDsMemHostRoute;
    hdr->fldGet        = fldGetLookupManageDsMemHostRoute;
    hdr->print         = printLookupManageDsMemHostRoute;
    hdr->reset         = resetLookupManageDsMemHostRoute;
    hdr->destroy       = destroyLookupManageDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostRouteLeft");
    hdr->name          = "LookupManageDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostRouteLeft;
    hdr->write         = writeLookupManageDsMemHostRouteLeft;
    hdr->set           = setLookupManageDsMemHostRouteLeft;
    hdr->fldSet        = fldSetLookupManageDsMemHostRouteLeft;
    hdr->fldGet        = fldGetLookupManageDsMemHostRouteLeft;
    hdr->print         = printLookupManageDsMemHostRouteLeft;
    hdr->reset         = resetLookupManageDsMemHostRouteLeft;
    hdr->destroy       = destroyLookupManageDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostRouteLeftKey");
    hdr->name          = "LookupManageDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostRouteLeftKey;
    hdr->write         = writeLookupManageDsMemHostRouteLeftKey;
    hdr->set           = setLookupManageDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetLookupManageDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetLookupManageDsMemHostRouteLeftKey;
    hdr->print         = printLookupManageDsMemHostRouteLeftKey;
    hdr->reset         = resetLookupManageDsMemHostRouteLeftKey;
    hdr->destroy       = destroyLookupManageDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostRouteLeftValid");
    hdr->name          = "LookupManageDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostRouteLeftValid;
    hdr->write         = writeLookupManageDsMemHostRouteLeftValid;
    hdr->set           = setLookupManageDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetLookupManageDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetLookupManageDsMemHostRouteLeftValid;
    hdr->print         = printLookupManageDsMemHostRouteLeftValid;
    hdr->reset         = resetLookupManageDsMemHostRouteLeftValid;
    hdr->destroy       = destroyLookupManageDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostRouteRight");
    hdr->name          = "LookupManageDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostRouteRight;
    hdr->write         = writeLookupManageDsMemHostRouteRight;
    hdr->set           = setLookupManageDsMemHostRouteRight;
    hdr->fldSet        = fldSetLookupManageDsMemHostRouteRight;
    hdr->fldGet        = fldGetLookupManageDsMemHostRouteRight;
    hdr->print         = printLookupManageDsMemHostRouteRight;
    hdr->reset         = resetLookupManageDsMemHostRouteRight;
    hdr->destroy       = destroyLookupManageDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostRouteRightKey");
    hdr->name          = "LookupManageDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a8;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostRouteRightKey;
    hdr->write         = writeLookupManageDsMemHostRouteRightKey;
    hdr->set           = setLookupManageDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetLookupManageDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetLookupManageDsMemHostRouteRightKey;
    hdr->print         = printLookupManageDsMemHostRouteRightKey;
    hdr->reset         = resetLookupManageDsMemHostRouteRightKey;
    hdr->destroy       = destroyLookupManageDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostRouteRightValid");
    hdr->name          = "LookupManageDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostRouteRightValid;
    hdr->write         = writeLookupManageDsMemHostRouteRightValid;
    hdr->set           = setLookupManageDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetLookupManageDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetLookupManageDsMemHostRouteRightValid;
    hdr->print         = printLookupManageDsMemHostRouteRightValid;
    hdr->reset         = resetLookupManageDsMemHostRouteRightValid;
    hdr->destroy       = destroyLookupManageDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostTsn");
    hdr->name          = "LookupManageDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostTsn;
    hdr->write         = writeLookupManageDsMemHostTsn;
    hdr->set           = setLookupManageDsMemHostTsn;
    hdr->fldSet        = fldSetLookupManageDsMemHostTsn;
    hdr->fldGet        = fldGetLookupManageDsMemHostTsn;
    hdr->print         = printLookupManageDsMemHostTsn;
    hdr->reset         = resetLookupManageDsMemHostTsn;
    hdr->destroy       = destroyLookupManageDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostTsnLeft");
    hdr->name          = "LookupManageDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostTsnLeft;
    hdr->write         = writeLookupManageDsMemHostTsnLeft;
    hdr->set           = setLookupManageDsMemHostTsnLeft;
    hdr->fldSet        = fldSetLookupManageDsMemHostTsnLeft;
    hdr->fldGet        = fldGetLookupManageDsMemHostTsnLeft;
    hdr->print         = printLookupManageDsMemHostTsnLeft;
    hdr->reset         = resetLookupManageDsMemHostTsnLeft;
    hdr->destroy       = destroyLookupManageDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemHostTsnRight");
    hdr->name          = "LookupManageDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemHostTsnRight;
    hdr->write         = writeLookupManageDsMemHostTsnRight;
    hdr->set           = setLookupManageDsMemHostTsnRight;
    hdr->fldSet        = fldSetLookupManageDsMemHostTsnRight;
    hdr->fldGet        = fldGetLookupManageDsMemHostTsnRight;
    hdr->print         = printLookupManageDsMemHostTsnRight;
    hdr->reset         = resetLookupManageDsMemHostTsnRight;
    hdr->destroy       = destroyLookupManageDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemIndvRcvyCfg");
    hdr->name          = "LookupManageDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemIndvRcvyCfg;
    hdr->write         = writeLookupManageDsMemIndvRcvyCfg;
    hdr->set           = setLookupManageDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetLookupManageDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetLookupManageDsMemIndvRcvyCfg;
    hdr->print         = printLookupManageDsMemIndvRcvyCfg;
    hdr->reset         = resetLookupManageDsMemIndvRcvyCfg;
    hdr->destroy       = destroyLookupManageDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemIndvRcvyCnt");
    hdr->name          = "LookupManageDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemIndvRcvyCnt;
    hdr->write         = writeLookupManageDsMemIndvRcvyCnt;
    hdr->set           = setLookupManageDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetLookupManageDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetLookupManageDsMemIndvRcvyCnt;
    hdr->print         = printLookupManageDsMemIndvRcvyCnt;
    hdr->reset         = resetLookupManageDsMemIndvRcvyCnt;
    hdr->destroy       = destroyLookupManageDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemIndvRcvySeq");
    hdr->name          = "LookupManageDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemIndvRcvySeq;
    hdr->write         = writeLookupManageDsMemIndvRcvySeq;
    hdr->set           = setLookupManageDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetLookupManageDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetLookupManageDsMemIndvRcvySeq;
    hdr->print         = printLookupManageDsMemIndvRcvySeq;
    hdr->reset         = resetLookupManageDsMemIndvRcvySeq;
    hdr->destroy       = destroyLookupManageDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacAgingLeft");
    hdr->name          = "LookupManageDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacAgingLeft;
    hdr->write         = writeLookupManageDsMemMacAgingLeft;
    hdr->set           = setLookupManageDsMemMacAgingLeft;
    hdr->fldSet        = fldSetLookupManageDsMemMacAgingLeft;
    hdr->fldGet        = fldGetLookupManageDsMemMacAgingLeft;
    hdr->print         = printLookupManageDsMemMacAgingLeft;
    hdr->reset         = resetLookupManageDsMemMacAgingLeft;
    hdr->destroy       = destroyLookupManageDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacAgingRight");
    hdr->name          = "LookupManageDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacAgingRight;
    hdr->write         = writeLookupManageDsMemMacAgingRight;
    hdr->set           = setLookupManageDsMemMacAgingRight;
    hdr->fldSet        = fldSetLookupManageDsMemMacAgingRight;
    hdr->fldGet        = fldGetLookupManageDsMemMacAgingRight;
    hdr->print         = printLookupManageDsMemMacAgingRight;
    hdr->reset         = resetLookupManageDsMemMacAgingRight;
    hdr->destroy       = destroyLookupManageDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacKeyLeft");
    hdr->name          = "LookupManageDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f8;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacKeyLeft;
    hdr->write         = writeLookupManageDsMemMacKeyLeft;
    hdr->set           = setLookupManageDsMemMacKeyLeft;
    hdr->fldSet        = fldSetLookupManageDsMemMacKeyLeft;
    hdr->fldGet        = fldGetLookupManageDsMemMacKeyLeft;
    hdr->print         = printLookupManageDsMemMacKeyLeft;
    hdr->reset         = resetLookupManageDsMemMacKeyLeft;
    hdr->destroy       = destroyLookupManageDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacKeyRight");
    hdr->name          = "LookupManageDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacKeyRight;
    hdr->write         = writeLookupManageDsMemMacKeyRight;
    hdr->set           = setLookupManageDsMemMacKeyRight;
    hdr->fldSet        = fldSetLookupManageDsMemMacKeyRight;
    hdr->fldGet        = fldGetLookupManageDsMemMacKeyRight;
    hdr->print         = printLookupManageDsMemMacKeyRight;
    hdr->reset         = resetLookupManageDsMemMacKeyRight;
    hdr->destroy       = destroyLookupManageDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacLeft");
    hdr->name          = "LookupManageDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacLeft;
    hdr->write         = writeLookupManageDsMemMacLeft;
    hdr->set           = setLookupManageDsMemMacLeft;
    hdr->fldSet        = fldSetLookupManageDsMemMacLeft;
    hdr->fldGet        = fldGetLookupManageDsMemMacLeft;
    hdr->print         = printLookupManageDsMemMacLeft;
    hdr->reset         = resetLookupManageDsMemMacLeft;
    hdr->destroy       = destroyLookupManageDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacRight");
    hdr->name          = "LookupManageDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacRight;
    hdr->write         = writeLookupManageDsMemMacRight;
    hdr->set           = setLookupManageDsMemMacRight;
    hdr->fldSet        = fldSetLookupManageDsMemMacRight;
    hdr->fldGet        = fldGetLookupManageDsMemMacRight;
    hdr->print         = printLookupManageDsMemMacRight;
    hdr->reset         = resetLookupManageDsMemMacRight;
    hdr->destroy       = destroyLookupManageDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacStaticLeft");
    hdr->name          = "LookupManageDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacStaticLeft;
    hdr->write         = writeLookupManageDsMemMacStaticLeft;
    hdr->set           = setLookupManageDsMemMacStaticLeft;
    hdr->fldSet        = fldSetLookupManageDsMemMacStaticLeft;
    hdr->fldGet        = fldGetLookupManageDsMemMacStaticLeft;
    hdr->print         = printLookupManageDsMemMacStaticLeft;
    hdr->reset         = resetLookupManageDsMemMacStaticLeft;
    hdr->destroy       = destroyLookupManageDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacStaticRight");
    hdr->name          = "LookupManageDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacStaticRight;
    hdr->write         = writeLookupManageDsMemMacStaticRight;
    hdr->set           = setLookupManageDsMemMacStaticRight;
    hdr->fldSet        = fldSetLookupManageDsMemMacStaticRight;
    hdr->fldGet        = fldGetLookupManageDsMemMacStaticRight;
    hdr->print         = printLookupManageDsMemMacStaticRight;
    hdr->reset         = resetLookupManageDsMemMacStaticRight;
    hdr->destroy       = destroyLookupManageDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacTsn");
    hdr->name          = "LookupManageDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacTsn;
    hdr->write         = writeLookupManageDsMemMacTsn;
    hdr->set           = setLookupManageDsMemMacTsn;
    hdr->fldSet        = fldSetLookupManageDsMemMacTsn;
    hdr->fldGet        = fldGetLookupManageDsMemMacTsn;
    hdr->print         = printLookupManageDsMemMacTsn;
    hdr->reset         = resetLookupManageDsMemMacTsn;
    hdr->destroy       = destroyLookupManageDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacTsnLeft");
    hdr->name          = "LookupManageDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacTsnLeft;
    hdr->write         = writeLookupManageDsMemMacTsnLeft;
    hdr->set           = setLookupManageDsMemMacTsnLeft;
    hdr->fldSet        = fldSetLookupManageDsMemMacTsnLeft;
    hdr->fldGet        = fldGetLookupManageDsMemMacTsnLeft;
    hdr->print         = printLookupManageDsMemMacTsnLeft;
    hdr->reset         = resetLookupManageDsMemMacTsnLeft;
    hdr->destroy       = destroyLookupManageDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacTsnRight");
    hdr->name          = "LookupManageDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacTsnRight;
    hdr->write         = writeLookupManageDsMemMacTsnRight;
    hdr->set           = setLookupManageDsMemMacTsnRight;
    hdr->fldSet        = fldSetLookupManageDsMemMacTsnRight;
    hdr->fldGet        = fldGetLookupManageDsMemMacTsnRight;
    hdr->print         = printLookupManageDsMemMacTsnRight;
    hdr->reset         = resetLookupManageDsMemMacTsnRight;
    hdr->destroy       = destroyLookupManageDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacValidLeft");
    hdr->name          = "LookupManageDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacValidLeft;
    hdr->write         = writeLookupManageDsMemMacValidLeft;
    hdr->set           = setLookupManageDsMemMacValidLeft;
    hdr->fldSet        = fldSetLookupManageDsMemMacValidLeft;
    hdr->fldGet        = fldGetLookupManageDsMemMacValidLeft;
    hdr->print         = printLookupManageDsMemMacValidLeft;
    hdr->reset         = resetLookupManageDsMemMacValidLeft;
    hdr->destroy       = destroyLookupManageDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemMacValidRight");
    hdr->name          = "LookupManageDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000148;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemMacValidRight;
    hdr->write         = writeLookupManageDsMemMacValidRight;
    hdr->set           = setLookupManageDsMemMacValidRight;
    hdr->fldSet        = fldSetLookupManageDsMemMacValidRight;
    hdr->fldGet        = fldGetLookupManageDsMemMacValidRight;
    hdr->print         = printLookupManageDsMemMacValidRight;
    hdr->reset         = resetLookupManageDsMemMacValidRight;
    hdr->destroy       = destroyLookupManageDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemPortColorStats");
    hdr->name          = "LookupManageDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemPortColorStats;
    hdr->write         = writeLookupManageDsMemPortColorStats;
    hdr->set           = setLookupManageDsMemPortColorStats;
    hdr->fldSet        = fldSetLookupManageDsMemPortColorStats;
    hdr->fldGet        = fldGetLookupManageDsMemPortColorStats;
    hdr->print         = printLookupManageDsMemPortColorStats;
    hdr->reset         = resetLookupManageDsMemPortColorStats;
    hdr->destroy       = destroyLookupManageDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemPortPolice");
    hdr->name          = "LookupManageDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemPortPolice;
    hdr->write         = writeLookupManageDsMemPortPolice;
    hdr->set           = setLookupManageDsMemPortPolice;
    hdr->fldSet        = fldSetLookupManageDsMemPortPolice;
    hdr->fldGet        = fldGetLookupManageDsMemPortPolice;
    hdr->print         = printLookupManageDsMemPortPolice;
    hdr->reset         = resetLookupManageDsMemPortPolice;
    hdr->destroy       = destroyLookupManageDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemPortPoliceCfg");
    hdr->name          = "LookupManageDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemPortPoliceCfg;
    hdr->write         = writeLookupManageDsMemPortPoliceCfg;
    hdr->set           = setLookupManageDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetLookupManageDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetLookupManageDsMemPortPoliceCfg;
    hdr->print         = printLookupManageDsMemPortPoliceCfg;
    hdr->reset         = resetLookupManageDsMemPortPoliceCfg;
    hdr->destroy       = destroyLookupManageDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemRouteTsn");
    hdr->name          = "LookupManageDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemRouteTsn;
    hdr->write         = writeLookupManageDsMemRouteTsn;
    hdr->set           = setLookupManageDsMemRouteTsn;
    hdr->fldSet        = fldSetLookupManageDsMemRouteTsn;
    hdr->fldGet        = fldGetLookupManageDsMemRouteTsn;
    hdr->print         = printLookupManageDsMemRouteTsn;
    hdr->reset         = resetLookupManageDsMemRouteTsn;
    hdr->destroy       = destroyLookupManageDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemStreamRcvyCfg");
    hdr->name          = "LookupManageDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemStreamRcvyCfg;
    hdr->write         = writeLookupManageDsMemStreamRcvyCfg;
    hdr->set           = setLookupManageDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetLookupManageDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetLookupManageDsMemStreamRcvyCfg;
    hdr->print         = printLookupManageDsMemStreamRcvyCfg;
    hdr->reset         = resetLookupManageDsMemStreamRcvyCfg;
    hdr->destroy       = destroyLookupManageDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemStreamRcvyCnt");
    hdr->name          = "LookupManageDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemStreamRcvyCnt;
    hdr->write         = writeLookupManageDsMemStreamRcvyCnt;
    hdr->set           = setLookupManageDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetLookupManageDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetLookupManageDsMemStreamRcvyCnt;
    hdr->print         = printLookupManageDsMemStreamRcvyCnt;
    hdr->reset         = resetLookupManageDsMemStreamRcvyCnt;
    hdr->destroy       = destroyLookupManageDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageDsMemStreamRcvySeq");
    hdr->name          = "LookupManageDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000300;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageDsMemStreamRcvySeq;
    hdr->write         = writeLookupManageDsMemStreamRcvySeq;
    hdr->set           = setLookupManageDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetLookupManageDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetLookupManageDsMemStreamRcvySeq;
    hdr->print         = printLookupManageDsMemStreamRcvySeq;
    hdr->reset         = resetLookupManageDsMemStreamRcvySeq;
    hdr->destroy       = destroyLookupManageDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageMsgAdmInfo0");
    hdr->name          = "LookupManageMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000310;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageMsgAdmInfo0;
    hdr->write         = writeLookupManageMsgAdmInfo0;
    hdr->set           = setLookupManageMsgAdmInfo0;
    hdr->fldSet        = fldSetLookupManageMsgAdmInfo0;
    hdr->fldGet        = fldGetLookupManageMsgAdmInfo0;
    hdr->print         = printLookupManageMsgAdmInfo0;
    hdr->reset         = resetLookupManageMsgAdmInfo0;
    hdr->destroy       = destroyLookupManageMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("LookupManageTmpDsMemMac");
    hdr->name          = "LookupManageTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000320;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readLookupManageTmpDsMemMac;
    hdr->write         = writeLookupManageTmpDsMemMac;
    hdr->set           = setLookupManageTmpDsMemMac;
    hdr->fldSet        = fldSetLookupManageTmpDsMemMac;
    hdr->fldGet        = fldGetLookupManageTmpDsMemMac;
    hdr->print         = printLookupManageTmpDsMemMac;
    hdr->reset         = resetLookupManageTmpDsMemMac;
    hdr->destroy       = destroyLookupManageTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
