/*
 * Software Development Kit for Fisilink
 * @file: PacketParser.c
 * @description: C language expression for PacketParser module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/PacketParserOpr.h>


int insertPacketParserHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlDosControl");
    hdr->name          = "CtlDosControl";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlDosControl;
    hdr->write         = writeCtlDosControl;
    hdr->set           = setCtlDosControl;
    hdr->fldSet        = fldSetCtlDosControl;
    hdr->fldGet        = fldGetCtlDosControl;
    hdr->print         = printCtlDosControl;
    hdr->reset         = resetCtlDosControl;
    hdr->destroy       = destroyCtlDosControl;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlL2HdrProtoCam");
    hdr->name          = "CtlL2HdrProtoCam";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlL2HdrProtoCam;
    hdr->write         = writeCtlL2HdrProtoCam;
    hdr->set           = setCtlL2HdrProtoCam;
    hdr->fldSet        = fldSetCtlL2HdrProtoCam;
    hdr->fldGet        = fldGetCtlL2HdrProtoCam;
    hdr->print         = printCtlL2HdrProtoCam;
    hdr->reset         = resetCtlL2HdrProtoCam;
    hdr->destroy       = destroyCtlL2HdrProtoCam;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlL3HdrProtoCam");
    hdr->name          = "CtlL3HdrProtoCam";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 3;
    hdr->granularity   = roundupPow2(3);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlL3HdrProtoCam;
    hdr->write         = writeCtlL3HdrProtoCam;
    hdr->set           = setCtlL3HdrProtoCam;
    hdr->fldSet        = fldSetCtlL3HdrProtoCam;
    hdr->fldGet        = fldGetCtlL3HdrProtoCam;
    hdr->print         = printCtlL3HdrProtoCam;
    hdr->reset         = resetCtlL3HdrProtoCam;
    hdr->destroy       = destroyCtlL3HdrProtoCam;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlParserEthernet");
    hdr->name          = "CtlParserEthernet";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlParserEthernet;
    hdr->write         = writeCtlParserEthernet;
    hdr->set           = setCtlParserEthernet;
    hdr->fldSet        = fldSetCtlParserEthernet;
    hdr->fldGet        = fldGetCtlParserEthernet;
    hdr->print         = printCtlParserEthernet;
    hdr->reset         = resetCtlParserEthernet;
    hdr->destroy       = destroyCtlParserEthernet;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlParserL4Port");
    hdr->name          = "CtlParserL4Port";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlParserL4Port;
    hdr->write         = writeCtlParserL4Port;
    hdr->set           = setCtlParserL4Port;
    hdr->fldSet        = fldSetCtlParserL4Port;
    hdr->fldGet        = fldGetCtlParserL4Port;
    hdr->print         = printCtlParserL4Port;
    hdr->reset         = resetCtlParserL4Port;
    hdr->destroy       = destroyCtlParserL4Port;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlParserTsn");
    hdr->name          = "CtlParserTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000050;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlParserTsn;
    hdr->write         = writeCtlParserTsn;
    hdr->set           = setCtlParserTsn;
    hdr->fldSet        = fldSetCtlParserTsn;
    hdr->fldGet        = fldGetCtlParserTsn;
    hdr->print         = printCtlParserTsn;
    hdr->reset         = resetCtlParserTsn;
    hdr->destroy       = destroyCtlParserTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlPktParserLog");
    hdr->name          = "CtlPktParserLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlPktParserLog;
    hdr->write         = writeCtlPktParserLog;
    hdr->set           = setCtlPktParserLog;
    hdr->fldSet        = fldSetCtlPktParserLog;
    hdr->fldGet        = fldGetCtlPktParserLog;
    hdr->print         = printCtlPktParserLog;
    hdr->reset         = resetCtlPktParserLog;
    hdr->destroy       = destroyCtlPktParserLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemAclTsn");
    hdr->name          = "PacketParserDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemAclTsn;
    hdr->write         = writePacketParserDsMemAclTsn;
    hdr->set           = setPacketParserDsMemAclTsn;
    hdr->fldSet        = fldSetPacketParserDsMemAclTsn;
    hdr->fldGet        = fldGetPacketParserDsMemAclTsn;
    hdr->print         = printPacketParserDsMemAclTsn;
    hdr->reset         = resetPacketParserDsMemAclTsn;
    hdr->destroy       = destroyPacketParserDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemFlowColorStats");
    hdr->name          = "PacketParserDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000080;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemFlowColorStats;
    hdr->write         = writePacketParserDsMemFlowColorStats;
    hdr->set           = setPacketParserDsMemFlowColorStats;
    hdr->fldSet        = fldSetPacketParserDsMemFlowColorStats;
    hdr->fldGet        = fldGetPacketParserDsMemFlowColorStats;
    hdr->print         = printPacketParserDsMemFlowColorStats;
    hdr->reset         = resetPacketParserDsMemFlowColorStats;
    hdr->destroy       = destroyPacketParserDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemFlowPolice");
    hdr->name          = "PacketParserDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemFlowPolice;
    hdr->write         = writePacketParserDsMemFlowPolice;
    hdr->set           = setPacketParserDsMemFlowPolice;
    hdr->fldSet        = fldSetPacketParserDsMemFlowPolice;
    hdr->fldGet        = fldGetPacketParserDsMemFlowPolice;
    hdr->print         = printPacketParserDsMemFlowPolice;
    hdr->reset         = resetPacketParserDsMemFlowPolice;
    hdr->destroy       = destroyPacketParserDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemFlowPoliceCfg");
    hdr->name          = "PacketParserDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemFlowPoliceCfg;
    hdr->write         = writePacketParserDsMemFlowPoliceCfg;
    hdr->set           = setPacketParserDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetPacketParserDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetPacketParserDsMemFlowPoliceCfg;
    hdr->print         = printPacketParserDsMemFlowPoliceCfg;
    hdr->reset         = resetPacketParserDsMemFlowPoliceCfg;
    hdr->destroy       = destroyPacketParserDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostRoute");
    hdr->name          = "PacketParserDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostRoute;
    hdr->write         = writePacketParserDsMemHostRoute;
    hdr->set           = setPacketParserDsMemHostRoute;
    hdr->fldSet        = fldSetPacketParserDsMemHostRoute;
    hdr->fldGet        = fldGetPacketParserDsMemHostRoute;
    hdr->print         = printPacketParserDsMemHostRoute;
    hdr->reset         = resetPacketParserDsMemHostRoute;
    hdr->destroy       = destroyPacketParserDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostRouteLeft");
    hdr->name          = "PacketParserDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostRouteLeft;
    hdr->write         = writePacketParserDsMemHostRouteLeft;
    hdr->set           = setPacketParserDsMemHostRouteLeft;
    hdr->fldSet        = fldSetPacketParserDsMemHostRouteLeft;
    hdr->fldGet        = fldGetPacketParserDsMemHostRouteLeft;
    hdr->print         = printPacketParserDsMemHostRouteLeft;
    hdr->reset         = resetPacketParserDsMemHostRouteLeft;
    hdr->destroy       = destroyPacketParserDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostRouteLeftKey");
    hdr->name          = "PacketParserDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostRouteLeftKey;
    hdr->write         = writePacketParserDsMemHostRouteLeftKey;
    hdr->set           = setPacketParserDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetPacketParserDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetPacketParserDsMemHostRouteLeftKey;
    hdr->print         = printPacketParserDsMemHostRouteLeftKey;
    hdr->reset         = resetPacketParserDsMemHostRouteLeftKey;
    hdr->destroy       = destroyPacketParserDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostRouteLeftValid");
    hdr->name          = "PacketParserDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostRouteLeftValid;
    hdr->write         = writePacketParserDsMemHostRouteLeftValid;
    hdr->set           = setPacketParserDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetPacketParserDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetPacketParserDsMemHostRouteLeftValid;
    hdr->print         = printPacketParserDsMemHostRouteLeftValid;
    hdr->reset         = resetPacketParserDsMemHostRouteLeftValid;
    hdr->destroy       = destroyPacketParserDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostRouteRight");
    hdr->name          = "PacketParserDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostRouteRight;
    hdr->write         = writePacketParserDsMemHostRouteRight;
    hdr->set           = setPacketParserDsMemHostRouteRight;
    hdr->fldSet        = fldSetPacketParserDsMemHostRouteRight;
    hdr->fldGet        = fldGetPacketParserDsMemHostRouteRight;
    hdr->print         = printPacketParserDsMemHostRouteRight;
    hdr->reset         = resetPacketParserDsMemHostRouteRight;
    hdr->destroy       = destroyPacketParserDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostRouteRightKey");
    hdr->name          = "PacketParserDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostRouteRightKey;
    hdr->write         = writePacketParserDsMemHostRouteRightKey;
    hdr->set           = setPacketParserDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetPacketParserDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetPacketParserDsMemHostRouteRightKey;
    hdr->print         = printPacketParserDsMemHostRouteRightKey;
    hdr->reset         = resetPacketParserDsMemHostRouteRightKey;
    hdr->destroy       = destroyPacketParserDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostRouteRightValid");
    hdr->name          = "PacketParserDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostRouteRightValid;
    hdr->write         = writePacketParserDsMemHostRouteRightValid;
    hdr->set           = setPacketParserDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetPacketParserDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetPacketParserDsMemHostRouteRightValid;
    hdr->print         = printPacketParserDsMemHostRouteRightValid;
    hdr->reset         = resetPacketParserDsMemHostRouteRightValid;
    hdr->destroy       = destroyPacketParserDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostTsn");
    hdr->name          = "PacketParserDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostTsn;
    hdr->write         = writePacketParserDsMemHostTsn;
    hdr->set           = setPacketParserDsMemHostTsn;
    hdr->fldSet        = fldSetPacketParserDsMemHostTsn;
    hdr->fldGet        = fldGetPacketParserDsMemHostTsn;
    hdr->print         = printPacketParserDsMemHostTsn;
    hdr->reset         = resetPacketParserDsMemHostTsn;
    hdr->destroy       = destroyPacketParserDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostTsnLeft");
    hdr->name          = "PacketParserDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostTsnLeft;
    hdr->write         = writePacketParserDsMemHostTsnLeft;
    hdr->set           = setPacketParserDsMemHostTsnLeft;
    hdr->fldSet        = fldSetPacketParserDsMemHostTsnLeft;
    hdr->fldGet        = fldGetPacketParserDsMemHostTsnLeft;
    hdr->print         = printPacketParserDsMemHostTsnLeft;
    hdr->reset         = resetPacketParserDsMemHostTsnLeft;
    hdr->destroy       = destroyPacketParserDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemHostTsnRight");
    hdr->name          = "PacketParserDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemHostTsnRight;
    hdr->write         = writePacketParserDsMemHostTsnRight;
    hdr->set           = setPacketParserDsMemHostTsnRight;
    hdr->fldSet        = fldSetPacketParserDsMemHostTsnRight;
    hdr->fldGet        = fldGetPacketParserDsMemHostTsnRight;
    hdr->print         = printPacketParserDsMemHostTsnRight;
    hdr->reset         = resetPacketParserDsMemHostTsnRight;
    hdr->destroy       = destroyPacketParserDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemIndvRcvyCfg");
    hdr->name          = "PacketParserDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemIndvRcvyCfg;
    hdr->write         = writePacketParserDsMemIndvRcvyCfg;
    hdr->set           = setPacketParserDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetPacketParserDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetPacketParserDsMemIndvRcvyCfg;
    hdr->print         = printPacketParserDsMemIndvRcvyCfg;
    hdr->reset         = resetPacketParserDsMemIndvRcvyCfg;
    hdr->destroy       = destroyPacketParserDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemIndvRcvyCnt");
    hdr->name          = "PacketParserDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemIndvRcvyCnt;
    hdr->write         = writePacketParserDsMemIndvRcvyCnt;
    hdr->set           = setPacketParserDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetPacketParserDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetPacketParserDsMemIndvRcvyCnt;
    hdr->print         = printPacketParserDsMemIndvRcvyCnt;
    hdr->reset         = resetPacketParserDsMemIndvRcvyCnt;
    hdr->destroy       = destroyPacketParserDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemIndvRcvySeq");
    hdr->name          = "PacketParserDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemIndvRcvySeq;
    hdr->write         = writePacketParserDsMemIndvRcvySeq;
    hdr->set           = setPacketParserDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetPacketParserDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetPacketParserDsMemIndvRcvySeq;
    hdr->print         = printPacketParserDsMemIndvRcvySeq;
    hdr->reset         = resetPacketParserDsMemIndvRcvySeq;
    hdr->destroy       = destroyPacketParserDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacAgingLeft");
    hdr->name          = "PacketParserDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacAgingLeft;
    hdr->write         = writePacketParserDsMemMacAgingLeft;
    hdr->set           = setPacketParserDsMemMacAgingLeft;
    hdr->fldSet        = fldSetPacketParserDsMemMacAgingLeft;
    hdr->fldGet        = fldGetPacketParserDsMemMacAgingLeft;
    hdr->print         = printPacketParserDsMemMacAgingLeft;
    hdr->reset         = resetPacketParserDsMemMacAgingLeft;
    hdr->destroy       = destroyPacketParserDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacAgingRight");
    hdr->name          = "PacketParserDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacAgingRight;
    hdr->write         = writePacketParserDsMemMacAgingRight;
    hdr->set           = setPacketParserDsMemMacAgingRight;
    hdr->fldSet        = fldSetPacketParserDsMemMacAgingRight;
    hdr->fldGet        = fldGetPacketParserDsMemMacAgingRight;
    hdr->print         = printPacketParserDsMemMacAgingRight;
    hdr->reset         = resetPacketParserDsMemMacAgingRight;
    hdr->destroy       = destroyPacketParserDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacKeyLeft");
    hdr->name          = "PacketParserDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacKeyLeft;
    hdr->write         = writePacketParserDsMemMacKeyLeft;
    hdr->set           = setPacketParserDsMemMacKeyLeft;
    hdr->fldSet        = fldSetPacketParserDsMemMacKeyLeft;
    hdr->fldGet        = fldGetPacketParserDsMemMacKeyLeft;
    hdr->print         = printPacketParserDsMemMacKeyLeft;
    hdr->reset         = resetPacketParserDsMemMacKeyLeft;
    hdr->destroy       = destroyPacketParserDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacKeyRight");
    hdr->name          = "PacketParserDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacKeyRight;
    hdr->write         = writePacketParserDsMemMacKeyRight;
    hdr->set           = setPacketParserDsMemMacKeyRight;
    hdr->fldSet        = fldSetPacketParserDsMemMacKeyRight;
    hdr->fldGet        = fldGetPacketParserDsMemMacKeyRight;
    hdr->print         = printPacketParserDsMemMacKeyRight;
    hdr->reset         = resetPacketParserDsMemMacKeyRight;
    hdr->destroy       = destroyPacketParserDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacLeft");
    hdr->name          = "PacketParserDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacLeft;
    hdr->write         = writePacketParserDsMemMacLeft;
    hdr->set           = setPacketParserDsMemMacLeft;
    hdr->fldSet        = fldSetPacketParserDsMemMacLeft;
    hdr->fldGet        = fldGetPacketParserDsMemMacLeft;
    hdr->print         = printPacketParserDsMemMacLeft;
    hdr->reset         = resetPacketParserDsMemMacLeft;
    hdr->destroy       = destroyPacketParserDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacRight");
    hdr->name          = "PacketParserDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacRight;
    hdr->write         = writePacketParserDsMemMacRight;
    hdr->set           = setPacketParserDsMemMacRight;
    hdr->fldSet        = fldSetPacketParserDsMemMacRight;
    hdr->fldGet        = fldGetPacketParserDsMemMacRight;
    hdr->print         = printPacketParserDsMemMacRight;
    hdr->reset         = resetPacketParserDsMemMacRight;
    hdr->destroy       = destroyPacketParserDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacStaticLeft");
    hdr->name          = "PacketParserDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacStaticLeft;
    hdr->write         = writePacketParserDsMemMacStaticLeft;
    hdr->set           = setPacketParserDsMemMacStaticLeft;
    hdr->fldSet        = fldSetPacketParserDsMemMacStaticLeft;
    hdr->fldGet        = fldGetPacketParserDsMemMacStaticLeft;
    hdr->print         = printPacketParserDsMemMacStaticLeft;
    hdr->reset         = resetPacketParserDsMemMacStaticLeft;
    hdr->destroy       = destroyPacketParserDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacStaticRight");
    hdr->name          = "PacketParserDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacStaticRight;
    hdr->write         = writePacketParserDsMemMacStaticRight;
    hdr->set           = setPacketParserDsMemMacStaticRight;
    hdr->fldSet        = fldSetPacketParserDsMemMacStaticRight;
    hdr->fldGet        = fldGetPacketParserDsMemMacStaticRight;
    hdr->print         = printPacketParserDsMemMacStaticRight;
    hdr->reset         = resetPacketParserDsMemMacStaticRight;
    hdr->destroy       = destroyPacketParserDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacTsn");
    hdr->name          = "PacketParserDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacTsn;
    hdr->write         = writePacketParserDsMemMacTsn;
    hdr->set           = setPacketParserDsMemMacTsn;
    hdr->fldSet        = fldSetPacketParserDsMemMacTsn;
    hdr->fldGet        = fldGetPacketParserDsMemMacTsn;
    hdr->print         = printPacketParserDsMemMacTsn;
    hdr->reset         = resetPacketParserDsMemMacTsn;
    hdr->destroy       = destroyPacketParserDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacTsnLeft");
    hdr->name          = "PacketParserDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacTsnLeft;
    hdr->write         = writePacketParserDsMemMacTsnLeft;
    hdr->set           = setPacketParserDsMemMacTsnLeft;
    hdr->fldSet        = fldSetPacketParserDsMemMacTsnLeft;
    hdr->fldGet        = fldGetPacketParserDsMemMacTsnLeft;
    hdr->print         = printPacketParserDsMemMacTsnLeft;
    hdr->reset         = resetPacketParserDsMemMacTsnLeft;
    hdr->destroy       = destroyPacketParserDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacTsnRight");
    hdr->name          = "PacketParserDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacTsnRight;
    hdr->write         = writePacketParserDsMemMacTsnRight;
    hdr->set           = setPacketParserDsMemMacTsnRight;
    hdr->fldSet        = fldSetPacketParserDsMemMacTsnRight;
    hdr->fldGet        = fldGetPacketParserDsMemMacTsnRight;
    hdr->print         = printPacketParserDsMemMacTsnRight;
    hdr->reset         = resetPacketParserDsMemMacTsnRight;
    hdr->destroy       = destroyPacketParserDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacValidLeft");
    hdr->name          = "PacketParserDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacValidLeft;
    hdr->write         = writePacketParserDsMemMacValidLeft;
    hdr->set           = setPacketParserDsMemMacValidLeft;
    hdr->fldSet        = fldSetPacketParserDsMemMacValidLeft;
    hdr->fldGet        = fldGetPacketParserDsMemMacValidLeft;
    hdr->print         = printPacketParserDsMemMacValidLeft;
    hdr->reset         = resetPacketParserDsMemMacValidLeft;
    hdr->destroy       = destroyPacketParserDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemMacValidRight");
    hdr->name          = "PacketParserDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemMacValidRight;
    hdr->write         = writePacketParserDsMemMacValidRight;
    hdr->set           = setPacketParserDsMemMacValidRight;
    hdr->fldSet        = fldSetPacketParserDsMemMacValidRight;
    hdr->fldGet        = fldGetPacketParserDsMemMacValidRight;
    hdr->print         = printPacketParserDsMemMacValidRight;
    hdr->reset         = resetPacketParserDsMemMacValidRight;
    hdr->destroy       = destroyPacketParserDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemPortColorStats");
    hdr->name          = "PacketParserDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemPortColorStats;
    hdr->write         = writePacketParserDsMemPortColorStats;
    hdr->set           = setPacketParserDsMemPortColorStats;
    hdr->fldSet        = fldSetPacketParserDsMemPortColorStats;
    hdr->fldGet        = fldGetPacketParserDsMemPortColorStats;
    hdr->print         = printPacketParserDsMemPortColorStats;
    hdr->reset         = resetPacketParserDsMemPortColorStats;
    hdr->destroy       = destroyPacketParserDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemPortPolice");
    hdr->name          = "PacketParserDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemPortPolice;
    hdr->write         = writePacketParserDsMemPortPolice;
    hdr->set           = setPacketParserDsMemPortPolice;
    hdr->fldSet        = fldSetPacketParserDsMemPortPolice;
    hdr->fldGet        = fldGetPacketParserDsMemPortPolice;
    hdr->print         = printPacketParserDsMemPortPolice;
    hdr->reset         = resetPacketParserDsMemPortPolice;
    hdr->destroy       = destroyPacketParserDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemPortPoliceCfg");
    hdr->name          = "PacketParserDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemPortPoliceCfg;
    hdr->write         = writePacketParserDsMemPortPoliceCfg;
    hdr->set           = setPacketParserDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetPacketParserDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetPacketParserDsMemPortPoliceCfg;
    hdr->print         = printPacketParserDsMemPortPoliceCfg;
    hdr->reset         = resetPacketParserDsMemPortPoliceCfg;
    hdr->destroy       = destroyPacketParserDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemRouteTsn");
    hdr->name          = "PacketParserDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemRouteTsn;
    hdr->write         = writePacketParserDsMemRouteTsn;
    hdr->set           = setPacketParserDsMemRouteTsn;
    hdr->fldSet        = fldSetPacketParserDsMemRouteTsn;
    hdr->fldGet        = fldGetPacketParserDsMemRouteTsn;
    hdr->print         = printPacketParserDsMemRouteTsn;
    hdr->reset         = resetPacketParserDsMemRouteTsn;
    hdr->destroy       = destroyPacketParserDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemStreamRcvyCfg");
    hdr->name          = "PacketParserDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000290;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemStreamRcvyCfg;
    hdr->write         = writePacketParserDsMemStreamRcvyCfg;
    hdr->set           = setPacketParserDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetPacketParserDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetPacketParserDsMemStreamRcvyCfg;
    hdr->print         = printPacketParserDsMemStreamRcvyCfg;
    hdr->reset         = resetPacketParserDsMemStreamRcvyCfg;
    hdr->destroy       = destroyPacketParserDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemStreamRcvyCnt");
    hdr->name          = "PacketParserDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemStreamRcvyCnt;
    hdr->write         = writePacketParserDsMemStreamRcvyCnt;
    hdr->set           = setPacketParserDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetPacketParserDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetPacketParserDsMemStreamRcvyCnt;
    hdr->print         = printPacketParserDsMemStreamRcvyCnt;
    hdr->reset         = resetPacketParserDsMemStreamRcvyCnt;
    hdr->destroy       = destroyPacketParserDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserDsMemStreamRcvySeq");
    hdr->name          = "PacketParserDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserDsMemStreamRcvySeq;
    hdr->write         = writePacketParserDsMemStreamRcvySeq;
    hdr->set           = setPacketParserDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetPacketParserDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetPacketParserDsMemStreamRcvySeq;
    hdr->print         = printPacketParserDsMemStreamRcvySeq;
    hdr->reset         = resetPacketParserDsMemStreamRcvySeq;
    hdr->destroy       = destroyPacketParserDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemUdfOffset");
    hdr->name          = "DsMemUdfOffset";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemUdfOffset;
    hdr->write         = writeDsMemUdfOffset;
    hdr->set           = setDsMemUdfOffset;
    hdr->fldSet        = fldSetDsMemUdfOffset;
    hdr->fldGet        = fldGetDsMemUdfOffset;
    hdr->print         = printDsMemUdfOffset;
    hdr->reset         = resetDsMemUdfOffset;
    hdr->destroy       = destroyDsMemUdfOffset;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserMsgAdmInfo0");
    hdr->name          = "PacketParserMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserMsgAdmInfo0;
    hdr->write         = writePacketParserMsgAdmInfo0;
    hdr->set           = setPacketParserMsgAdmInfo0;
    hdr->fldSet        = fldSetPacketParserMsgAdmInfo0;
    hdr->fldGet        = fldGetPacketParserMsgAdmInfo0;
    hdr->print         = printPacketParserMsgAdmInfo0;
    hdr->reset         = resetPacketParserMsgAdmInfo0;
    hdr->destroy       = destroyPacketParserMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketParserTmpDsMemMac");
    hdr->name          = "PacketParserTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketParserTmpDsMemMac;
    hdr->write         = writePacketParserTmpDsMemMac;
    hdr->set           = setPacketParserTmpDsMemMac;
    hdr->fldSet        = fldSetPacketParserTmpDsMemMac;
    hdr->fldGet        = fldGetPacketParserTmpDsMemMac;
    hdr->print         = printPacketParserTmpDsMemMac;
    hdr->reset         = resetPacketParserTmpDsMemMac;
    hdr->destroy       = destroyPacketParserTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
