/*
 * Software Development Kit for Fisilink
 * @file: PacketEdit.c
 * @description: C language expression for PacketEdit module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/PacketEditOpr.h>


int insertPacketEditHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditCtlCommon");
    hdr->name          = "PacketEditCtlCommon";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditCtlCommon;
    hdr->write         = writePacketEditCtlCommon;
    hdr->set           = setPacketEditCtlCommon;
    hdr->fldSet        = fldSetPacketEditCtlCommon;
    hdr->fldGet        = fldGetPacketEditCtlCommon;
    hdr->print         = printPacketEditCtlCommon;
    hdr->reset         = resetPacketEditCtlCommon;
    hdr->destroy       = destroyPacketEditCtlCommon;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEgrCpu");
    hdr->name          = "CtlEgrCpu";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEgrCpu;
    hdr->write         = writeCtlEgrCpu;
    hdr->set           = setCtlEgrCpu;
    hdr->fldSet        = fldSetCtlEgrCpu;
    hdr->fldGet        = fldGetCtlEgrCpu;
    hdr->print         = printCtlEgrCpu;
    hdr->reset         = resetCtlEgrCpu;
    hdr->destroy       = destroyCtlEgrCpu;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEgrDot1qTpid");
    hdr->name          = "CtlEgrDot1qTpid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEgrDot1qTpid;
    hdr->write         = writeCtlEgrDot1qTpid;
    hdr->set           = setCtlEgrDot1qTpid;
    hdr->fldSet        = fldSetCtlEgrDot1qTpid;
    hdr->fldGet        = fldGetCtlEgrDot1qTpid;
    hdr->print         = printCtlEgrDot1qTpid;
    hdr->reset         = resetCtlEgrDot1qTpid;
    hdr->destroy       = destroyCtlEgrDot1qTpid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEgrEdit");
    hdr->name          = "CtlEgrEdit";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000018;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEgrEdit;
    hdr->write         = writeCtlEgrEdit;
    hdr->set           = setCtlEgrEdit;
    hdr->fldSet        = fldSetCtlEgrEdit;
    hdr->fldGet        = fldGetCtlEgrEdit;
    hdr->print         = printCtlEgrEdit;
    hdr->reset         = resetCtlEgrEdit;
    hdr->destroy       = destroyCtlEgrEdit;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEgrExcpDestPort");
    hdr->name          = "CtlEgrExcpDestPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEgrExcpDestPort;
    hdr->write         = writeCtlEgrExcpDestPort;
    hdr->set           = setCtlEgrExcpDestPort;
    hdr->fldSet        = fldSetCtlEgrExcpDestPort;
    hdr->fldGet        = fldGetCtlEgrExcpDestPort;
    hdr->print         = printCtlEgrExcpDestPort;
    hdr->reset         = resetCtlEgrExcpDestPort;
    hdr->destroy       = destroyCtlEgrExcpDestPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEgrExt");
    hdr->name          = "CtlEgrExt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000028;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEgrExt;
    hdr->write         = writeCtlEgrExt;
    hdr->set           = setCtlEgrExt;
    hdr->fldSet        = fldSetCtlEgrExt;
    hdr->fldGet        = fldGetCtlEgrExt;
    hdr->print         = printCtlEgrExt;
    hdr->reset         = resetCtlEgrExt;
    hdr->destroy       = destroyCtlEgrExt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEgrLog");
    hdr->name          = "CtlEgrLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEgrLog;
    hdr->write         = writeCtlEgrLog;
    hdr->set           = setCtlEgrLog;
    hdr->fldSet        = fldSetCtlEgrLog;
    hdr->fldGet        = fldGetCtlEgrLog;
    hdr->print         = printCtlEgrLog;
    hdr->reset         = resetCtlEgrLog;
    hdr->destroy       = destroyCtlEgrLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEgrOam");
    hdr->name          = "CtlEgrOam";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000038;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEgrOam;
    hdr->write         = writeCtlEgrOam;
    hdr->set           = setCtlEgrOam;
    hdr->fldSet        = fldSetCtlEgrOam;
    hdr->fldGet        = fldGetCtlEgrOam;
    hdr->print         = printCtlEgrOam;
    hdr->reset         = resetCtlEgrOam;
    hdr->destroy       = destroyCtlEgrOam;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlRemoteSpan");
    hdr->name          = "CtlRemoteSpan";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlRemoteSpan;
    hdr->write         = writeCtlRemoteSpan;
    hdr->set           = setCtlRemoteSpan;
    hdr->fldSet        = fldSetCtlRemoteSpan;
    hdr->fldGet        = fldGetCtlRemoteSpan;
    hdr->print         = printCtlRemoteSpan;
    hdr->reset         = resetCtlRemoteSpan;
    hdr->destroy       = destroyCtlRemoteSpan;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlRouterPktMac");
    hdr->name          = "CtlRouterPktMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000048;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlRouterPktMac;
    hdr->write         = writeCtlRouterPktMac;
    hdr->set           = setCtlRouterPktMac;
    hdr->fldSet        = fldSetCtlRouterPktMac;
    hdr->fldGet        = fldGetCtlRouterPktMac;
    hdr->print         = printCtlRouterPktMac;
    hdr->reset         = resetCtlRouterPktMac;
    hdr->destroy       = destroyCtlRouterPktMac;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemAclTsn");
    hdr->name          = "PacketEditDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemAclTsn;
    hdr->write         = writePacketEditDsMemAclTsn;
    hdr->set           = setPacketEditDsMemAclTsn;
    hdr->fldSet        = fldSetPacketEditDsMemAclTsn;
    hdr->fldGet        = fldGetPacketEditDsMemAclTsn;
    hdr->print         = printPacketEditDsMemAclTsn;
    hdr->reset         = resetPacketEditDsMemAclTsn;
    hdr->destroy       = destroyPacketEditDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemDestPort");
    hdr->name          = "DsMemDestPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000058;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemDestPort;
    hdr->write         = writeDsMemDestPort;
    hdr->set           = setDsMemDestPort;
    hdr->fldSet        = fldSetDsMemDestPort;
    hdr->fldGet        = fldGetDsMemDestPort;
    hdr->print         = printDsMemDestPort;
    hdr->reset         = resetDsMemDestPort;
    hdr->destroy       = destroyDsMemDestPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemDestStpState");
    hdr->name          = "DsMemDestStpState";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemDestStpState;
    hdr->write         = writeDsMemDestStpState;
    hdr->set           = setDsMemDestStpState;
    hdr->fldSet        = fldSetDsMemDestStpState;
    hdr->fldGet        = fldGetDsMemDestStpState;
    hdr->print         = printDsMemDestStpState;
    hdr->reset         = resetDsMemDestStpState;
    hdr->destroy       = destroyDsMemDestStpState;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemDestVlan");
    hdr->name          = "DsMemDestVlan";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000068;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemDestVlan;
    hdr->write         = writeDsMemDestVlan;
    hdr->set           = setDsMemDestVlan;
    hdr->fldSet        = fldSetDsMemDestVlan;
    hdr->fldGet        = fldGetDsMemDestVlan;
    hdr->print         = printDsMemDestVlan;
    hdr->reset         = resetDsMemDestVlan;
    hdr->destroy       = destroyDsMemDestVlan;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemEgrExcpStats");
    hdr->name          = "DsMemEgrExcpStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemEgrExcpStats;
    hdr->write         = writeDsMemEgrExcpStats;
    hdr->set           = setDsMemEgrExcpStats;
    hdr->fldSet        = fldSetDsMemEgrExcpStats;
    hdr->fldGet        = fldGetDsMemEgrExcpStats;
    hdr->print         = printDsMemEgrExcpStats;
    hdr->reset         = resetDsMemEgrExcpStats;
    hdr->destroy       = destroyDsMemEgrExcpStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemEgrMepPtr");
    hdr->name          = "DsMemEgrMepPtr";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000078;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemEgrMepPtr;
    hdr->write         = writeDsMemEgrMepPtr;
    hdr->set           = setDsMemEgrMepPtr;
    hdr->fldSet        = fldSetDsMemEgrMepPtr;
    hdr->fldGet        = fldGetDsMemEgrMepPtr;
    hdr->print         = printDsMemEgrMepPtr;
    hdr->reset         = resetDsMemEgrMepPtr;
    hdr->destroy       = destroyDsMemEgrMepPtr;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemEgrOamKey");
    hdr->name          = "DsMemEgrOamKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000080;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemEgrOamKey;
    hdr->write         = writeDsMemEgrOamKey;
    hdr->set           = setDsMemEgrOamKey;
    hdr->fldSet        = fldSetDsMemEgrOamKey;
    hdr->fldGet        = fldGetDsMemEgrOamKey;
    hdr->print         = printDsMemEgrOamKey;
    hdr->reset         = resetDsMemEgrOamKey;
    hdr->destroy       = destroyDsMemEgrOamKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemEgrOamSession");
    hdr->name          = "DsMemEgrOamSession";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000088;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemEgrOamSession;
    hdr->write         = writeDsMemEgrOamSession;
    hdr->set           = setDsMemEgrOamSession;
    hdr->fldSet        = fldSetDsMemEgrOamSession;
    hdr->fldGet        = fldGetDsMemEgrOamSession;
    hdr->print         = printDsMemEgrOamSession;
    hdr->reset         = resetDsMemEgrOamSession;
    hdr->destroy       = destroyDsMemEgrOamSession;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemEgrSrcPort");
    hdr->name          = "DsMemEgrSrcPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemEgrSrcPort;
    hdr->write         = writeDsMemEgrSrcPort;
    hdr->set           = setDsMemEgrSrcPort;
    hdr->fldSet        = fldSetDsMemEgrSrcPort;
    hdr->fldGet        = fldGetDsMemEgrSrcPort;
    hdr->print         = printDsMemEgrSrcPort;
    hdr->reset         = resetDsMemEgrSrcPort;
    hdr->destroy       = destroyDsMemEgrSrcPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemFlowColorStats");
    hdr->name          = "PacketEditDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemFlowColorStats;
    hdr->write         = writePacketEditDsMemFlowColorStats;
    hdr->set           = setPacketEditDsMemFlowColorStats;
    hdr->fldSet        = fldSetPacketEditDsMemFlowColorStats;
    hdr->fldGet        = fldGetPacketEditDsMemFlowColorStats;
    hdr->print         = printPacketEditDsMemFlowColorStats;
    hdr->reset         = resetPacketEditDsMemFlowColorStats;
    hdr->destroy       = destroyPacketEditDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemFlowPolice");
    hdr->name          = "PacketEditDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemFlowPolice;
    hdr->write         = writePacketEditDsMemFlowPolice;
    hdr->set           = setPacketEditDsMemFlowPolice;
    hdr->fldSet        = fldSetPacketEditDsMemFlowPolice;
    hdr->fldGet        = fldGetPacketEditDsMemFlowPolice;
    hdr->print         = printPacketEditDsMemFlowPolice;
    hdr->reset         = resetPacketEditDsMemFlowPolice;
    hdr->destroy       = destroyPacketEditDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemFlowPoliceCfg");
    hdr->name          = "PacketEditDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemFlowPoliceCfg;
    hdr->write         = writePacketEditDsMemFlowPoliceCfg;
    hdr->set           = setPacketEditDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetPacketEditDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetPacketEditDsMemFlowPoliceCfg;
    hdr->print         = printPacketEditDsMemFlowPoliceCfg;
    hdr->reset         = resetPacketEditDsMemFlowPoliceCfg;
    hdr->destroy       = destroyPacketEditDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostRoute");
    hdr->name          = "PacketEditDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostRoute;
    hdr->write         = writePacketEditDsMemHostRoute;
    hdr->set           = setPacketEditDsMemHostRoute;
    hdr->fldSet        = fldSetPacketEditDsMemHostRoute;
    hdr->fldGet        = fldGetPacketEditDsMemHostRoute;
    hdr->print         = printPacketEditDsMemHostRoute;
    hdr->reset         = resetPacketEditDsMemHostRoute;
    hdr->destroy       = destroyPacketEditDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostRouteLeft");
    hdr->name          = "PacketEditDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostRouteLeft;
    hdr->write         = writePacketEditDsMemHostRouteLeft;
    hdr->set           = setPacketEditDsMemHostRouteLeft;
    hdr->fldSet        = fldSetPacketEditDsMemHostRouteLeft;
    hdr->fldGet        = fldGetPacketEditDsMemHostRouteLeft;
    hdr->print         = printPacketEditDsMemHostRouteLeft;
    hdr->reset         = resetPacketEditDsMemHostRouteLeft;
    hdr->destroy       = destroyPacketEditDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostRouteLeftKey");
    hdr->name          = "PacketEditDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostRouteLeftKey;
    hdr->write         = writePacketEditDsMemHostRouteLeftKey;
    hdr->set           = setPacketEditDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetPacketEditDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetPacketEditDsMemHostRouteLeftKey;
    hdr->print         = printPacketEditDsMemHostRouteLeftKey;
    hdr->reset         = resetPacketEditDsMemHostRouteLeftKey;
    hdr->destroy       = destroyPacketEditDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostRouteLeftValid");
    hdr->name          = "PacketEditDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostRouteLeftValid;
    hdr->write         = writePacketEditDsMemHostRouteLeftValid;
    hdr->set           = setPacketEditDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetPacketEditDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetPacketEditDsMemHostRouteLeftValid;
    hdr->print         = printPacketEditDsMemHostRouteLeftValid;
    hdr->reset         = resetPacketEditDsMemHostRouteLeftValid;
    hdr->destroy       = destroyPacketEditDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostRouteRight");
    hdr->name          = "PacketEditDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostRouteRight;
    hdr->write         = writePacketEditDsMemHostRouteRight;
    hdr->set           = setPacketEditDsMemHostRouteRight;
    hdr->fldSet        = fldSetPacketEditDsMemHostRouteRight;
    hdr->fldGet        = fldGetPacketEditDsMemHostRouteRight;
    hdr->print         = printPacketEditDsMemHostRouteRight;
    hdr->reset         = resetPacketEditDsMemHostRouteRight;
    hdr->destroy       = destroyPacketEditDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostRouteRightKey");
    hdr->name          = "PacketEditDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostRouteRightKey;
    hdr->write         = writePacketEditDsMemHostRouteRightKey;
    hdr->set           = setPacketEditDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetPacketEditDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetPacketEditDsMemHostRouteRightKey;
    hdr->print         = printPacketEditDsMemHostRouteRightKey;
    hdr->reset         = resetPacketEditDsMemHostRouteRightKey;
    hdr->destroy       = destroyPacketEditDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostRouteRightValid");
    hdr->name          = "PacketEditDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostRouteRightValid;
    hdr->write         = writePacketEditDsMemHostRouteRightValid;
    hdr->set           = setPacketEditDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetPacketEditDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetPacketEditDsMemHostRouteRightValid;
    hdr->print         = printPacketEditDsMemHostRouteRightValid;
    hdr->reset         = resetPacketEditDsMemHostRouteRightValid;
    hdr->destroy       = destroyPacketEditDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostTsn");
    hdr->name          = "PacketEditDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostTsn;
    hdr->write         = writePacketEditDsMemHostTsn;
    hdr->set           = setPacketEditDsMemHostTsn;
    hdr->fldSet        = fldSetPacketEditDsMemHostTsn;
    hdr->fldGet        = fldGetPacketEditDsMemHostTsn;
    hdr->print         = printPacketEditDsMemHostTsn;
    hdr->reset         = resetPacketEditDsMemHostTsn;
    hdr->destroy       = destroyPacketEditDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostTsnLeft");
    hdr->name          = "PacketEditDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostTsnLeft;
    hdr->write         = writePacketEditDsMemHostTsnLeft;
    hdr->set           = setPacketEditDsMemHostTsnLeft;
    hdr->fldSet        = fldSetPacketEditDsMemHostTsnLeft;
    hdr->fldGet        = fldGetPacketEditDsMemHostTsnLeft;
    hdr->print         = printPacketEditDsMemHostTsnLeft;
    hdr->reset         = resetPacketEditDsMemHostTsnLeft;
    hdr->destroy       = destroyPacketEditDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemHostTsnRight");
    hdr->name          = "PacketEditDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemHostTsnRight;
    hdr->write         = writePacketEditDsMemHostTsnRight;
    hdr->set           = setPacketEditDsMemHostTsnRight;
    hdr->fldSet        = fldSetPacketEditDsMemHostTsnRight;
    hdr->fldGet        = fldGetPacketEditDsMemHostTsnRight;
    hdr->print         = printPacketEditDsMemHostTsnRight;
    hdr->reset         = resetPacketEditDsMemHostTsnRight;
    hdr->destroy       = destroyPacketEditDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemIndvRcvyCfg");
    hdr->name          = "PacketEditDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemIndvRcvyCfg;
    hdr->write         = writePacketEditDsMemIndvRcvyCfg;
    hdr->set           = setPacketEditDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetPacketEditDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetPacketEditDsMemIndvRcvyCfg;
    hdr->print         = printPacketEditDsMemIndvRcvyCfg;
    hdr->reset         = resetPacketEditDsMemIndvRcvyCfg;
    hdr->destroy       = destroyPacketEditDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemIndvRcvyCnt");
    hdr->name          = "PacketEditDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemIndvRcvyCnt;
    hdr->write         = writePacketEditDsMemIndvRcvyCnt;
    hdr->set           = setPacketEditDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetPacketEditDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetPacketEditDsMemIndvRcvyCnt;
    hdr->print         = printPacketEditDsMemIndvRcvyCnt;
    hdr->reset         = resetPacketEditDsMemIndvRcvyCnt;
    hdr->destroy       = destroyPacketEditDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemIndvRcvySeq");
    hdr->name          = "PacketEditDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemIndvRcvySeq;
    hdr->write         = writePacketEditDsMemIndvRcvySeq;
    hdr->set           = setPacketEditDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetPacketEditDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetPacketEditDsMemIndvRcvySeq;
    hdr->print         = printPacketEditDsMemIndvRcvySeq;
    hdr->reset         = resetPacketEditDsMemIndvRcvySeq;
    hdr->destroy       = destroyPacketEditDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemL3Mcast");
    hdr->name          = "DsMemL3Mcast";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000118;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemL3Mcast;
    hdr->write         = writeDsMemL3Mcast;
    hdr->set           = setDsMemL3Mcast;
    hdr->fldSet        = fldSetDsMemL3Mcast;
    hdr->fldGet        = fldGetDsMemL3Mcast;
    hdr->print         = printDsMemL3Mcast;
    hdr->reset         = resetDsMemL3Mcast;
    hdr->destroy       = destroyDsMemL3Mcast;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacAgingLeft");
    hdr->name          = "PacketEditDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacAgingLeft;
    hdr->write         = writePacketEditDsMemMacAgingLeft;
    hdr->set           = setPacketEditDsMemMacAgingLeft;
    hdr->fldSet        = fldSetPacketEditDsMemMacAgingLeft;
    hdr->fldGet        = fldGetPacketEditDsMemMacAgingLeft;
    hdr->print         = printPacketEditDsMemMacAgingLeft;
    hdr->reset         = resetPacketEditDsMemMacAgingLeft;
    hdr->destroy       = destroyPacketEditDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacAgingRight");
    hdr->name          = "PacketEditDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacAgingRight;
    hdr->write         = writePacketEditDsMemMacAgingRight;
    hdr->set           = setPacketEditDsMemMacAgingRight;
    hdr->fldSet        = fldSetPacketEditDsMemMacAgingRight;
    hdr->fldGet        = fldGetPacketEditDsMemMacAgingRight;
    hdr->print         = printPacketEditDsMemMacAgingRight;
    hdr->reset         = resetPacketEditDsMemMacAgingRight;
    hdr->destroy       = destroyPacketEditDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacKeyLeft");
    hdr->name          = "PacketEditDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacKeyLeft;
    hdr->write         = writePacketEditDsMemMacKeyLeft;
    hdr->set           = setPacketEditDsMemMacKeyLeft;
    hdr->fldSet        = fldSetPacketEditDsMemMacKeyLeft;
    hdr->fldGet        = fldGetPacketEditDsMemMacKeyLeft;
    hdr->print         = printPacketEditDsMemMacKeyLeft;
    hdr->reset         = resetPacketEditDsMemMacKeyLeft;
    hdr->destroy       = destroyPacketEditDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacKeyRight");
    hdr->name          = "PacketEditDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacKeyRight;
    hdr->write         = writePacketEditDsMemMacKeyRight;
    hdr->set           = setPacketEditDsMemMacKeyRight;
    hdr->fldSet        = fldSetPacketEditDsMemMacKeyRight;
    hdr->fldGet        = fldGetPacketEditDsMemMacKeyRight;
    hdr->print         = printPacketEditDsMemMacKeyRight;
    hdr->reset         = resetPacketEditDsMemMacKeyRight;
    hdr->destroy       = destroyPacketEditDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacLeft");
    hdr->name          = "PacketEditDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacLeft;
    hdr->write         = writePacketEditDsMemMacLeft;
    hdr->set           = setPacketEditDsMemMacLeft;
    hdr->fldSet        = fldSetPacketEditDsMemMacLeft;
    hdr->fldGet        = fldGetPacketEditDsMemMacLeft;
    hdr->print         = printPacketEditDsMemMacLeft;
    hdr->reset         = resetPacketEditDsMemMacLeft;
    hdr->destroy       = destroyPacketEditDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacRight");
    hdr->name          = "PacketEditDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000290;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacRight;
    hdr->write         = writePacketEditDsMemMacRight;
    hdr->set           = setPacketEditDsMemMacRight;
    hdr->fldSet        = fldSetPacketEditDsMemMacRight;
    hdr->fldGet        = fldGetPacketEditDsMemMacRight;
    hdr->print         = printPacketEditDsMemMacRight;
    hdr->reset         = resetPacketEditDsMemMacRight;
    hdr->destroy       = destroyPacketEditDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacStaticLeft");
    hdr->name          = "PacketEditDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacStaticLeft;
    hdr->write         = writePacketEditDsMemMacStaticLeft;
    hdr->set           = setPacketEditDsMemMacStaticLeft;
    hdr->fldSet        = fldSetPacketEditDsMemMacStaticLeft;
    hdr->fldGet        = fldGetPacketEditDsMemMacStaticLeft;
    hdr->print         = printPacketEditDsMemMacStaticLeft;
    hdr->reset         = resetPacketEditDsMemMacStaticLeft;
    hdr->destroy       = destroyPacketEditDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacStaticRight");
    hdr->name          = "PacketEditDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacStaticRight;
    hdr->write         = writePacketEditDsMemMacStaticRight;
    hdr->set           = setPacketEditDsMemMacStaticRight;
    hdr->fldSet        = fldSetPacketEditDsMemMacStaticRight;
    hdr->fldGet        = fldGetPacketEditDsMemMacStaticRight;
    hdr->print         = printPacketEditDsMemMacStaticRight;
    hdr->reset         = resetPacketEditDsMemMacStaticRight;
    hdr->destroy       = destroyPacketEditDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacTsn");
    hdr->name          = "PacketEditDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacTsn;
    hdr->write         = writePacketEditDsMemMacTsn;
    hdr->set           = setPacketEditDsMemMacTsn;
    hdr->fldSet        = fldSetPacketEditDsMemMacTsn;
    hdr->fldGet        = fldGetPacketEditDsMemMacTsn;
    hdr->print         = printPacketEditDsMemMacTsn;
    hdr->reset         = resetPacketEditDsMemMacTsn;
    hdr->destroy       = destroyPacketEditDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacTsnLeft");
    hdr->name          = "PacketEditDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacTsnLeft;
    hdr->write         = writePacketEditDsMemMacTsnLeft;
    hdr->set           = setPacketEditDsMemMacTsnLeft;
    hdr->fldSet        = fldSetPacketEditDsMemMacTsnLeft;
    hdr->fldGet        = fldGetPacketEditDsMemMacTsnLeft;
    hdr->print         = printPacketEditDsMemMacTsnLeft;
    hdr->reset         = resetPacketEditDsMemMacTsnLeft;
    hdr->destroy       = destroyPacketEditDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacTsnRight");
    hdr->name          = "PacketEditDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacTsnRight;
    hdr->write         = writePacketEditDsMemMacTsnRight;
    hdr->set           = setPacketEditDsMemMacTsnRight;
    hdr->fldSet        = fldSetPacketEditDsMemMacTsnRight;
    hdr->fldGet        = fldGetPacketEditDsMemMacTsnRight;
    hdr->print         = printPacketEditDsMemMacTsnRight;
    hdr->reset         = resetPacketEditDsMemMacTsnRight;
    hdr->destroy       = destroyPacketEditDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacValidLeft");
    hdr->name          = "PacketEditDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacValidLeft;
    hdr->write         = writePacketEditDsMemMacValidLeft;
    hdr->set           = setPacketEditDsMemMacValidLeft;
    hdr->fldSet        = fldSetPacketEditDsMemMacValidLeft;
    hdr->fldGet        = fldGetPacketEditDsMemMacValidLeft;
    hdr->print         = printPacketEditDsMemMacValidLeft;
    hdr->reset         = resetPacketEditDsMemMacValidLeft;
    hdr->destroy       = destroyPacketEditDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemMacValidRight");
    hdr->name          = "PacketEditDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000300;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemMacValidRight;
    hdr->write         = writePacketEditDsMemMacValidRight;
    hdr->set           = setPacketEditDsMemMacValidRight;
    hdr->fldSet        = fldSetPacketEditDsMemMacValidRight;
    hdr->fldGet        = fldGetPacketEditDsMemMacValidRight;
    hdr->print         = printPacketEditDsMemMacValidRight;
    hdr->reset         = resetPacketEditDsMemMacValidRight;
    hdr->destroy       = destroyPacketEditDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemNexthop");
    hdr->name          = "DsMemNexthop";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000188;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemNexthop;
    hdr->write         = writeDsMemNexthop;
    hdr->set           = setDsMemNexthop;
    hdr->fldSet        = fldSetDsMemNexthop;
    hdr->fldGet        = fldGetDsMemNexthop;
    hdr->print         = printDsMemNexthop;
    hdr->reset         = resetDsMemNexthop;
    hdr->destroy       = destroyDsMemNexthop;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemPortColorStats");
    hdr->name          = "PacketEditDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000320;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemPortColorStats;
    hdr->write         = writePacketEditDsMemPortColorStats;
    hdr->set           = setPacketEditDsMemPortColorStats;
    hdr->fldSet        = fldSetPacketEditDsMemPortColorStats;
    hdr->fldGet        = fldGetPacketEditDsMemPortColorStats;
    hdr->print         = printPacketEditDsMemPortColorStats;
    hdr->reset         = resetPacketEditDsMemPortColorStats;
    hdr->destroy       = destroyPacketEditDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemPortPolice");
    hdr->name          = "PacketEditDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000330;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemPortPolice;
    hdr->write         = writePacketEditDsMemPortPolice;
    hdr->set           = setPacketEditDsMemPortPolice;
    hdr->fldSet        = fldSetPacketEditDsMemPortPolice;
    hdr->fldGet        = fldGetPacketEditDsMemPortPolice;
    hdr->print         = printPacketEditDsMemPortPolice;
    hdr->reset         = resetPacketEditDsMemPortPolice;
    hdr->destroy       = destroyPacketEditDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemPortPoliceCfg");
    hdr->name          = "PacketEditDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000340;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemPortPoliceCfg;
    hdr->write         = writePacketEditDsMemPortPoliceCfg;
    hdr->set           = setPacketEditDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetPacketEditDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetPacketEditDsMemPortPoliceCfg;
    hdr->print         = printPacketEditDsMemPortPoliceCfg;
    hdr->reset         = resetPacketEditDsMemPortPoliceCfg;
    hdr->destroy       = destroyPacketEditDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemRouteTsn");
    hdr->name          = "PacketEditDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000350;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemRouteTsn;
    hdr->write         = writePacketEditDsMemRouteTsn;
    hdr->set           = setPacketEditDsMemRouteTsn;
    hdr->fldSet        = fldSetPacketEditDsMemRouteTsn;
    hdr->fldGet        = fldGetPacketEditDsMemRouteTsn;
    hdr->print         = printPacketEditDsMemRouteTsn;
    hdr->reset         = resetPacketEditDsMemRouteTsn;
    hdr->destroy       = destroyPacketEditDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemStreamRcvyCfg");
    hdr->name          = "PacketEditDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000360;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemStreamRcvyCfg;
    hdr->write         = writePacketEditDsMemStreamRcvyCfg;
    hdr->set           = setPacketEditDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetPacketEditDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetPacketEditDsMemStreamRcvyCfg;
    hdr->print         = printPacketEditDsMemStreamRcvyCfg;
    hdr->reset         = resetPacketEditDsMemStreamRcvyCfg;
    hdr->destroy       = destroyPacketEditDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemStreamRcvyCnt");
    hdr->name          = "PacketEditDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000370;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemStreamRcvyCnt;
    hdr->write         = writePacketEditDsMemStreamRcvyCnt;
    hdr->set           = setPacketEditDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetPacketEditDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetPacketEditDsMemStreamRcvyCnt;
    hdr->print         = printPacketEditDsMemStreamRcvyCnt;
    hdr->reset         = resetPacketEditDsMemStreamRcvyCnt;
    hdr->destroy       = destroyPacketEditDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditDsMemStreamRcvySeq");
    hdr->name          = "PacketEditDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000380;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditDsMemStreamRcvySeq;
    hdr->write         = writePacketEditDsMemStreamRcvySeq;
    hdr->set           = setPacketEditDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetPacketEditDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetPacketEditDsMemStreamRcvySeq;
    hdr->print         = printPacketEditDsMemStreamRcvySeq;
    hdr->reset         = resetPacketEditDsMemStreamRcvySeq;
    hdr->destroy       = destroyPacketEditDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegEgrPriorMap");
    hdr->name          = "DsRegEgrPriorMap";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c8;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegEgrPriorMap;
    hdr->write         = writeDsRegEgrPriorMap;
    hdr->set           = setDsRegEgrPriorMap;
    hdr->fldSet        = fldSetDsRegEgrPriorMap;
    hdr->fldGet        = fldGetDsRegEgrPriorMap;
    hdr->print         = printDsRegEgrPriorMap;
    hdr->reset         = resetDsRegEgrPriorMap;
    hdr->destroy       = destroyDsRegEgrPriorMap;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditMsgAdmInfo0");
    hdr->name          = "PacketEditMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0003a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditMsgAdmInfo0;
    hdr->write         = writePacketEditMsgAdmInfo0;
    hdr->set           = setPacketEditMsgAdmInfo0;
    hdr->fldSet        = fldSetPacketEditMsgAdmInfo0;
    hdr->fldGet        = fldGetPacketEditMsgAdmInfo0;
    hdr->print         = printPacketEditMsgAdmInfo0;
    hdr->reset         = resetPacketEditMsgAdmInfo0;
    hdr->destroy       = destroyPacketEditMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketEditTmpDsMemMac");
    hdr->name          = "PacketEditTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0003b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketEditTmpDsMemMac;
    hdr->write         = writePacketEditTmpDsMemMac;
    hdr->set           = setPacketEditTmpDsMemMac;
    hdr->fldSet        = fldSetPacketEditTmpDsMemMac;
    hdr->fldGet        = fldGetPacketEditTmpDsMemMac;
    hdr->print         = printPacketEditTmpDsMemMac;
    hdr->reset         = resetPacketEditTmpDsMemMac;
    hdr->destroy       = destroyPacketEditTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
