/*
 * Software Development Kit for Fisilink
 * @file: PacketProcess.c
 * @description: C language expression for PacketProcess module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/PacketProcessOpr.h>


int insertPacketProcessHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlMacLearn");
    hdr->name          = "CtlMacLearn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlMacLearn;
    hdr->write         = writeCtlMacLearn;
    hdr->set           = setCtlMacLearn;
    hdr->fldSet        = fldSetCtlMacLearn;
    hdr->fldGet        = fldGetCtlMacLearn;
    hdr->print         = printCtlMacLearn;
    hdr->reset         = resetCtlMacLearn;
    hdr->destroy       = destroyCtlMacLearn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlPktProcLog");
    hdr->name          = "CtlPktProcLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlPktProcLog;
    hdr->write         = writeCtlPktProcLog;
    hdr->set           = setCtlPktProcLog;
    hdr->fldSet        = fldSetCtlPktProcLog;
    hdr->fldGet        = fldGetCtlPktProcLog;
    hdr->print         = printCtlPktProcLog;
    hdr->reset         = resetCtlPktProcLog;
    hdr->destroy       = destroyCtlPktProcLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlPpGapConfig");
    hdr->name          = "CtlPpGapConfig";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlPpGapConfig;
    hdr->write         = writeCtlPpGapConfig;
    hdr->set           = setCtlPpGapConfig;
    hdr->fldSet        = fldSetCtlPpGapConfig;
    hdr->fldGet        = fldGetCtlPpGapConfig;
    hdr->print         = printCtlPpGapConfig;
    hdr->reset         = resetCtlPpGapConfig;
    hdr->destroy       = destroyCtlPpGapConfig;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlStormCntl");
    hdr->name          = "CtlStormCntl";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000018;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlStormCntl;
    hdr->write         = writeCtlStormCntl;
    hdr->set           = setCtlStormCntl;
    hdr->fldSet        = fldSetCtlStormCntl;
    hdr->fldGet        = fldGetCtlStormCntl;
    hdr->print         = printCtlStormCntl;
    hdr->reset         = resetCtlStormCntl;
    hdr->destroy       = destroyCtlStormCntl;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemAclTsn");
    hdr->name          = "PacketProcessDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemAclTsn;
    hdr->write         = writePacketProcessDsMemAclTsn;
    hdr->set           = setPacketProcessDsMemAclTsn;
    hdr->fldSet        = fldSetPacketProcessDsMemAclTsn;
    hdr->fldGet        = fldGetPacketProcessDsMemAclTsn;
    hdr->print         = printPacketProcessDsMemAclTsn;
    hdr->reset         = resetPacketProcessDsMemAclTsn;
    hdr->destroy       = destroyPacketProcessDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemCustomFdb");
    hdr->name          = "DsMemCustomFdb";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000028;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemCustomFdb;
    hdr->write         = writeDsMemCustomFdb;
    hdr->set           = setDsMemCustomFdb;
    hdr->fldSet        = fldSetDsMemCustomFdb;
    hdr->fldGet        = fldGetDsMemCustomFdb;
    hdr->print         = printDsMemCustomFdb;
    hdr->reset         = resetDsMemCustomFdb;
    hdr->destroy       = destroyDsMemCustomFdb;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemFlowColorStats");
    hdr->name          = "PacketProcessDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemFlowColorStats;
    hdr->write         = writePacketProcessDsMemFlowColorStats;
    hdr->set           = setPacketProcessDsMemFlowColorStats;
    hdr->fldSet        = fldSetPacketProcessDsMemFlowColorStats;
    hdr->fldGet        = fldGetPacketProcessDsMemFlowColorStats;
    hdr->print         = printPacketProcessDsMemFlowColorStats;
    hdr->reset         = resetPacketProcessDsMemFlowColorStats;
    hdr->destroy       = destroyPacketProcessDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemFlowPolice");
    hdr->name          = "PacketProcessDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemFlowPolice;
    hdr->write         = writePacketProcessDsMemFlowPolice;
    hdr->set           = setPacketProcessDsMemFlowPolice;
    hdr->fldSet        = fldSetPacketProcessDsMemFlowPolice;
    hdr->fldGet        = fldGetPacketProcessDsMemFlowPolice;
    hdr->print         = printPacketProcessDsMemFlowPolice;
    hdr->reset         = resetPacketProcessDsMemFlowPolice;
    hdr->destroy       = destroyPacketProcessDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemFlowPoliceCfg");
    hdr->name          = "PacketProcessDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000080;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemFlowPoliceCfg;
    hdr->write         = writePacketProcessDsMemFlowPoliceCfg;
    hdr->set           = setPacketProcessDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetPacketProcessDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetPacketProcessDsMemFlowPoliceCfg;
    hdr->print         = printPacketProcessDsMemFlowPoliceCfg;
    hdr->reset         = resetPacketProcessDsMemFlowPoliceCfg;
    hdr->destroy       = destroyPacketProcessDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostRoute");
    hdr->name          = "PacketProcessDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostRoute;
    hdr->write         = writePacketProcessDsMemHostRoute;
    hdr->set           = setPacketProcessDsMemHostRoute;
    hdr->fldSet        = fldSetPacketProcessDsMemHostRoute;
    hdr->fldGet        = fldGetPacketProcessDsMemHostRoute;
    hdr->print         = printPacketProcessDsMemHostRoute;
    hdr->reset         = resetPacketProcessDsMemHostRoute;
    hdr->destroy       = destroyPacketProcessDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostRouteLeft");
    hdr->name          = "PacketProcessDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostRouteLeft;
    hdr->write         = writePacketProcessDsMemHostRouteLeft;
    hdr->set           = setPacketProcessDsMemHostRouteLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemHostRouteLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemHostRouteLeft;
    hdr->print         = printPacketProcessDsMemHostRouteLeft;
    hdr->reset         = resetPacketProcessDsMemHostRouteLeft;
    hdr->destroy       = destroyPacketProcessDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostRouteLeftKey");
    hdr->name          = "PacketProcessDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostRouteLeftKey;
    hdr->write         = writePacketProcessDsMemHostRouteLeftKey;
    hdr->set           = setPacketProcessDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetPacketProcessDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetPacketProcessDsMemHostRouteLeftKey;
    hdr->print         = printPacketProcessDsMemHostRouteLeftKey;
    hdr->reset         = resetPacketProcessDsMemHostRouteLeftKey;
    hdr->destroy       = destroyPacketProcessDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostRouteLeftValid");
    hdr->name          = "PacketProcessDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostRouteLeftValid;
    hdr->write         = writePacketProcessDsMemHostRouteLeftValid;
    hdr->set           = setPacketProcessDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetPacketProcessDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetPacketProcessDsMemHostRouteLeftValid;
    hdr->print         = printPacketProcessDsMemHostRouteLeftValid;
    hdr->reset         = resetPacketProcessDsMemHostRouteLeftValid;
    hdr->destroy       = destroyPacketProcessDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostRouteRight");
    hdr->name          = "PacketProcessDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostRouteRight;
    hdr->write         = writePacketProcessDsMemHostRouteRight;
    hdr->set           = setPacketProcessDsMemHostRouteRight;
    hdr->fldSet        = fldSetPacketProcessDsMemHostRouteRight;
    hdr->fldGet        = fldGetPacketProcessDsMemHostRouteRight;
    hdr->print         = printPacketProcessDsMemHostRouteRight;
    hdr->reset         = resetPacketProcessDsMemHostRouteRight;
    hdr->destroy       = destroyPacketProcessDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostRouteRightKey");
    hdr->name          = "PacketProcessDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostRouteRightKey;
    hdr->write         = writePacketProcessDsMemHostRouteRightKey;
    hdr->set           = setPacketProcessDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetPacketProcessDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetPacketProcessDsMemHostRouteRightKey;
    hdr->print         = printPacketProcessDsMemHostRouteRightKey;
    hdr->reset         = resetPacketProcessDsMemHostRouteRightKey;
    hdr->destroy       = destroyPacketProcessDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostRouteRightValid");
    hdr->name          = "PacketProcessDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostRouteRightValid;
    hdr->write         = writePacketProcessDsMemHostRouteRightValid;
    hdr->set           = setPacketProcessDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetPacketProcessDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetPacketProcessDsMemHostRouteRightValid;
    hdr->print         = printPacketProcessDsMemHostRouteRightValid;
    hdr->reset         = resetPacketProcessDsMemHostRouteRightValid;
    hdr->destroy       = destroyPacketProcessDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostTsn");
    hdr->name          = "PacketProcessDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostTsn;
    hdr->write         = writePacketProcessDsMemHostTsn;
    hdr->set           = setPacketProcessDsMemHostTsn;
    hdr->fldSet        = fldSetPacketProcessDsMemHostTsn;
    hdr->fldGet        = fldGetPacketProcessDsMemHostTsn;
    hdr->print         = printPacketProcessDsMemHostTsn;
    hdr->reset         = resetPacketProcessDsMemHostTsn;
    hdr->destroy       = destroyPacketProcessDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostTsnLeft");
    hdr->name          = "PacketProcessDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostTsnLeft;
    hdr->write         = writePacketProcessDsMemHostTsnLeft;
    hdr->set           = setPacketProcessDsMemHostTsnLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemHostTsnLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemHostTsnLeft;
    hdr->print         = printPacketProcessDsMemHostTsnLeft;
    hdr->reset         = resetPacketProcessDsMemHostTsnLeft;
    hdr->destroy       = destroyPacketProcessDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemHostTsnRight");
    hdr->name          = "PacketProcessDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemHostTsnRight;
    hdr->write         = writePacketProcessDsMemHostTsnRight;
    hdr->set           = setPacketProcessDsMemHostTsnRight;
    hdr->fldSet        = fldSetPacketProcessDsMemHostTsnRight;
    hdr->fldGet        = fldGetPacketProcessDsMemHostTsnRight;
    hdr->print         = printPacketProcessDsMemHostTsnRight;
    hdr->reset         = resetPacketProcessDsMemHostTsnRight;
    hdr->destroy       = destroyPacketProcessDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemIndvRcvyCfg");
    hdr->name          = "PacketProcessDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemIndvRcvyCfg;
    hdr->write         = writePacketProcessDsMemIndvRcvyCfg;
    hdr->set           = setPacketProcessDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetPacketProcessDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetPacketProcessDsMemIndvRcvyCfg;
    hdr->print         = printPacketProcessDsMemIndvRcvyCfg;
    hdr->reset         = resetPacketProcessDsMemIndvRcvyCfg;
    hdr->destroy       = destroyPacketProcessDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemIndvRcvyCnt");
    hdr->name          = "PacketProcessDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemIndvRcvyCnt;
    hdr->write         = writePacketProcessDsMemIndvRcvyCnt;
    hdr->set           = setPacketProcessDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetPacketProcessDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetPacketProcessDsMemIndvRcvyCnt;
    hdr->print         = printPacketProcessDsMemIndvRcvyCnt;
    hdr->reset         = resetPacketProcessDsMemIndvRcvyCnt;
    hdr->destroy       = destroyPacketProcessDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemIndvRcvySeq");
    hdr->name          = "PacketProcessDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemIndvRcvySeq;
    hdr->write         = writePacketProcessDsMemIndvRcvySeq;
    hdr->set           = setPacketProcessDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetPacketProcessDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetPacketProcessDsMemIndvRcvySeq;
    hdr->print         = printPacketProcessDsMemIndvRcvySeq;
    hdr->reset         = resetPacketProcessDsMemIndvRcvySeq;
    hdr->destroy       = destroyPacketProcessDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMac");
    hdr->name          = "DsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMac;
    hdr->write         = writeDsMemMac;
    hdr->set           = setDsMemMac;
    hdr->fldSet        = fldSetDsMemMac;
    hdr->fldGet        = fldGetDsMemMac;
    hdr->print         = printDsMemMac;
    hdr->reset         = resetDsMemMac;
    hdr->destroy       = destroyDsMemMac;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacAgingLeft");
    hdr->name          = "PacketProcessDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacAgingLeft;
    hdr->write         = writePacketProcessDsMemMacAgingLeft;
    hdr->set           = setPacketProcessDsMemMacAgingLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemMacAgingLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemMacAgingLeft;
    hdr->print         = printPacketProcessDsMemMacAgingLeft;
    hdr->reset         = resetPacketProcessDsMemMacAgingLeft;
    hdr->destroy       = destroyPacketProcessDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacAgingRight");
    hdr->name          = "PacketProcessDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacAgingRight;
    hdr->write         = writePacketProcessDsMemMacAgingRight;
    hdr->set           = setPacketProcessDsMemMacAgingRight;
    hdr->fldSet        = fldSetPacketProcessDsMemMacAgingRight;
    hdr->fldGet        = fldGetPacketProcessDsMemMacAgingRight;
    hdr->print         = printPacketProcessDsMemMacAgingRight;
    hdr->reset         = resetPacketProcessDsMemMacAgingRight;
    hdr->destroy       = destroyPacketProcessDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacKeyLeft");
    hdr->name          = "PacketProcessDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacKeyLeft;
    hdr->write         = writePacketProcessDsMemMacKeyLeft;
    hdr->set           = setPacketProcessDsMemMacKeyLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemMacKeyLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemMacKeyLeft;
    hdr->print         = printPacketProcessDsMemMacKeyLeft;
    hdr->reset         = resetPacketProcessDsMemMacKeyLeft;
    hdr->destroy       = destroyPacketProcessDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacKeyRight");
    hdr->name          = "PacketProcessDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacKeyRight;
    hdr->write         = writePacketProcessDsMemMacKeyRight;
    hdr->set           = setPacketProcessDsMemMacKeyRight;
    hdr->fldSet        = fldSetPacketProcessDsMemMacKeyRight;
    hdr->fldGet        = fldGetPacketProcessDsMemMacKeyRight;
    hdr->print         = printPacketProcessDsMemMacKeyRight;
    hdr->reset         = resetPacketProcessDsMemMacKeyRight;
    hdr->destroy       = destroyPacketProcessDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacLeft");
    hdr->name          = "PacketProcessDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacLeft;
    hdr->write         = writePacketProcessDsMemMacLeft;
    hdr->set           = setPacketProcessDsMemMacLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemMacLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemMacLeft;
    hdr->print         = printPacketProcessDsMemMacLeft;
    hdr->reset         = resetPacketProcessDsMemMacLeft;
    hdr->destroy       = destroyPacketProcessDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacRight");
    hdr->name          = "PacketProcessDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacRight;
    hdr->write         = writePacketProcessDsMemMacRight;
    hdr->set           = setPacketProcessDsMemMacRight;
    hdr->fldSet        = fldSetPacketProcessDsMemMacRight;
    hdr->fldGet        = fldGetPacketProcessDsMemMacRight;
    hdr->print         = printPacketProcessDsMemMacRight;
    hdr->reset         = resetPacketProcessDsMemMacRight;
    hdr->destroy       = destroyPacketProcessDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacStaticLeft");
    hdr->name          = "PacketProcessDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacStaticLeft;
    hdr->write         = writePacketProcessDsMemMacStaticLeft;
    hdr->set           = setPacketProcessDsMemMacStaticLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemMacStaticLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemMacStaticLeft;
    hdr->print         = printPacketProcessDsMemMacStaticLeft;
    hdr->reset         = resetPacketProcessDsMemMacStaticLeft;
    hdr->destroy       = destroyPacketProcessDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacStaticRight");
    hdr->name          = "PacketProcessDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacStaticRight;
    hdr->write         = writePacketProcessDsMemMacStaticRight;
    hdr->set           = setPacketProcessDsMemMacStaticRight;
    hdr->fldSet        = fldSetPacketProcessDsMemMacStaticRight;
    hdr->fldGet        = fldGetPacketProcessDsMemMacStaticRight;
    hdr->print         = printPacketProcessDsMemMacStaticRight;
    hdr->reset         = resetPacketProcessDsMemMacStaticRight;
    hdr->destroy       = destroyPacketProcessDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacTsn");
    hdr->name          = "PacketProcessDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f8;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacTsn;
    hdr->write         = writePacketProcessDsMemMacTsn;
    hdr->set           = setPacketProcessDsMemMacTsn;
    hdr->fldSet        = fldSetPacketProcessDsMemMacTsn;
    hdr->fldGet        = fldGetPacketProcessDsMemMacTsn;
    hdr->print         = printPacketProcessDsMemMacTsn;
    hdr->reset         = resetPacketProcessDsMemMacTsn;
    hdr->destroy       = destroyPacketProcessDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacTsnLeft");
    hdr->name          = "PacketProcessDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacTsnLeft;
    hdr->write         = writePacketProcessDsMemMacTsnLeft;
    hdr->set           = setPacketProcessDsMemMacTsnLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemMacTsnLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemMacTsnLeft;
    hdr->print         = printPacketProcessDsMemMacTsnLeft;
    hdr->reset         = resetPacketProcessDsMemMacTsnLeft;
    hdr->destroy       = destroyPacketProcessDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacTsnRight");
    hdr->name          = "PacketProcessDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacTsnRight;
    hdr->write         = writePacketProcessDsMemMacTsnRight;
    hdr->set           = setPacketProcessDsMemMacTsnRight;
    hdr->fldSet        = fldSetPacketProcessDsMemMacTsnRight;
    hdr->fldGet        = fldGetPacketProcessDsMemMacTsnRight;
    hdr->print         = printPacketProcessDsMemMacTsnRight;
    hdr->reset         = resetPacketProcessDsMemMacTsnRight;
    hdr->destroy       = destroyPacketProcessDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacValidLeft");
    hdr->name          = "PacketProcessDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacValidLeft;
    hdr->write         = writePacketProcessDsMemMacValidLeft;
    hdr->set           = setPacketProcessDsMemMacValidLeft;
    hdr->fldSet        = fldSetPacketProcessDsMemMacValidLeft;
    hdr->fldGet        = fldGetPacketProcessDsMemMacValidLeft;
    hdr->print         = printPacketProcessDsMemMacValidLeft;
    hdr->reset         = resetPacketProcessDsMemMacValidLeft;
    hdr->destroy       = destroyPacketProcessDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemMacValidRight");
    hdr->name          = "PacketProcessDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemMacValidRight;
    hdr->write         = writePacketProcessDsMemMacValidRight;
    hdr->set           = setPacketProcessDsMemMacValidRight;
    hdr->fldSet        = fldSetPacketProcessDsMemMacValidRight;
    hdr->fldGet        = fldGetPacketProcessDsMemMacValidRight;
    hdr->print         = printPacketProcessDsMemMacValidRight;
    hdr->reset         = resetPacketProcessDsMemMacValidRight;
    hdr->destroy       = destroyPacketProcessDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemPortColorStats");
    hdr->name          = "PacketProcessDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemPortColorStats;
    hdr->write         = writePacketProcessDsMemPortColorStats;
    hdr->set           = setPacketProcessDsMemPortColorStats;
    hdr->fldSet        = fldSetPacketProcessDsMemPortColorStats;
    hdr->fldGet        = fldGetPacketProcessDsMemPortColorStats;
    hdr->print         = printPacketProcessDsMemPortColorStats;
    hdr->reset         = resetPacketProcessDsMemPortColorStats;
    hdr->destroy       = destroyPacketProcessDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemPortPolice");
    hdr->name          = "PacketProcessDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemPortPolice;
    hdr->write         = writePacketProcessDsMemPortPolice;
    hdr->set           = setPacketProcessDsMemPortPolice;
    hdr->fldSet        = fldSetPacketProcessDsMemPortPolice;
    hdr->fldGet        = fldGetPacketProcessDsMemPortPolice;
    hdr->print         = printPacketProcessDsMemPortPolice;
    hdr->reset         = resetPacketProcessDsMemPortPolice;
    hdr->destroy       = destroyPacketProcessDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemPortPoliceCfg");
    hdr->name          = "PacketProcessDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemPortPoliceCfg;
    hdr->write         = writePacketProcessDsMemPortPoliceCfg;
    hdr->set           = setPacketProcessDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetPacketProcessDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetPacketProcessDsMemPortPoliceCfg;
    hdr->print         = printPacketProcessDsMemPortPoliceCfg;
    hdr->reset         = resetPacketProcessDsMemPortPoliceCfg;
    hdr->destroy       = destroyPacketProcessDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemRoute");
    hdr->name          = "DsMemRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000138;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemRoute;
    hdr->write         = writeDsMemRoute;
    hdr->set           = setDsMemRoute;
    hdr->fldSet        = fldSetDsMemRoute;
    hdr->fldGet        = fldGetDsMemRoute;
    hdr->print         = printDsMemRoute;
    hdr->reset         = resetDsMemRoute;
    hdr->destroy       = destroyDsMemRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemRouteTsn");
    hdr->name          = "PacketProcessDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemRouteTsn;
    hdr->write         = writePacketProcessDsMemRouteTsn;
    hdr->set           = setPacketProcessDsMemRouteTsn;
    hdr->fldSet        = fldSetPacketProcessDsMemRouteTsn;
    hdr->fldGet        = fldGetPacketProcessDsMemRouteTsn;
    hdr->print         = printPacketProcessDsMemRouteTsn;
    hdr->reset         = resetPacketProcessDsMemRouteTsn;
    hdr->destroy       = destroyPacketProcessDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemStorm");
    hdr->name          = "DsMemStorm";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000148;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemStorm;
    hdr->write         = writeDsMemStorm;
    hdr->set           = setDsMemStorm;
    hdr->fldSet        = fldSetDsMemStorm;
    hdr->fldGet        = fldGetDsMemStorm;
    hdr->print         = printDsMemStorm;
    hdr->reset         = resetDsMemStorm;
    hdr->destroy       = destroyDsMemStorm;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemStormCtrl");
    hdr->name          = "DsMemStormCtrl";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemStormCtrl;
    hdr->write         = writeDsMemStormCtrl;
    hdr->set           = setDsMemStormCtrl;
    hdr->fldSet        = fldSetDsMemStormCtrl;
    hdr->fldGet        = fldGetDsMemStormCtrl;
    hdr->print         = printDsMemStormCtrl;
    hdr->reset         = resetDsMemStormCtrl;
    hdr->destroy       = destroyDsMemStormCtrl;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemStreamRcvyCfg");
    hdr->name          = "PacketProcessDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemStreamRcvyCfg;
    hdr->write         = writePacketProcessDsMemStreamRcvyCfg;
    hdr->set           = setPacketProcessDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetPacketProcessDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetPacketProcessDsMemStreamRcvyCfg;
    hdr->print         = printPacketProcessDsMemStreamRcvyCfg;
    hdr->reset         = resetPacketProcessDsMemStreamRcvyCfg;
    hdr->destroy       = destroyPacketProcessDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemStreamRcvyCnt");
    hdr->name          = "PacketProcessDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemStreamRcvyCnt;
    hdr->write         = writePacketProcessDsMemStreamRcvyCnt;
    hdr->set           = setPacketProcessDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetPacketProcessDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetPacketProcessDsMemStreamRcvyCnt;
    hdr->print         = printPacketProcessDsMemStreamRcvyCnt;
    hdr->reset         = resetPacketProcessDsMemStreamRcvyCnt;
    hdr->destroy       = destroyPacketProcessDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessDsMemStreamRcvySeq");
    hdr->name          = "PacketProcessDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessDsMemStreamRcvySeq;
    hdr->write         = writePacketProcessDsMemStreamRcvySeq;
    hdr->set           = setPacketProcessDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetPacketProcessDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetPacketProcessDsMemStreamRcvySeq;
    hdr->print         = printPacketProcessDsMemStreamRcvySeq;
    hdr->reset         = resetPacketProcessDsMemStreamRcvySeq;
    hdr->destroy       = destroyPacketProcessDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegPortLearnCtrl");
    hdr->name          = "DsRegPortLearnCtrl";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegPortLearnCtrl;
    hdr->write         = writeDsRegPortLearnCtrl;
    hdr->set           = setDsRegPortLearnCtrl;
    hdr->fldSet        = fldSetDsRegPortLearnCtrl;
    hdr->fldGet        = fldGetDsRegPortLearnCtrl;
    hdr->print         = printDsRegPortLearnCtrl;
    hdr->reset         = resetDsRegPortLearnCtrl;
    hdr->destroy       = destroyDsRegPortLearnCtrl;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegPortLearnNum");
    hdr->name          = "DsRegPortLearnNum";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000178;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegPortLearnNum;
    hdr->write         = writeDsRegPortLearnNum;
    hdr->set           = setDsRegPortLearnNum;
    hdr->fldSet        = fldSetDsRegPortLearnNum;
    hdr->fldGet        = fldGetDsRegPortLearnNum;
    hdr->print         = printDsRegPortLearnNum;
    hdr->reset         = resetDsRegPortLearnNum;
    hdr->destroy       = destroyDsRegPortLearnNum;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessMsgAdmInfo0");
    hdr->name          = "PacketProcessMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000300;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessMsgAdmInfo0;
    hdr->write         = writePacketProcessMsgAdmInfo0;
    hdr->set           = setPacketProcessMsgAdmInfo0;
    hdr->fldSet        = fldSetPacketProcessMsgAdmInfo0;
    hdr->fldGet        = fldGetPacketProcessMsgAdmInfo0;
    hdr->print         = printPacketProcessMsgAdmInfo0;
    hdr->reset         = resetPacketProcessMsgAdmInfo0;
    hdr->destroy       = destroyPacketProcessMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("PacketProcessTmpDsMemMac");
    hdr->name          = "PacketProcessTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000310;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readPacketProcessTmpDsMemMac;
    hdr->write         = writePacketProcessTmpDsMemMac;
    hdr->set           = setPacketProcessTmpDsMemMac;
    hdr->fldSet        = fldSetPacketProcessTmpDsMemMac;
    hdr->fldGet        = fldGetPacketProcessTmpDsMemMac;
    hdr->print         = printPacketProcessTmpDsMemMac;
    hdr->reset         = resetPacketProcessTmpDsMemMac;
    hdr->destroy       = destroyPacketProcessTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
