/*
 * Software Development Kit for Fisilink
 * @file: Redundancy.c
 * @description: C language expression for Redundancy module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/RedundancyOpr.h>


int insertRedundancyHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlRcvy");
    hdr->name          = "CtlRcvy";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlRcvy;
    hdr->write         = writeCtlRcvy;
    hdr->set           = setCtlRcvy;
    hdr->fldSet        = fldSetCtlRcvy;
    hdr->fldGet        = fldGetCtlRcvy;
    hdr->print         = printCtlRcvy;
    hdr->reset         = resetCtlRcvy;
    hdr->destroy       = destroyCtlRcvy;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlRcvyLog");
    hdr->name          = "CtlRcvyLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlRcvyLog;
    hdr->write         = writeCtlRcvyLog;
    hdr->set           = setCtlRcvyLog;
    hdr->fldSet        = fldSetCtlRcvyLog;
    hdr->fldGet        = fldGetCtlRcvyLog;
    hdr->print         = printCtlRcvyLog;
    hdr->reset         = resetCtlRcvyLog;
    hdr->destroy       = destroyCtlRcvyLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemAclTsn");
    hdr->name          = "RedundancyDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemAclTsn;
    hdr->write         = writeRedundancyDsMemAclTsn;
    hdr->set           = setRedundancyDsMemAclTsn;
    hdr->fldSet        = fldSetRedundancyDsMemAclTsn;
    hdr->fldGet        = fldGetRedundancyDsMemAclTsn;
    hdr->print         = printRedundancyDsMemAclTsn;
    hdr->reset         = resetRedundancyDsMemAclTsn;
    hdr->destroy       = destroyRedundancyDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemFlowColorStats");
    hdr->name          = "RedundancyDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemFlowColorStats;
    hdr->write         = writeRedundancyDsMemFlowColorStats;
    hdr->set           = setRedundancyDsMemFlowColorStats;
    hdr->fldSet        = fldSetRedundancyDsMemFlowColorStats;
    hdr->fldGet        = fldGetRedundancyDsMemFlowColorStats;
    hdr->print         = printRedundancyDsMemFlowColorStats;
    hdr->reset         = resetRedundancyDsMemFlowColorStats;
    hdr->destroy       = destroyRedundancyDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemFlowPolice");
    hdr->name          = "RedundancyDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemFlowPolice;
    hdr->write         = writeRedundancyDsMemFlowPolice;
    hdr->set           = setRedundancyDsMemFlowPolice;
    hdr->fldSet        = fldSetRedundancyDsMemFlowPolice;
    hdr->fldGet        = fldGetRedundancyDsMemFlowPolice;
    hdr->print         = printRedundancyDsMemFlowPolice;
    hdr->reset         = resetRedundancyDsMemFlowPolice;
    hdr->destroy       = destroyRedundancyDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemFlowPoliceCfg");
    hdr->name          = "RedundancyDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000050;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemFlowPoliceCfg;
    hdr->write         = writeRedundancyDsMemFlowPoliceCfg;
    hdr->set           = setRedundancyDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetRedundancyDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetRedundancyDsMemFlowPoliceCfg;
    hdr->print         = printRedundancyDsMemFlowPoliceCfg;
    hdr->reset         = resetRedundancyDsMemFlowPoliceCfg;
    hdr->destroy       = destroyRedundancyDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemHandle2StreamId");
    hdr->name          = "DsMemHandle2StreamId";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemHandle2StreamId;
    hdr->write         = writeDsMemHandle2StreamId;
    hdr->set           = setDsMemHandle2StreamId;
    hdr->fldSet        = fldSetDsMemHandle2StreamId;
    hdr->fldGet        = fldGetDsMemHandle2StreamId;
    hdr->print         = printDsMemHandle2StreamId;
    hdr->reset         = resetDsMemHandle2StreamId;
    hdr->destroy       = destroyDsMemHandle2StreamId;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostRoute");
    hdr->name          = "RedundancyDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostRoute;
    hdr->write         = writeRedundancyDsMemHostRoute;
    hdr->set           = setRedundancyDsMemHostRoute;
    hdr->fldSet        = fldSetRedundancyDsMemHostRoute;
    hdr->fldGet        = fldGetRedundancyDsMemHostRoute;
    hdr->print         = printRedundancyDsMemHostRoute;
    hdr->reset         = resetRedundancyDsMemHostRoute;
    hdr->destroy       = destroyRedundancyDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostRouteLeft");
    hdr->name          = "RedundancyDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000080;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostRouteLeft;
    hdr->write         = writeRedundancyDsMemHostRouteLeft;
    hdr->set           = setRedundancyDsMemHostRouteLeft;
    hdr->fldSet        = fldSetRedundancyDsMemHostRouteLeft;
    hdr->fldGet        = fldGetRedundancyDsMemHostRouteLeft;
    hdr->print         = printRedundancyDsMemHostRouteLeft;
    hdr->reset         = resetRedundancyDsMemHostRouteLeft;
    hdr->destroy       = destroyRedundancyDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostRouteLeftKey");
    hdr->name          = "RedundancyDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostRouteLeftKey;
    hdr->write         = writeRedundancyDsMemHostRouteLeftKey;
    hdr->set           = setRedundancyDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetRedundancyDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetRedundancyDsMemHostRouteLeftKey;
    hdr->print         = printRedundancyDsMemHostRouteLeftKey;
    hdr->reset         = resetRedundancyDsMemHostRouteLeftKey;
    hdr->destroy       = destroyRedundancyDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostRouteLeftValid");
    hdr->name          = "RedundancyDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostRouteLeftValid;
    hdr->write         = writeRedundancyDsMemHostRouteLeftValid;
    hdr->set           = setRedundancyDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetRedundancyDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetRedundancyDsMemHostRouteLeftValid;
    hdr->print         = printRedundancyDsMemHostRouteLeftValid;
    hdr->reset         = resetRedundancyDsMemHostRouteLeftValid;
    hdr->destroy       = destroyRedundancyDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostRouteRight");
    hdr->name          = "RedundancyDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostRouteRight;
    hdr->write         = writeRedundancyDsMemHostRouteRight;
    hdr->set           = setRedundancyDsMemHostRouteRight;
    hdr->fldSet        = fldSetRedundancyDsMemHostRouteRight;
    hdr->fldGet        = fldGetRedundancyDsMemHostRouteRight;
    hdr->print         = printRedundancyDsMemHostRouteRight;
    hdr->reset         = resetRedundancyDsMemHostRouteRight;
    hdr->destroy       = destroyRedundancyDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostRouteRightKey");
    hdr->name          = "RedundancyDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostRouteRightKey;
    hdr->write         = writeRedundancyDsMemHostRouteRightKey;
    hdr->set           = setRedundancyDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetRedundancyDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetRedundancyDsMemHostRouteRightKey;
    hdr->print         = printRedundancyDsMemHostRouteRightKey;
    hdr->reset         = resetRedundancyDsMemHostRouteRightKey;
    hdr->destroy       = destroyRedundancyDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostRouteRightValid");
    hdr->name          = "RedundancyDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostRouteRightValid;
    hdr->write         = writeRedundancyDsMemHostRouteRightValid;
    hdr->set           = setRedundancyDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetRedundancyDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetRedundancyDsMemHostRouteRightValid;
    hdr->print         = printRedundancyDsMemHostRouteRightValid;
    hdr->reset         = resetRedundancyDsMemHostRouteRightValid;
    hdr->destroy       = destroyRedundancyDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostTsn");
    hdr->name          = "RedundancyDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostTsn;
    hdr->write         = writeRedundancyDsMemHostTsn;
    hdr->set           = setRedundancyDsMemHostTsn;
    hdr->fldSet        = fldSetRedundancyDsMemHostTsn;
    hdr->fldGet        = fldGetRedundancyDsMemHostTsn;
    hdr->print         = printRedundancyDsMemHostTsn;
    hdr->reset         = resetRedundancyDsMemHostTsn;
    hdr->destroy       = destroyRedundancyDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostTsnLeft");
    hdr->name          = "RedundancyDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostTsnLeft;
    hdr->write         = writeRedundancyDsMemHostTsnLeft;
    hdr->set           = setRedundancyDsMemHostTsnLeft;
    hdr->fldSet        = fldSetRedundancyDsMemHostTsnLeft;
    hdr->fldGet        = fldGetRedundancyDsMemHostTsnLeft;
    hdr->print         = printRedundancyDsMemHostTsnLeft;
    hdr->reset         = resetRedundancyDsMemHostTsnLeft;
    hdr->destroy       = destroyRedundancyDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemHostTsnRight");
    hdr->name          = "RedundancyDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemHostTsnRight;
    hdr->write         = writeRedundancyDsMemHostTsnRight;
    hdr->set           = setRedundancyDsMemHostTsnRight;
    hdr->fldSet        = fldSetRedundancyDsMemHostTsnRight;
    hdr->fldGet        = fldGetRedundancyDsMemHostTsnRight;
    hdr->print         = printRedundancyDsMemHostTsnRight;
    hdr->reset         = resetRedundancyDsMemHostTsnRight;
    hdr->destroy       = destroyRedundancyDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemIndvRcvyCfg");
    hdr->name          = "RedundancyDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000088;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemIndvRcvyCfg;
    hdr->write         = writeRedundancyDsMemIndvRcvyCfg;
    hdr->set           = setRedundancyDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetRedundancyDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetRedundancyDsMemIndvRcvyCfg;
    hdr->print         = printRedundancyDsMemIndvRcvyCfg;
    hdr->reset         = resetRedundancyDsMemIndvRcvyCfg;
    hdr->destroy       = destroyRedundancyDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemIndvRcvyCnt");
    hdr->name          = "RedundancyDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemIndvRcvyCnt;
    hdr->write         = writeRedundancyDsMemIndvRcvyCnt;
    hdr->set           = setRedundancyDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetRedundancyDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetRedundancyDsMemIndvRcvyCnt;
    hdr->print         = printRedundancyDsMemIndvRcvyCnt;
    hdr->reset         = resetRedundancyDsMemIndvRcvyCnt;
    hdr->destroy       = destroyRedundancyDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemIndvRcvySeq");
    hdr->name          = "RedundancyDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000098;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemIndvRcvySeq;
    hdr->write         = writeRedundancyDsMemIndvRcvySeq;
    hdr->set           = setRedundancyDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetRedundancyDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetRedundancyDsMemIndvRcvySeq;
    hdr->print         = printRedundancyDsMemIndvRcvySeq;
    hdr->reset         = resetRedundancyDsMemIndvRcvySeq;
    hdr->destroy       = destroyRedundancyDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacAgingLeft");
    hdr->name          = "RedundancyDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacAgingLeft;
    hdr->write         = writeRedundancyDsMemMacAgingLeft;
    hdr->set           = setRedundancyDsMemMacAgingLeft;
    hdr->fldSet        = fldSetRedundancyDsMemMacAgingLeft;
    hdr->fldGet        = fldGetRedundancyDsMemMacAgingLeft;
    hdr->print         = printRedundancyDsMemMacAgingLeft;
    hdr->reset         = resetRedundancyDsMemMacAgingLeft;
    hdr->destroy       = destroyRedundancyDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacAgingRight");
    hdr->name          = "RedundancyDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacAgingRight;
    hdr->write         = writeRedundancyDsMemMacAgingRight;
    hdr->set           = setRedundancyDsMemMacAgingRight;
    hdr->fldSet        = fldSetRedundancyDsMemMacAgingRight;
    hdr->fldGet        = fldGetRedundancyDsMemMacAgingRight;
    hdr->print         = printRedundancyDsMemMacAgingRight;
    hdr->reset         = resetRedundancyDsMemMacAgingRight;
    hdr->destroy       = destroyRedundancyDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacKeyLeft");
    hdr->name          = "RedundancyDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacKeyLeft;
    hdr->write         = writeRedundancyDsMemMacKeyLeft;
    hdr->set           = setRedundancyDsMemMacKeyLeft;
    hdr->fldSet        = fldSetRedundancyDsMemMacKeyLeft;
    hdr->fldGet        = fldGetRedundancyDsMemMacKeyLeft;
    hdr->print         = printRedundancyDsMemMacKeyLeft;
    hdr->reset         = resetRedundancyDsMemMacKeyLeft;
    hdr->destroy       = destroyRedundancyDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacKeyRight");
    hdr->name          = "RedundancyDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacKeyRight;
    hdr->write         = writeRedundancyDsMemMacKeyRight;
    hdr->set           = setRedundancyDsMemMacKeyRight;
    hdr->fldSet        = fldSetRedundancyDsMemMacKeyRight;
    hdr->fldGet        = fldGetRedundancyDsMemMacKeyRight;
    hdr->print         = printRedundancyDsMemMacKeyRight;
    hdr->reset         = resetRedundancyDsMemMacKeyRight;
    hdr->destroy       = destroyRedundancyDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacLeft");
    hdr->name          = "RedundancyDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacLeft;
    hdr->write         = writeRedundancyDsMemMacLeft;
    hdr->set           = setRedundancyDsMemMacLeft;
    hdr->fldSet        = fldSetRedundancyDsMemMacLeft;
    hdr->fldGet        = fldGetRedundancyDsMemMacLeft;
    hdr->print         = printRedundancyDsMemMacLeft;
    hdr->reset         = resetRedundancyDsMemMacLeft;
    hdr->destroy       = destroyRedundancyDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacRight");
    hdr->name          = "RedundancyDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacRight;
    hdr->write         = writeRedundancyDsMemMacRight;
    hdr->set           = setRedundancyDsMemMacRight;
    hdr->fldSet        = fldSetRedundancyDsMemMacRight;
    hdr->fldGet        = fldGetRedundancyDsMemMacRight;
    hdr->print         = printRedundancyDsMemMacRight;
    hdr->reset         = resetRedundancyDsMemMacRight;
    hdr->destroy       = destroyRedundancyDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacStaticLeft");
    hdr->name          = "RedundancyDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacStaticLeft;
    hdr->write         = writeRedundancyDsMemMacStaticLeft;
    hdr->set           = setRedundancyDsMemMacStaticLeft;
    hdr->fldSet        = fldSetRedundancyDsMemMacStaticLeft;
    hdr->fldGet        = fldGetRedundancyDsMemMacStaticLeft;
    hdr->print         = printRedundancyDsMemMacStaticLeft;
    hdr->reset         = resetRedundancyDsMemMacStaticLeft;
    hdr->destroy       = destroyRedundancyDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacStaticRight");
    hdr->name          = "RedundancyDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacStaticRight;
    hdr->write         = writeRedundancyDsMemMacStaticRight;
    hdr->set           = setRedundancyDsMemMacStaticRight;
    hdr->fldSet        = fldSetRedundancyDsMemMacStaticRight;
    hdr->fldGet        = fldGetRedundancyDsMemMacStaticRight;
    hdr->print         = printRedundancyDsMemMacStaticRight;
    hdr->reset         = resetRedundancyDsMemMacStaticRight;
    hdr->destroy       = destroyRedundancyDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacTsn");
    hdr->name          = "RedundancyDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacTsn;
    hdr->write         = writeRedundancyDsMemMacTsn;
    hdr->set           = setRedundancyDsMemMacTsn;
    hdr->fldSet        = fldSetRedundancyDsMemMacTsn;
    hdr->fldGet        = fldGetRedundancyDsMemMacTsn;
    hdr->print         = printRedundancyDsMemMacTsn;
    hdr->reset         = resetRedundancyDsMemMacTsn;
    hdr->destroy       = destroyRedundancyDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacTsnLeft");
    hdr->name          = "RedundancyDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacTsnLeft;
    hdr->write         = writeRedundancyDsMemMacTsnLeft;
    hdr->set           = setRedundancyDsMemMacTsnLeft;
    hdr->fldSet        = fldSetRedundancyDsMemMacTsnLeft;
    hdr->fldGet        = fldGetRedundancyDsMemMacTsnLeft;
    hdr->print         = printRedundancyDsMemMacTsnLeft;
    hdr->reset         = resetRedundancyDsMemMacTsnLeft;
    hdr->destroy       = destroyRedundancyDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacTsnRight");
    hdr->name          = "RedundancyDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacTsnRight;
    hdr->write         = writeRedundancyDsMemMacTsnRight;
    hdr->set           = setRedundancyDsMemMacTsnRight;
    hdr->fldSet        = fldSetRedundancyDsMemMacTsnRight;
    hdr->fldGet        = fldGetRedundancyDsMemMacTsnRight;
    hdr->print         = printRedundancyDsMemMacTsnRight;
    hdr->reset         = resetRedundancyDsMemMacTsnRight;
    hdr->destroy       = destroyRedundancyDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacValidLeft");
    hdr->name          = "RedundancyDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacValidLeft;
    hdr->write         = writeRedundancyDsMemMacValidLeft;
    hdr->set           = setRedundancyDsMemMacValidLeft;
    hdr->fldSet        = fldSetRedundancyDsMemMacValidLeft;
    hdr->fldGet        = fldGetRedundancyDsMemMacValidLeft;
    hdr->print         = printRedundancyDsMemMacValidLeft;
    hdr->reset         = resetRedundancyDsMemMacValidLeft;
    hdr->destroy       = destroyRedundancyDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemMacValidRight");
    hdr->name          = "RedundancyDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemMacValidRight;
    hdr->write         = writeRedundancyDsMemMacValidRight;
    hdr->set           = setRedundancyDsMemMacValidRight;
    hdr->fldSet        = fldSetRedundancyDsMemMacValidRight;
    hdr->fldGet        = fldGetRedundancyDsMemMacValidRight;
    hdr->print         = printRedundancyDsMemMacValidRight;
    hdr->reset         = resetRedundancyDsMemMacValidRight;
    hdr->destroy       = destroyRedundancyDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemPortColorStats");
    hdr->name          = "RedundancyDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemPortColorStats;
    hdr->write         = writeRedundancyDsMemPortColorStats;
    hdr->set           = setRedundancyDsMemPortColorStats;
    hdr->fldSet        = fldSetRedundancyDsMemPortColorStats;
    hdr->fldGet        = fldGetRedundancyDsMemPortColorStats;
    hdr->print         = printRedundancyDsMemPortColorStats;
    hdr->reset         = resetRedundancyDsMemPortColorStats;
    hdr->destroy       = destroyRedundancyDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemPortPolice");
    hdr->name          = "RedundancyDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemPortPolice;
    hdr->write         = writeRedundancyDsMemPortPolice;
    hdr->set           = setRedundancyDsMemPortPolice;
    hdr->fldSet        = fldSetRedundancyDsMemPortPolice;
    hdr->fldGet        = fldGetRedundancyDsMemPortPolice;
    hdr->print         = printRedundancyDsMemPortPolice;
    hdr->reset         = resetRedundancyDsMemPortPolice;
    hdr->destroy       = destroyRedundancyDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemPortPoliceCfg");
    hdr->name          = "RedundancyDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemPortPoliceCfg;
    hdr->write         = writeRedundancyDsMemPortPoliceCfg;
    hdr->set           = setRedundancyDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetRedundancyDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetRedundancyDsMemPortPoliceCfg;
    hdr->print         = printRedundancyDsMemPortPoliceCfg;
    hdr->reset         = resetRedundancyDsMemPortPoliceCfg;
    hdr->destroy       = destroyRedundancyDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemRcvyCfg");
    hdr->name          = "DsMemRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemRcvyCfg;
    hdr->write         = writeDsMemRcvyCfg;
    hdr->set           = setDsMemRcvyCfg;
    hdr->fldSet        = fldSetDsMemRcvyCfg;
    hdr->fldGet        = fldGetDsMemRcvyCfg;
    hdr->print         = printDsMemRcvyCfg;
    hdr->reset         = resetDsMemRcvyCfg;
    hdr->destroy       = destroyDsMemRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemRcvyCnt");
    hdr->name          = "DsMemRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000128;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemRcvyCnt;
    hdr->write         = writeDsMemRcvyCnt;
    hdr->set           = setDsMemRcvyCnt;
    hdr->fldSet        = fldSetDsMemRcvyCnt;
    hdr->fldGet        = fldGetDsMemRcvyCnt;
    hdr->print         = printDsMemRcvyCnt;
    hdr->reset         = resetDsMemRcvyCnt;
    hdr->destroy       = destroyDsMemRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemRcvySeq");
    hdr->name          = "DsMemRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemRcvySeq;
    hdr->write         = writeDsMemRcvySeq;
    hdr->set           = setDsMemRcvySeq;
    hdr->fldSet        = fldSetDsMemRcvySeq;
    hdr->fldGet        = fldGetDsMemRcvySeq;
    hdr->print         = printDsMemRcvySeq;
    hdr->reset         = resetDsMemRcvySeq;
    hdr->destroy       = destroyDsMemRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemRouteTsn");
    hdr->name          = "RedundancyDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemRouteTsn;
    hdr->write         = writeRedundancyDsMemRouteTsn;
    hdr->set           = setRedundancyDsMemRouteTsn;
    hdr->fldSet        = fldSetRedundancyDsMemRouteTsn;
    hdr->fldGet        = fldGetRedundancyDsMemRouteTsn;
    hdr->print         = printRedundancyDsMemRouteTsn;
    hdr->reset         = resetRedundancyDsMemRouteTsn;
    hdr->destroy       = destroyRedundancyDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemStreamRcvyCfg");
    hdr->name          = "RedundancyDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemStreamRcvyCfg;
    hdr->write         = writeRedundancyDsMemStreamRcvyCfg;
    hdr->set           = setRedundancyDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetRedundancyDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetRedundancyDsMemStreamRcvyCfg;
    hdr->print         = printRedundancyDsMemStreamRcvyCfg;
    hdr->reset         = resetRedundancyDsMemStreamRcvyCfg;
    hdr->destroy       = destroyRedundancyDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemStreamRcvyCnt");
    hdr->name          = "RedundancyDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000148;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemStreamRcvyCnt;
    hdr->write         = writeRedundancyDsMemStreamRcvyCnt;
    hdr->set           = setRedundancyDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetRedundancyDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetRedundancyDsMemStreamRcvyCnt;
    hdr->print         = printRedundancyDsMemStreamRcvyCnt;
    hdr->reset         = resetRedundancyDsMemStreamRcvyCnt;
    hdr->destroy       = destroyRedundancyDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyDsMemStreamRcvySeq");
    hdr->name          = "RedundancyDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyDsMemStreamRcvySeq;
    hdr->write         = writeRedundancyDsMemStreamRcvySeq;
    hdr->set           = setRedundancyDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetRedundancyDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetRedundancyDsMemStreamRcvySeq;
    hdr->print         = printRedundancyDsMemStreamRcvySeq;
    hdr->reset         = resetRedundancyDsMemStreamRcvySeq;
    hdr->destroy       = destroyRedundancyDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyMsgAdmInfo0");
    hdr->name          = "RedundancyMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyMsgAdmInfo0;
    hdr->write         = writeRedundancyMsgAdmInfo0;
    hdr->set           = setRedundancyMsgAdmInfo0;
    hdr->fldSet        = fldSetRedundancyMsgAdmInfo0;
    hdr->fldGet        = fldGetRedundancyMsgAdmInfo0;
    hdr->print         = printRedundancyMsgAdmInfo0;
    hdr->reset         = resetRedundancyMsgAdmInfo0;
    hdr->destroy       = destroyRedundancyMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("RedundancyTmpDsMemMac");
    hdr->name          = "RedundancyTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readRedundancyTmpDsMemMac;
    hdr->write         = writeRedundancyTmpDsMemMac;
    hdr->set           = setRedundancyTmpDsMemMac;
    hdr->fldSet        = fldSetRedundancyTmpDsMemMac;
    hdr->fldGet        = fldGetRedundancyTmpDsMemMac;
    hdr->print         = printRedundancyTmpDsMemMac;
    hdr->reset         = resetRedundancyTmpDsMemMac;
    hdr->destroy       = destroyRedundancyTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
