/*
 * Software Development Kit for Fisilink
 * @file: TrafficManage.c
 * @description: C language expression for TrafficManage module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/TrafficManageOpr.h>


int insertTrafficManageHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlAdmLog");
    hdr->name          = "CtlAdmLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlAdmLog;
    hdr->write         = writeCtlAdmLog;
    hdr->set           = setCtlAdmLog;
    hdr->fldSet        = fldSetCtlAdmLog;
    hdr->fldGet        = fldGetCtlAdmLog;
    hdr->print         = printCtlAdmLog;
    hdr->reset         = resetCtlAdmLog;
    hdr->destroy       = destroyCtlAdmLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageCtlCommon");
    hdr->name          = "TrafficManageCtlCommon";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageCtlCommon;
    hdr->write         = writeTrafficManageCtlCommon;
    hdr->set           = setTrafficManageCtlCommon;
    hdr->fldSet        = fldSetTrafficManageCtlCommon;
    hdr->fldGet        = fldGetTrafficManageCtlCommon;
    hdr->print         = printTrafficManageCtlCommon;
    hdr->reset         = resetTrafficManageCtlCommon;
    hdr->destroy       = destroyTrafficManageCtlCommon;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlEnqCfg");
    hdr->name          = "CtlEnqCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlEnqCfg;
    hdr->write         = writeCtlEnqCfg;
    hdr->set           = setCtlEnqCfg;
    hdr->fldSet        = fldSetCtlEnqCfg;
    hdr->fldGet        = fldGetCtlEnqCfg;
    hdr->print         = printCtlEnqCfg;
    hdr->reset         = resetCtlEnqCfg;
    hdr->destroy       = destroyCtlEnqCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlPtpTimerEn");
    hdr->name          = "CtlPtpTimerEn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000018;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlPtpTimerEn;
    hdr->write         = writeCtlPtpTimerEn;
    hdr->set           = setCtlPtpTimerEn;
    hdr->fldSet        = fldSetCtlPtpTimerEn;
    hdr->fldGet        = fldGetCtlPtpTimerEn;
    hdr->print         = printCtlPtpTimerEn;
    hdr->reset         = resetCtlPtpTimerEn;
    hdr->destroy       = destroyCtlPtpTimerEn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlRepExtPort");
    hdr->name          = "CtlRepExtPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000020;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlRepExtPort;
    hdr->write         = writeCtlRepExtPort;
    hdr->set           = setCtlRepExtPort;
    hdr->fldSet        = fldSetCtlRepExtPort;
    hdr->fldGet        = fldGetCtlRepExtPort;
    hdr->print         = printCtlRepExtPort;
    hdr->reset         = resetCtlRepExtPort;
    hdr->destroy       = destroyCtlRepExtPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemAclTsn");
    hdr->name          = "TrafficManageDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000050;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemAclTsn;
    hdr->write         = writeTrafficManageDsMemAclTsn;
    hdr->set           = setTrafficManageDsMemAclTsn;
    hdr->fldSet        = fldSetTrafficManageDsMemAclTsn;
    hdr->fldGet        = fldGetTrafficManageDsMemAclTsn;
    hdr->print         = printTrafficManageDsMemAclTsn;
    hdr->reset         = resetTrafficManageDsMemAclTsn;
    hdr->destroy       = destroyTrafficManageDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemFlowColorStats");
    hdr->name          = "TrafficManageDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemFlowColorStats;
    hdr->write         = writeTrafficManageDsMemFlowColorStats;
    hdr->set           = setTrafficManageDsMemFlowColorStats;
    hdr->fldSet        = fldSetTrafficManageDsMemFlowColorStats;
    hdr->fldGet        = fldGetTrafficManageDsMemFlowColorStats;
    hdr->print         = printTrafficManageDsMemFlowColorStats;
    hdr->reset         = resetTrafficManageDsMemFlowColorStats;
    hdr->destroy       = destroyTrafficManageDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemFlowPolice");
    hdr->name          = "TrafficManageDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemFlowPolice;
    hdr->write         = writeTrafficManageDsMemFlowPolice;
    hdr->set           = setTrafficManageDsMemFlowPolice;
    hdr->fldSet        = fldSetTrafficManageDsMemFlowPolice;
    hdr->fldGet        = fldGetTrafficManageDsMemFlowPolice;
    hdr->print         = printTrafficManageDsMemFlowPolice;
    hdr->reset         = resetTrafficManageDsMemFlowPolice;
    hdr->destroy       = destroyTrafficManageDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemFlowPoliceCfg");
    hdr->name          = "TrafficManageDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000080;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemFlowPoliceCfg;
    hdr->write         = writeTrafficManageDsMemFlowPoliceCfg;
    hdr->set           = setTrafficManageDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetTrafficManageDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetTrafficManageDsMemFlowPoliceCfg;
    hdr->print         = printTrafficManageDsMemFlowPoliceCfg;
    hdr->reset         = resetTrafficManageDsMemFlowPoliceCfg;
    hdr->destroy       = destroyTrafficManageDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostRoute");
    hdr->name          = "TrafficManageDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostRoute;
    hdr->write         = writeTrafficManageDsMemHostRoute;
    hdr->set           = setTrafficManageDsMemHostRoute;
    hdr->fldSet        = fldSetTrafficManageDsMemHostRoute;
    hdr->fldGet        = fldGetTrafficManageDsMemHostRoute;
    hdr->print         = printTrafficManageDsMemHostRoute;
    hdr->reset         = resetTrafficManageDsMemHostRoute;
    hdr->destroy       = destroyTrafficManageDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostRouteLeft");
    hdr->name          = "TrafficManageDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostRouteLeft;
    hdr->write         = writeTrafficManageDsMemHostRouteLeft;
    hdr->set           = setTrafficManageDsMemHostRouteLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemHostRouteLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemHostRouteLeft;
    hdr->print         = printTrafficManageDsMemHostRouteLeft;
    hdr->reset         = resetTrafficManageDsMemHostRouteLeft;
    hdr->destroy       = destroyTrafficManageDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostRouteLeftKey");
    hdr->name          = "TrafficManageDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostRouteLeftKey;
    hdr->write         = writeTrafficManageDsMemHostRouteLeftKey;
    hdr->set           = setTrafficManageDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetTrafficManageDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetTrafficManageDsMemHostRouteLeftKey;
    hdr->print         = printTrafficManageDsMemHostRouteLeftKey;
    hdr->reset         = resetTrafficManageDsMemHostRouteLeftKey;
    hdr->destroy       = destroyTrafficManageDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostRouteLeftValid");
    hdr->name          = "TrafficManageDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostRouteLeftValid;
    hdr->write         = writeTrafficManageDsMemHostRouteLeftValid;
    hdr->set           = setTrafficManageDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetTrafficManageDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetTrafficManageDsMemHostRouteLeftValid;
    hdr->print         = printTrafficManageDsMemHostRouteLeftValid;
    hdr->reset         = resetTrafficManageDsMemHostRouteLeftValid;
    hdr->destroy       = destroyTrafficManageDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostRouteRight");
    hdr->name          = "TrafficManageDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostRouteRight;
    hdr->write         = writeTrafficManageDsMemHostRouteRight;
    hdr->set           = setTrafficManageDsMemHostRouteRight;
    hdr->fldSet        = fldSetTrafficManageDsMemHostRouteRight;
    hdr->fldGet        = fldGetTrafficManageDsMemHostRouteRight;
    hdr->print         = printTrafficManageDsMemHostRouteRight;
    hdr->reset         = resetTrafficManageDsMemHostRouteRight;
    hdr->destroy       = destroyTrafficManageDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostRouteRightKey");
    hdr->name          = "TrafficManageDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostRouteRightKey;
    hdr->write         = writeTrafficManageDsMemHostRouteRightKey;
    hdr->set           = setTrafficManageDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetTrafficManageDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetTrafficManageDsMemHostRouteRightKey;
    hdr->print         = printTrafficManageDsMemHostRouteRightKey;
    hdr->reset         = resetTrafficManageDsMemHostRouteRightKey;
    hdr->destroy       = destroyTrafficManageDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostRouteRightValid");
    hdr->name          = "TrafficManageDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostRouteRightValid;
    hdr->write         = writeTrafficManageDsMemHostRouteRightValid;
    hdr->set           = setTrafficManageDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetTrafficManageDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetTrafficManageDsMemHostRouteRightValid;
    hdr->print         = printTrafficManageDsMemHostRouteRightValid;
    hdr->reset         = resetTrafficManageDsMemHostRouteRightValid;
    hdr->destroy       = destroyTrafficManageDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostTsn");
    hdr->name          = "TrafficManageDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostTsn;
    hdr->write         = writeTrafficManageDsMemHostTsn;
    hdr->set           = setTrafficManageDsMemHostTsn;
    hdr->fldSet        = fldSetTrafficManageDsMemHostTsn;
    hdr->fldGet        = fldGetTrafficManageDsMemHostTsn;
    hdr->print         = printTrafficManageDsMemHostTsn;
    hdr->reset         = resetTrafficManageDsMemHostTsn;
    hdr->destroy       = destroyTrafficManageDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostTsnLeft");
    hdr->name          = "TrafficManageDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostTsnLeft;
    hdr->write         = writeTrafficManageDsMemHostTsnLeft;
    hdr->set           = setTrafficManageDsMemHostTsnLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemHostTsnLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemHostTsnLeft;
    hdr->print         = printTrafficManageDsMemHostTsnLeft;
    hdr->reset         = resetTrafficManageDsMemHostTsnLeft;
    hdr->destroy       = destroyTrafficManageDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemHostTsnRight");
    hdr->name          = "TrafficManageDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemHostTsnRight;
    hdr->write         = writeTrafficManageDsMemHostTsnRight;
    hdr->set           = setTrafficManageDsMemHostTsnRight;
    hdr->fldSet        = fldSetTrafficManageDsMemHostTsnRight;
    hdr->fldGet        = fldGetTrafficManageDsMemHostTsnRight;
    hdr->print         = printTrafficManageDsMemHostTsnRight;
    hdr->reset         = resetTrafficManageDsMemHostTsnRight;
    hdr->destroy       = destroyTrafficManageDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemIndvRcvyCfg");
    hdr->name          = "TrafficManageDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemIndvRcvyCfg;
    hdr->write         = writeTrafficManageDsMemIndvRcvyCfg;
    hdr->set           = setTrafficManageDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetTrafficManageDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetTrafficManageDsMemIndvRcvyCfg;
    hdr->print         = printTrafficManageDsMemIndvRcvyCfg;
    hdr->reset         = resetTrafficManageDsMemIndvRcvyCfg;
    hdr->destroy       = destroyTrafficManageDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemIndvRcvyCnt");
    hdr->name          = "TrafficManageDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemIndvRcvyCnt;
    hdr->write         = writeTrafficManageDsMemIndvRcvyCnt;
    hdr->set           = setTrafficManageDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetTrafficManageDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetTrafficManageDsMemIndvRcvyCnt;
    hdr->print         = printTrafficManageDsMemIndvRcvyCnt;
    hdr->reset         = resetTrafficManageDsMemIndvRcvyCnt;
    hdr->destroy       = destroyTrafficManageDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemIndvRcvySeq");
    hdr->name          = "TrafficManageDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemIndvRcvySeq;
    hdr->write         = writeTrafficManageDsMemIndvRcvySeq;
    hdr->set           = setTrafficManageDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetTrafficManageDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetTrafficManageDsMemIndvRcvySeq;
    hdr->print         = printTrafficManageDsMemIndvRcvySeq;
    hdr->reset         = resetTrafficManageDsMemIndvRcvySeq;
    hdr->destroy       = destroyTrafficManageDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacAgingLeft");
    hdr->name          = "TrafficManageDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacAgingLeft;
    hdr->write         = writeTrafficManageDsMemMacAgingLeft;
    hdr->set           = setTrafficManageDsMemMacAgingLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemMacAgingLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemMacAgingLeft;
    hdr->print         = printTrafficManageDsMemMacAgingLeft;
    hdr->reset         = resetTrafficManageDsMemMacAgingLeft;
    hdr->destroy       = destroyTrafficManageDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacAgingRight");
    hdr->name          = "TrafficManageDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacAgingRight;
    hdr->write         = writeTrafficManageDsMemMacAgingRight;
    hdr->set           = setTrafficManageDsMemMacAgingRight;
    hdr->fldSet        = fldSetTrafficManageDsMemMacAgingRight;
    hdr->fldGet        = fldGetTrafficManageDsMemMacAgingRight;
    hdr->print         = printTrafficManageDsMemMacAgingRight;
    hdr->reset         = resetTrafficManageDsMemMacAgingRight;
    hdr->destroy       = destroyTrafficManageDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacKeyLeft");
    hdr->name          = "TrafficManageDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacKeyLeft;
    hdr->write         = writeTrafficManageDsMemMacKeyLeft;
    hdr->set           = setTrafficManageDsMemMacKeyLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemMacKeyLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemMacKeyLeft;
    hdr->print         = printTrafficManageDsMemMacKeyLeft;
    hdr->reset         = resetTrafficManageDsMemMacKeyLeft;
    hdr->destroy       = destroyTrafficManageDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacKeyRight");
    hdr->name          = "TrafficManageDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacKeyRight;
    hdr->write         = writeTrafficManageDsMemMacKeyRight;
    hdr->set           = setTrafficManageDsMemMacKeyRight;
    hdr->fldSet        = fldSetTrafficManageDsMemMacKeyRight;
    hdr->fldGet        = fldGetTrafficManageDsMemMacKeyRight;
    hdr->print         = printTrafficManageDsMemMacKeyRight;
    hdr->reset         = resetTrafficManageDsMemMacKeyRight;
    hdr->destroy       = destroyTrafficManageDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacLeft");
    hdr->name          = "TrafficManageDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacLeft;
    hdr->write         = writeTrafficManageDsMemMacLeft;
    hdr->set           = setTrafficManageDsMemMacLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemMacLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemMacLeft;
    hdr->print         = printTrafficManageDsMemMacLeft;
    hdr->reset         = resetTrafficManageDsMemMacLeft;
    hdr->destroy       = destroyTrafficManageDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacRight");
    hdr->name          = "TrafficManageDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacRight;
    hdr->write         = writeTrafficManageDsMemMacRight;
    hdr->set           = setTrafficManageDsMemMacRight;
    hdr->fldSet        = fldSetTrafficManageDsMemMacRight;
    hdr->fldGet        = fldGetTrafficManageDsMemMacRight;
    hdr->print         = printTrafficManageDsMemMacRight;
    hdr->reset         = resetTrafficManageDsMemMacRight;
    hdr->destroy       = destroyTrafficManageDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacStaticLeft");
    hdr->name          = "TrafficManageDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacStaticLeft;
    hdr->write         = writeTrafficManageDsMemMacStaticLeft;
    hdr->set           = setTrafficManageDsMemMacStaticLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemMacStaticLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemMacStaticLeft;
    hdr->print         = printTrafficManageDsMemMacStaticLeft;
    hdr->reset         = resetTrafficManageDsMemMacStaticLeft;
    hdr->destroy       = destroyTrafficManageDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacStaticRight");
    hdr->name          = "TrafficManageDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacStaticRight;
    hdr->write         = writeTrafficManageDsMemMacStaticRight;
    hdr->set           = setTrafficManageDsMemMacStaticRight;
    hdr->fldSet        = fldSetTrafficManageDsMemMacStaticRight;
    hdr->fldGet        = fldGetTrafficManageDsMemMacStaticRight;
    hdr->print         = printTrafficManageDsMemMacStaticRight;
    hdr->reset         = resetTrafficManageDsMemMacStaticRight;
    hdr->destroy       = destroyTrafficManageDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacTsn");
    hdr->name          = "TrafficManageDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacTsn;
    hdr->write         = writeTrafficManageDsMemMacTsn;
    hdr->set           = setTrafficManageDsMemMacTsn;
    hdr->fldSet        = fldSetTrafficManageDsMemMacTsn;
    hdr->fldGet        = fldGetTrafficManageDsMemMacTsn;
    hdr->print         = printTrafficManageDsMemMacTsn;
    hdr->reset         = resetTrafficManageDsMemMacTsn;
    hdr->destroy       = destroyTrafficManageDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacTsnLeft");
    hdr->name          = "TrafficManageDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacTsnLeft;
    hdr->write         = writeTrafficManageDsMemMacTsnLeft;
    hdr->set           = setTrafficManageDsMemMacTsnLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemMacTsnLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemMacTsnLeft;
    hdr->print         = printTrafficManageDsMemMacTsnLeft;
    hdr->reset         = resetTrafficManageDsMemMacTsnLeft;
    hdr->destroy       = destroyTrafficManageDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacTsnRight");
    hdr->name          = "TrafficManageDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacTsnRight;
    hdr->write         = writeTrafficManageDsMemMacTsnRight;
    hdr->set           = setTrafficManageDsMemMacTsnRight;
    hdr->fldSet        = fldSetTrafficManageDsMemMacTsnRight;
    hdr->fldGet        = fldGetTrafficManageDsMemMacTsnRight;
    hdr->print         = printTrafficManageDsMemMacTsnRight;
    hdr->reset         = resetTrafficManageDsMemMacTsnRight;
    hdr->destroy       = destroyTrafficManageDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacValidLeft");
    hdr->name          = "TrafficManageDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacValidLeft;
    hdr->write         = writeTrafficManageDsMemMacValidLeft;
    hdr->set           = setTrafficManageDsMemMacValidLeft;
    hdr->fldSet        = fldSetTrafficManageDsMemMacValidLeft;
    hdr->fldGet        = fldGetTrafficManageDsMemMacValidLeft;
    hdr->print         = printTrafficManageDsMemMacValidLeft;
    hdr->reset         = resetTrafficManageDsMemMacValidLeft;
    hdr->destroy       = destroyTrafficManageDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemMacValidRight");
    hdr->name          = "TrafficManageDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000220;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemMacValidRight;
    hdr->write         = writeTrafficManageDsMemMacValidRight;
    hdr->set           = setTrafficManageDsMemMacValidRight;
    hdr->fldSet        = fldSetTrafficManageDsMemMacValidRight;
    hdr->fldGet        = fldGetTrafficManageDsMemMacValidRight;
    hdr->print         = printTrafficManageDsMemMacValidRight;
    hdr->reset         = resetTrafficManageDsMemMacValidRight;
    hdr->destroy       = destroyTrafficManageDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemPortColorStats");
    hdr->name          = "TrafficManageDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemPortColorStats;
    hdr->write         = writeTrafficManageDsMemPortColorStats;
    hdr->set           = setTrafficManageDsMemPortColorStats;
    hdr->fldSet        = fldSetTrafficManageDsMemPortColorStats;
    hdr->fldGet        = fldGetTrafficManageDsMemPortColorStats;
    hdr->print         = printTrafficManageDsMemPortColorStats;
    hdr->reset         = resetTrafficManageDsMemPortColorStats;
    hdr->destroy       = destroyTrafficManageDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemPortPolice");
    hdr->name          = "TrafficManageDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemPortPolice;
    hdr->write         = writeTrafficManageDsMemPortPolice;
    hdr->set           = setTrafficManageDsMemPortPolice;
    hdr->fldSet        = fldSetTrafficManageDsMemPortPolice;
    hdr->fldGet        = fldGetTrafficManageDsMemPortPolice;
    hdr->print         = printTrafficManageDsMemPortPolice;
    hdr->reset         = resetTrafficManageDsMemPortPolice;
    hdr->destroy       = destroyTrafficManageDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemPortPoliceCfg");
    hdr->name          = "TrafficManageDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemPortPoliceCfg;
    hdr->write         = writeTrafficManageDsMemPortPoliceCfg;
    hdr->set           = setTrafficManageDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetTrafficManageDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetTrafficManageDsMemPortPoliceCfg;
    hdr->print         = printTrafficManageDsMemPortPoliceCfg;
    hdr->reset         = resetTrafficManageDsMemPortPoliceCfg;
    hdr->destroy       = destroyTrafficManageDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemRouteTsn");
    hdr->name          = "TrafficManageDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemRouteTsn;
    hdr->write         = writeTrafficManageDsMemRouteTsn;
    hdr->set           = setTrafficManageDsMemRouteTsn;
    hdr->fldSet        = fldSetTrafficManageDsMemRouteTsn;
    hdr->fldGet        = fldGetTrafficManageDsMemRouteTsn;
    hdr->print         = printTrafficManageDsMemRouteTsn;
    hdr->reset         = resetTrafficManageDsMemRouteTsn;
    hdr->destroy       = destroyTrafficManageDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemStreamRcvyCfg");
    hdr->name          = "TrafficManageDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemStreamRcvyCfg;
    hdr->write         = writeTrafficManageDsMemStreamRcvyCfg;
    hdr->set           = setTrafficManageDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetTrafficManageDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetTrafficManageDsMemStreamRcvyCfg;
    hdr->print         = printTrafficManageDsMemStreamRcvyCfg;
    hdr->reset         = resetTrafficManageDsMemStreamRcvyCfg;
    hdr->destroy       = destroyTrafficManageDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemStreamRcvyCnt");
    hdr->name          = "TrafficManageDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemStreamRcvyCnt;
    hdr->write         = writeTrafficManageDsMemStreamRcvyCnt;
    hdr->set           = setTrafficManageDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetTrafficManageDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetTrafficManageDsMemStreamRcvyCnt;
    hdr->print         = printTrafficManageDsMemStreamRcvyCnt;
    hdr->reset         = resetTrafficManageDsMemStreamRcvyCnt;
    hdr->destroy       = destroyTrafficManageDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageDsMemStreamRcvySeq");
    hdr->name          = "TrafficManageDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000290;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageDsMemStreamRcvySeq;
    hdr->write         = writeTrafficManageDsMemStreamRcvySeq;
    hdr->set           = setTrafficManageDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetTrafficManageDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetTrafficManageDsMemStreamRcvySeq;
    hdr->print         = printTrafficManageDsMemStreamRcvySeq;
    hdr->reset         = resetTrafficManageDsMemStreamRcvySeq;
    hdr->destroy       = destroyTrafficManageDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemTsnGate");
    hdr->name          = "DsMemTsnGate";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemTsnGate;
    hdr->write         = writeDsMemTsnGate;
    hdr->set           = setDsMemTsnGate;
    hdr->fldSet        = fldSetDsMemTsnGate;
    hdr->fldGet        = fldGetDsMemTsnGate;
    hdr->print         = printDsMemTsnGate;
    hdr->reset         = resetDsMemTsnGate;
    hdr->destroy       = destroyDsMemTsnGate;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegCpuPktPrior");
    hdr->name          = "DsRegCpuPktPrior";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000158;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegCpuPktPrior;
    hdr->write         = writeDsRegCpuPktPrior;
    hdr->set           = setDsRegCpuPktPrior;
    hdr->fldSet        = fldSetDsRegCpuPktPrior;
    hdr->fldGet        = fldGetDsRegCpuPktPrior;
    hdr->print         = printDsRegCpuPktPrior;
    hdr->reset         = resetDsRegCpuPktPrior;
    hdr->destroy       = destroyDsRegCpuPktPrior;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegPtpTimer");
    hdr->name          = "DsRegPtpTimer";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000160;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegPtpTimer;
    hdr->write         = writeDsRegPtpTimer;
    hdr->set           = setDsRegPtpTimer;
    hdr->fldSet        = fldSetDsRegPtpTimer;
    hdr->fldGet        = fldGetDsRegPtpTimer;
    hdr->print         = printDsRegPtpTimer;
    hdr->reset         = resetDsRegPtpTimer;
    hdr->destroy       = destroyDsRegPtpTimer;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsRegQueueDrop");
    hdr->name          = "DsRegQueueDrop";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000168;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsRegQueueDrop;
    hdr->write         = writeDsRegQueueDrop;
    hdr->set           = setDsRegQueueDrop;
    hdr->fldSet        = fldSetDsRegQueueDrop;
    hdr->fldGet        = fldGetDsRegQueueDrop;
    hdr->print         = printDsRegQueueDrop;
    hdr->reset         = resetDsRegQueueDrop;
    hdr->destroy       = destroyDsRegQueueDrop;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageMsgAdmInfo0");
    hdr->name          = "TrafficManageMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageMsgAdmInfo0;
    hdr->write         = writeTrafficManageMsgAdmInfo0;
    hdr->set           = setTrafficManageMsgAdmInfo0;
    hdr->fldSet        = fldSetTrafficManageMsgAdmInfo0;
    hdr->fldGet        = fldGetTrafficManageMsgAdmInfo0;
    hdr->print         = printTrafficManageMsgAdmInfo0;
    hdr->reset         = resetTrafficManageMsgAdmInfo0;
    hdr->destroy       = destroyTrafficManageMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("TrafficManageTmpDsMemMac");
    hdr->name          = "TrafficManageTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readTrafficManageTmpDsMemMac;
    hdr->write         = writeTrafficManageTmpDsMemMac;
    hdr->set           = setTrafficManageTmpDsMemMac;
    hdr->fldSet        = fldSetTrafficManageTmpDsMemMac;
    hdr->fldGet        = fldGetTrafficManageTmpDsMemMac;
    hdr->print         = printTrafficManageTmpDsMemMac;
    hdr->reset         = resetTrafficManageTmpDsMemMac;
    hdr->destroy       = destroyTrafficManageTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
