/*
 * Software Development Kit for Fisilink
 * @file: VlanLookup.c
 * @description: C language expression for VlanLookup module
 * @note: Copyright (C) 2020 
 *
 * You should have received a copy of the Fisilink License
 * along with this program; if not, write to Fisilink
 */


#include <stdlib.h>
#include <assert.h>
#include <common/hash.h>
#include <common/rbmem.h>
#include <mem/VlanLookupOpr.h>


int insertVlanLookupHdr(struct rb_root *root) {
    tMemRegHdr *hdr = NULL;
    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupCtlCommon");
    hdr->name          = "VlanLookupCtlCommon";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000000;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupCtlCommon;
    hdr->write         = writeVlanLookupCtlCommon;
    hdr->set           = setVlanLookupCtlCommon;
    hdr->fldSet        = fldSetVlanLookupCtlCommon;
    hdr->fldGet        = fldGetVlanLookupCtlCommon;
    hdr->print         = printVlanLookupCtlCommon;
    hdr->reset         = resetVlanLookupCtlCommon;
    hdr->destroy       = destroyVlanLookupCtlCommon;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlProtocolVlanKey");
    hdr->name          = "CtlProtocolVlanKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000008;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlProtocolVlanKey;
    hdr->write         = writeCtlProtocolVlanKey;
    hdr->set           = setCtlProtocolVlanKey;
    hdr->fldSet        = fldSetCtlProtocolVlanKey;
    hdr->fldGet        = fldGetCtlProtocolVlanKey;
    hdr->print         = printCtlProtocolVlanKey;
    hdr->reset         = resetCtlProtocolVlanKey;
    hdr->destroy       = destroyCtlProtocolVlanKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("CtlVlanLookupLog");
    hdr->name          = "CtlVlanLookupLog";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000010;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readCtlVlanLookupLog;
    hdr->write         = writeCtlVlanLookupLog;
    hdr->set           = setCtlVlanLookupLog;
    hdr->fldSet        = fldSetCtlVlanLookupLog;
    hdr->fldGet        = fldGetCtlVlanLookupLog;
    hdr->print         = printCtlVlanLookupLog;
    hdr->reset         = resetCtlVlanLookupLog;
    hdr->destroy       = destroyCtlVlanLookupLog;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemAclTsn");
    hdr->name          = "VlanLookupDsMemAclTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000030;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemAclTsn;
    hdr->write         = writeVlanLookupDsMemAclTsn;
    hdr->set           = setVlanLookupDsMemAclTsn;
    hdr->fldSet        = fldSetVlanLookupDsMemAclTsn;
    hdr->fldGet        = fldGetVlanLookupDsMemAclTsn;
    hdr->print         = printVlanLookupDsMemAclTsn;
    hdr->reset         = resetVlanLookupDsMemAclTsn;
    hdr->destroy       = destroyVlanLookupDsMemAclTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemFlowColorStats");
    hdr->name          = "VlanLookupDsMemFlowColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000040;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemFlowColorStats;
    hdr->write         = writeVlanLookupDsMemFlowColorStats;
    hdr->set           = setVlanLookupDsMemFlowColorStats;
    hdr->fldSet        = fldSetVlanLookupDsMemFlowColorStats;
    hdr->fldGet        = fldGetVlanLookupDsMemFlowColorStats;
    hdr->print         = printVlanLookupDsMemFlowColorStats;
    hdr->reset         = resetVlanLookupDsMemFlowColorStats;
    hdr->destroy       = destroyVlanLookupDsMemFlowColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemFlowPolice");
    hdr->name          = "VlanLookupDsMemFlowPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000050;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemFlowPolice;
    hdr->write         = writeVlanLookupDsMemFlowPolice;
    hdr->set           = setVlanLookupDsMemFlowPolice;
    hdr->fldSet        = fldSetVlanLookupDsMemFlowPolice;
    hdr->fldGet        = fldGetVlanLookupDsMemFlowPolice;
    hdr->print         = printVlanLookupDsMemFlowPolice;
    hdr->reset         = resetVlanLookupDsMemFlowPolice;
    hdr->destroy       = destroyVlanLookupDsMemFlowPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemFlowPoliceCfg");
    hdr->name          = "VlanLookupDsMemFlowPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000060;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemFlowPoliceCfg;
    hdr->write         = writeVlanLookupDsMemFlowPoliceCfg;
    hdr->set           = setVlanLookupDsMemFlowPoliceCfg;
    hdr->fldSet        = fldSetVlanLookupDsMemFlowPoliceCfg;
    hdr->fldGet        = fldGetVlanLookupDsMemFlowPoliceCfg;
    hdr->print         = printVlanLookupDsMemFlowPoliceCfg;
    hdr->reset         = resetVlanLookupDsMemFlowPoliceCfg;
    hdr->destroy       = destroyVlanLookupDsMemFlowPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostRoute");
    hdr->name          = "VlanLookupDsMemHostRoute";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000070;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostRoute;
    hdr->write         = writeVlanLookupDsMemHostRoute;
    hdr->set           = setVlanLookupDsMemHostRoute;
    hdr->fldSet        = fldSetVlanLookupDsMemHostRoute;
    hdr->fldGet        = fldGetVlanLookupDsMemHostRoute;
    hdr->print         = printVlanLookupDsMemHostRoute;
    hdr->reset         = resetVlanLookupDsMemHostRoute;
    hdr->destroy       = destroyVlanLookupDsMemHostRoute;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostRouteLeft");
    hdr->name          = "VlanLookupDsMemHostRouteLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000080;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostRouteLeft;
    hdr->write         = writeVlanLookupDsMemHostRouteLeft;
    hdr->set           = setVlanLookupDsMemHostRouteLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemHostRouteLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemHostRouteLeft;
    hdr->print         = printVlanLookupDsMemHostRouteLeft;
    hdr->reset         = resetVlanLookupDsMemHostRouteLeft;
    hdr->destroy       = destroyVlanLookupDsMemHostRouteLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostRouteLeftKey");
    hdr->name          = "VlanLookupDsMemHostRouteLeftKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000090;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostRouteLeftKey;
    hdr->write         = writeVlanLookupDsMemHostRouteLeftKey;
    hdr->set           = setVlanLookupDsMemHostRouteLeftKey;
    hdr->fldSet        = fldSetVlanLookupDsMemHostRouteLeftKey;
    hdr->fldGet        = fldGetVlanLookupDsMemHostRouteLeftKey;
    hdr->print         = printVlanLookupDsMemHostRouteLeftKey;
    hdr->reset         = resetVlanLookupDsMemHostRouteLeftKey;
    hdr->destroy       = destroyVlanLookupDsMemHostRouteLeftKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostRouteLeftValid");
    hdr->name          = "VlanLookupDsMemHostRouteLeftValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostRouteLeftValid;
    hdr->write         = writeVlanLookupDsMemHostRouteLeftValid;
    hdr->set           = setVlanLookupDsMemHostRouteLeftValid;
    hdr->fldSet        = fldSetVlanLookupDsMemHostRouteLeftValid;
    hdr->fldGet        = fldGetVlanLookupDsMemHostRouteLeftValid;
    hdr->print         = printVlanLookupDsMemHostRouteLeftValid;
    hdr->reset         = resetVlanLookupDsMemHostRouteLeftValid;
    hdr->destroy       = destroyVlanLookupDsMemHostRouteLeftValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostRouteRight");
    hdr->name          = "VlanLookupDsMemHostRouteRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostRouteRight;
    hdr->write         = writeVlanLookupDsMemHostRouteRight;
    hdr->set           = setVlanLookupDsMemHostRouteRight;
    hdr->fldSet        = fldSetVlanLookupDsMemHostRouteRight;
    hdr->fldGet        = fldGetVlanLookupDsMemHostRouteRight;
    hdr->print         = printVlanLookupDsMemHostRouteRight;
    hdr->reset         = resetVlanLookupDsMemHostRouteRight;
    hdr->destroy       = destroyVlanLookupDsMemHostRouteRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostRouteRightKey");
    hdr->name          = "VlanLookupDsMemHostRouteRightKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostRouteRightKey;
    hdr->write         = writeVlanLookupDsMemHostRouteRightKey;
    hdr->set           = setVlanLookupDsMemHostRouteRightKey;
    hdr->fldSet        = fldSetVlanLookupDsMemHostRouteRightKey;
    hdr->fldGet        = fldGetVlanLookupDsMemHostRouteRightKey;
    hdr->print         = printVlanLookupDsMemHostRouteRightKey;
    hdr->reset         = resetVlanLookupDsMemHostRouteRightKey;
    hdr->destroy       = destroyVlanLookupDsMemHostRouteRightKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostRouteRightValid");
    hdr->name          = "VlanLookupDsMemHostRouteRightValid";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostRouteRightValid;
    hdr->write         = writeVlanLookupDsMemHostRouteRightValid;
    hdr->set           = setVlanLookupDsMemHostRouteRightValid;
    hdr->fldSet        = fldSetVlanLookupDsMemHostRouteRightValid;
    hdr->fldGet        = fldGetVlanLookupDsMemHostRouteRightValid;
    hdr->print         = printVlanLookupDsMemHostRouteRightValid;
    hdr->reset         = resetVlanLookupDsMemHostRouteRightValid;
    hdr->destroy       = destroyVlanLookupDsMemHostRouteRightValid;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostTsn");
    hdr->name          = "VlanLookupDsMemHostTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostTsn;
    hdr->write         = writeVlanLookupDsMemHostTsn;
    hdr->set           = setVlanLookupDsMemHostTsn;
    hdr->fldSet        = fldSetVlanLookupDsMemHostTsn;
    hdr->fldGet        = fldGetVlanLookupDsMemHostTsn;
    hdr->print         = printVlanLookupDsMemHostTsn;
    hdr->reset         = resetVlanLookupDsMemHostTsn;
    hdr->destroy       = destroyVlanLookupDsMemHostTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostTsnLeft");
    hdr->name          = "VlanLookupDsMemHostTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostTsnLeft;
    hdr->write         = writeVlanLookupDsMemHostTsnLeft;
    hdr->set           = setVlanLookupDsMemHostTsnLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemHostTsnLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemHostTsnLeft;
    hdr->print         = printVlanLookupDsMemHostTsnLeft;
    hdr->reset         = resetVlanLookupDsMemHostTsnLeft;
    hdr->destroy       = destroyVlanLookupDsMemHostTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemHostTsnRight");
    hdr->name          = "VlanLookupDsMemHostTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000100;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemHostTsnRight;
    hdr->write         = writeVlanLookupDsMemHostTsnRight;
    hdr->set           = setVlanLookupDsMemHostTsnRight;
    hdr->fldSet        = fldSetVlanLookupDsMemHostTsnRight;
    hdr->fldGet        = fldGetVlanLookupDsMemHostTsnRight;
    hdr->print         = printVlanLookupDsMemHostTsnRight;
    hdr->reset         = resetVlanLookupDsMemHostTsnRight;
    hdr->destroy       = destroyVlanLookupDsMemHostTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemIndvRcvyCfg");
    hdr->name          = "VlanLookupDsMemIndvRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemIndvRcvyCfg;
    hdr->write         = writeVlanLookupDsMemIndvRcvyCfg;
    hdr->set           = setVlanLookupDsMemIndvRcvyCfg;
    hdr->fldSet        = fldSetVlanLookupDsMemIndvRcvyCfg;
    hdr->fldGet        = fldGetVlanLookupDsMemIndvRcvyCfg;
    hdr->print         = printVlanLookupDsMemIndvRcvyCfg;
    hdr->reset         = resetVlanLookupDsMemIndvRcvyCfg;
    hdr->destroy       = destroyVlanLookupDsMemIndvRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemIndvRcvyCnt");
    hdr->name          = "VlanLookupDsMemIndvRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000120;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemIndvRcvyCnt;
    hdr->write         = writeVlanLookupDsMemIndvRcvyCnt;
    hdr->set           = setVlanLookupDsMemIndvRcvyCnt;
    hdr->fldSet        = fldSetVlanLookupDsMemIndvRcvyCnt;
    hdr->fldGet        = fldGetVlanLookupDsMemIndvRcvyCnt;
    hdr->print         = printVlanLookupDsMemIndvRcvyCnt;
    hdr->reset         = resetVlanLookupDsMemIndvRcvyCnt;
    hdr->destroy       = destroyVlanLookupDsMemIndvRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemIndvRcvySeq");
    hdr->name          = "VlanLookupDsMemIndvRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000130;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemIndvRcvySeq;
    hdr->write         = writeVlanLookupDsMemIndvRcvySeq;
    hdr->set           = setVlanLookupDsMemIndvRcvySeq;
    hdr->fldSet        = fldSetVlanLookupDsMemIndvRcvySeq;
    hdr->fldGet        = fldGetVlanLookupDsMemIndvRcvySeq;
    hdr->print         = printVlanLookupDsMemIndvRcvySeq;
    hdr->reset         = resetVlanLookupDsMemIndvRcvySeq;
    hdr->destroy       = destroyVlanLookupDsMemIndvRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacAgingLeft");
    hdr->name          = "VlanLookupDsMemMacAgingLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000140;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacAgingLeft;
    hdr->write         = writeVlanLookupDsMemMacAgingLeft;
    hdr->set           = setVlanLookupDsMemMacAgingLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemMacAgingLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemMacAgingLeft;
    hdr->print         = printVlanLookupDsMemMacAgingLeft;
    hdr->reset         = resetVlanLookupDsMemMacAgingLeft;
    hdr->destroy       = destroyVlanLookupDsMemMacAgingLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacAgingRight");
    hdr->name          = "VlanLookupDsMemMacAgingRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000150;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacAgingRight;
    hdr->write         = writeVlanLookupDsMemMacAgingRight;
    hdr->set           = setVlanLookupDsMemMacAgingRight;
    hdr->fldSet        = fldSetVlanLookupDsMemMacAgingRight;
    hdr->fldGet        = fldGetVlanLookupDsMemMacAgingRight;
    hdr->print         = printVlanLookupDsMemMacAgingRight;
    hdr->reset         = resetVlanLookupDsMemMacAgingRight;
    hdr->destroy       = destroyVlanLookupDsMemMacAgingRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemMacBasedVlanKey");
    hdr->name          = "DsMemMacBasedVlanKey";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0000b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemMacBasedVlanKey;
    hdr->write         = writeDsMemMacBasedVlanKey;
    hdr->set           = setDsMemMacBasedVlanKey;
    hdr->fldSet        = fldSetDsMemMacBasedVlanKey;
    hdr->fldGet        = fldGetDsMemMacBasedVlanKey;
    hdr->print         = printDsMemMacBasedVlanKey;
    hdr->reset         = resetDsMemMacBasedVlanKey;
    hdr->destroy       = destroyDsMemMacBasedVlanKey;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacKeyLeft");
    hdr->name          = "VlanLookupDsMemMacKeyLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000170;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacKeyLeft;
    hdr->write         = writeVlanLookupDsMemMacKeyLeft;
    hdr->set           = setVlanLookupDsMemMacKeyLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemMacKeyLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemMacKeyLeft;
    hdr->print         = printVlanLookupDsMemMacKeyLeft;
    hdr->reset         = resetVlanLookupDsMemMacKeyLeft;
    hdr->destroy       = destroyVlanLookupDsMemMacKeyLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacKeyRight");
    hdr->name          = "VlanLookupDsMemMacKeyRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000180;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacKeyRight;
    hdr->write         = writeVlanLookupDsMemMacKeyRight;
    hdr->set           = setVlanLookupDsMemMacKeyRight;
    hdr->fldSet        = fldSetVlanLookupDsMemMacKeyRight;
    hdr->fldGet        = fldGetVlanLookupDsMemMacKeyRight;
    hdr->print         = printVlanLookupDsMemMacKeyRight;
    hdr->reset         = resetVlanLookupDsMemMacKeyRight;
    hdr->destroy       = destroyVlanLookupDsMemMacKeyRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacLeft");
    hdr->name          = "VlanLookupDsMemMacLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000190;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacLeft;
    hdr->write         = writeVlanLookupDsMemMacLeft;
    hdr->set           = setVlanLookupDsMemMacLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemMacLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemMacLeft;
    hdr->print         = printVlanLookupDsMemMacLeft;
    hdr->reset         = resetVlanLookupDsMemMacLeft;
    hdr->destroy       = destroyVlanLookupDsMemMacLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacRight");
    hdr->name          = "VlanLookupDsMemMacRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacRight;
    hdr->write         = writeVlanLookupDsMemMacRight;
    hdr->set           = setVlanLookupDsMemMacRight;
    hdr->fldSet        = fldSetVlanLookupDsMemMacRight;
    hdr->fldGet        = fldGetVlanLookupDsMemMacRight;
    hdr->print         = printVlanLookupDsMemMacRight;
    hdr->reset         = resetVlanLookupDsMemMacRight;
    hdr->destroy       = destroyVlanLookupDsMemMacRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacStaticLeft");
    hdr->name          = "VlanLookupDsMemMacStaticLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacStaticLeft;
    hdr->write         = writeVlanLookupDsMemMacStaticLeft;
    hdr->set           = setVlanLookupDsMemMacStaticLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemMacStaticLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemMacStaticLeft;
    hdr->print         = printVlanLookupDsMemMacStaticLeft;
    hdr->reset         = resetVlanLookupDsMemMacStaticLeft;
    hdr->destroy       = destroyVlanLookupDsMemMacStaticLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacStaticRight");
    hdr->name          = "VlanLookupDsMemMacStaticRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001c0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacStaticRight;
    hdr->write         = writeVlanLookupDsMemMacStaticRight;
    hdr->set           = setVlanLookupDsMemMacStaticRight;
    hdr->fldSet        = fldSetVlanLookupDsMemMacStaticRight;
    hdr->fldGet        = fldGetVlanLookupDsMemMacStaticRight;
    hdr->print         = printVlanLookupDsMemMacStaticRight;
    hdr->reset         = resetVlanLookupDsMemMacStaticRight;
    hdr->destroy       = destroyVlanLookupDsMemMacStaticRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacTsn");
    hdr->name          = "VlanLookupDsMemMacTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001d0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacTsn;
    hdr->write         = writeVlanLookupDsMemMacTsn;
    hdr->set           = setVlanLookupDsMemMacTsn;
    hdr->fldSet        = fldSetVlanLookupDsMemMacTsn;
    hdr->fldGet        = fldGetVlanLookupDsMemMacTsn;
    hdr->print         = printVlanLookupDsMemMacTsn;
    hdr->reset         = resetVlanLookupDsMemMacTsn;
    hdr->destroy       = destroyVlanLookupDsMemMacTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacTsnLeft");
    hdr->name          = "VlanLookupDsMemMacTsnLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001e0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacTsnLeft;
    hdr->write         = writeVlanLookupDsMemMacTsnLeft;
    hdr->set           = setVlanLookupDsMemMacTsnLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemMacTsnLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemMacTsnLeft;
    hdr->print         = printVlanLookupDsMemMacTsnLeft;
    hdr->reset         = resetVlanLookupDsMemMacTsnLeft;
    hdr->destroy       = destroyVlanLookupDsMemMacTsnLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacTsnRight");
    hdr->name          = "VlanLookupDsMemMacTsnRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0001f0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacTsnRight;
    hdr->write         = writeVlanLookupDsMemMacTsnRight;
    hdr->set           = setVlanLookupDsMemMacTsnRight;
    hdr->fldSet        = fldSetVlanLookupDsMemMacTsnRight;
    hdr->fldGet        = fldGetVlanLookupDsMemMacTsnRight;
    hdr->print         = printVlanLookupDsMemMacTsnRight;
    hdr->reset         = resetVlanLookupDsMemMacTsnRight;
    hdr->destroy       = destroyVlanLookupDsMemMacTsnRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacValidLeft");
    hdr->name          = "VlanLookupDsMemMacValidLeft";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000200;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacValidLeft;
    hdr->write         = writeVlanLookupDsMemMacValidLeft;
    hdr->set           = setVlanLookupDsMemMacValidLeft;
    hdr->fldSet        = fldSetVlanLookupDsMemMacValidLeft;
    hdr->fldGet        = fldGetVlanLookupDsMemMacValidLeft;
    hdr->print         = printVlanLookupDsMemMacValidLeft;
    hdr->reset         = resetVlanLookupDsMemMacValidLeft;
    hdr->destroy       = destroyVlanLookupDsMemMacValidLeft;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemMacValidRight");
    hdr->name          = "VlanLookupDsMemMacValidRight";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000210;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemMacValidRight;
    hdr->write         = writeVlanLookupDsMemMacValidRight;
    hdr->set           = setVlanLookupDsMemMacValidRight;
    hdr->fldSet        = fldSetVlanLookupDsMemMacValidRight;
    hdr->fldGet        = fldGetVlanLookupDsMemMacValidRight;
    hdr->print         = printVlanLookupDsMemMacValidRight;
    hdr->reset         = resetVlanLookupDsMemMacValidRight;
    hdr->destroy       = destroyVlanLookupDsMemMacValidRight;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("DsMemPhyPort");
    hdr->name          = "DsMemPhyPort";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 1;
    hdr->granularity   = roundupPow2(1);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000110;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readDsMemPhyPort;
    hdr->write         = writeDsMemPhyPort;
    hdr->set           = setDsMemPhyPort;
    hdr->fldSet        = fldSetDsMemPhyPort;
    hdr->fldGet        = fldGetDsMemPhyPort;
    hdr->print         = printDsMemPhyPort;
    hdr->reset         = resetDsMemPhyPort;
    hdr->destroy       = destroyDsMemPhyPort;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemPortColorStats");
    hdr->name          = "VlanLookupDsMemPortColorStats";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000230;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemPortColorStats;
    hdr->write         = writeVlanLookupDsMemPortColorStats;
    hdr->set           = setVlanLookupDsMemPortColorStats;
    hdr->fldSet        = fldSetVlanLookupDsMemPortColorStats;
    hdr->fldGet        = fldGetVlanLookupDsMemPortColorStats;
    hdr->print         = printVlanLookupDsMemPortColorStats;
    hdr->reset         = resetVlanLookupDsMemPortColorStats;
    hdr->destroy       = destroyVlanLookupDsMemPortColorStats;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemPortPolice");
    hdr->name          = "VlanLookupDsMemPortPolice";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000240;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemPortPolice;
    hdr->write         = writeVlanLookupDsMemPortPolice;
    hdr->set           = setVlanLookupDsMemPortPolice;
    hdr->fldSet        = fldSetVlanLookupDsMemPortPolice;
    hdr->fldGet        = fldGetVlanLookupDsMemPortPolice;
    hdr->print         = printVlanLookupDsMemPortPolice;
    hdr->reset         = resetVlanLookupDsMemPortPolice;
    hdr->destroy       = destroyVlanLookupDsMemPortPolice;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemPortPoliceCfg");
    hdr->name          = "VlanLookupDsMemPortPoliceCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000250;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemPortPoliceCfg;
    hdr->write         = writeVlanLookupDsMemPortPoliceCfg;
    hdr->set           = setVlanLookupDsMemPortPoliceCfg;
    hdr->fldSet        = fldSetVlanLookupDsMemPortPoliceCfg;
    hdr->fldGet        = fldGetVlanLookupDsMemPortPoliceCfg;
    hdr->print         = printVlanLookupDsMemPortPoliceCfg;
    hdr->reset         = resetVlanLookupDsMemPortPoliceCfg;
    hdr->destroy       = destroyVlanLookupDsMemPortPoliceCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemRouteTsn");
    hdr->name          = "VlanLookupDsMemRouteTsn";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000260;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemRouteTsn;
    hdr->write         = writeVlanLookupDsMemRouteTsn;
    hdr->set           = setVlanLookupDsMemRouteTsn;
    hdr->fldSet        = fldSetVlanLookupDsMemRouteTsn;
    hdr->fldGet        = fldGetVlanLookupDsMemRouteTsn;
    hdr->print         = printVlanLookupDsMemRouteTsn;
    hdr->reset         = resetVlanLookupDsMemRouteTsn;
    hdr->destroy       = destroyVlanLookupDsMemRouteTsn;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemStreamRcvyCfg");
    hdr->name          = "VlanLookupDsMemStreamRcvyCfg";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000270;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemStreamRcvyCfg;
    hdr->write         = writeVlanLookupDsMemStreamRcvyCfg;
    hdr->set           = setVlanLookupDsMemStreamRcvyCfg;
    hdr->fldSet        = fldSetVlanLookupDsMemStreamRcvyCfg;
    hdr->fldGet        = fldGetVlanLookupDsMemStreamRcvyCfg;
    hdr->print         = printVlanLookupDsMemStreamRcvyCfg;
    hdr->reset         = resetVlanLookupDsMemStreamRcvyCfg;
    hdr->destroy       = destroyVlanLookupDsMemStreamRcvyCfg;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemStreamRcvyCnt");
    hdr->name          = "VlanLookupDsMemStreamRcvyCnt";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000280;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemStreamRcvyCnt;
    hdr->write         = writeVlanLookupDsMemStreamRcvyCnt;
    hdr->set           = setVlanLookupDsMemStreamRcvyCnt;
    hdr->fldSet        = fldSetVlanLookupDsMemStreamRcvyCnt;
    hdr->fldGet        = fldGetVlanLookupDsMemStreamRcvyCnt;
    hdr->print         = printVlanLookupDsMemStreamRcvyCnt;
    hdr->reset         = resetVlanLookupDsMemStreamRcvyCnt;
    hdr->destroy       = destroyVlanLookupDsMemStreamRcvyCnt;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupDsMemStreamRcvySeq");
    hdr->name          = "VlanLookupDsMemStreamRcvySeq";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff000290;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupDsMemStreamRcvySeq;
    hdr->write         = writeVlanLookupDsMemStreamRcvySeq;
    hdr->set           = setVlanLookupDsMemStreamRcvySeq;
    hdr->fldSet        = fldSetVlanLookupDsMemStreamRcvySeq;
    hdr->fldGet        = fldGetVlanLookupDsMemStreamRcvySeq;
    hdr->print         = printVlanLookupDsMemStreamRcvySeq;
    hdr->reset         = resetVlanLookupDsMemStreamRcvySeq;
    hdr->destroy       = destroyVlanLookupDsMemStreamRcvySeq;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupMsgAdmInfo0");
    hdr->name          = "VlanLookupMsgAdmInfo0";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002a0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupMsgAdmInfo0;
    hdr->write         = writeVlanLookupMsgAdmInfo0;
    hdr->set           = setVlanLookupMsgAdmInfo0;
    hdr->fldSet        = fldSetVlanLookupMsgAdmInfo0;
    hdr->fldGet        = fldGetVlanLookupMsgAdmInfo0;
    hdr->print         = printVlanLookupMsgAdmInfo0;
    hdr->reset         = resetVlanLookupMsgAdmInfo0;
    hdr->destroy       = destroyVlanLookupMsgAdmInfo0;
    insertMem(root, hdr);

    hdr = NULL;
    hdr = (tMemRegHdr *)calloc(sizeof(tMemRegHdr), 1);
    assert(hdr != NULL);
    hdr->uid           = jsHash("VlanLookupTmpDsMemMac");
    hdr->name          = "VlanLookupTmpDsMemMac";
    hdr->type          = eMEM_INDIRECT;
    hdr->widthInQuad   = 0;
    hdr->granularity   = roundupPow2(0);
    hdr->entryNum.entries    = 1;
    hdr->addrBase.linearAddr = 0xff0002b0;
    hdr->entryList     = NULL;
    hdr->fldNameList   = NULL;
    hdr->rwLockList    = NULL;
    hdr->read          = readVlanLookupTmpDsMemMac;
    hdr->write         = writeVlanLookupTmpDsMemMac;
    hdr->set           = setVlanLookupTmpDsMemMac;
    hdr->fldSet        = fldSetVlanLookupTmpDsMemMac;
    hdr->fldGet        = fldGetVlanLookupTmpDsMemMac;
    hdr->print         = printVlanLookupTmpDsMemMac;
    hdr->reset         = resetVlanLookupTmpDsMemMac;
    hdr->destroy       = destroyVlanLookupTmpDsMemMac;
    insertMem(root, hdr);


    return 0;
} //End of mem init
